export type PlanRunStatus = 'scheduled' | 'active' | 'cancelled' | 'completed'
export type MicrocycleClassification = 'normal' | 'deload' | 'reload'
export type SessionStatus = 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'missed'
export type CompletionMode = 'as_prescribed' | 'fallback'
export type PerformanceStatus = 'draft' | 'finalized'
export type ExecutionMode = 'as_prescribed' | 'substituted' | 'skipped' | 'additional'
export type NextState = 'editable' | 'blocked' | 'locked' | 'none'
export type BlockedReason = 'previous_exposure_in_progress' | 'previous_exposure_not_performed' | 'session_started' | 'no_future_session' | 'run_not_active'
export type PrescriptionCompleteness = 'none' | 'partial' | 'complete'
export type EventType = 'plan_revision_changed' | 'personal_record' | 'deload_started' | 'reload_started' | 'vacation' | 'training_break' | 'observation'

export interface PlanRef { plan_id: number; code: string; name: string }
export interface RevisionRef { plan_revision_id: number; revision_no: number; status: string }
export interface MicrocycleRef { ordinal: number; starts_on: string; ends_on: string; classification: MicrocycleClassification; plan_revision_no: number }
export interface ExerciseRef { exercise_id: number; slug: string; name: string; variant_label: string }
export interface SetPlan { ordinal: number; role: string; rep_min: number; rep_max: number; target_rir: number | null }
export interface SetPrescription extends SetPlan { load_kg: number | null; comment: string | null }
export interface Divergence { load: 'below' | 'equal' | 'above' | null; reps: 'below_range' | 'at_floor' | 'in_range' | 'top_of_range' | 'above_range' | null; rir: 'deeper' | 'on_target' | 'shallower' | null }
export interface SetPerformance { ordinal: number; prescribed_set_ordinal: number | null; status: 'performed' | 'skipped'; load_kg: number | null; repetitions: number | null; rir: number | null; comment: string | null; recorded_at: string; is_additional: boolean; divergence: Divergence }

export interface PlanRunListItem { plan_run_id: number; name: string; status: PlanRunStatus; plan: PlanRef; starts_on: string; ends_on: string; microcycle_count: number; microcycle_duration_days: number; current_microcycle_ordinal: number | null }
export interface PlanRunListResponse { as_of: string; items: PlanRunListItem[] }
export interface RunHeader extends Omit<PlanRunListItem, 'current_microcycle_ordinal'> { initial_revision: RevisionRef; version: string }
export interface RunPosition { microcycle_ordinal: number | null; day_in_microcycle: number | null; run_day: number | null; run_days_total: number; days_left: number }
export interface EventDTO { event_id: number; event_type: EventType; title: string; occurred_at: string; date: string; microcycle_ordinal: number | null; day_in_microcycle: number | null; session: { session_id: number; workout_name: string } | null; exercise_trace: { exercise_trace_id: number; display_name: string } | null; from_revision_no: number | null; to_revision_no: number | null; body: string | null; source: 'system' | 'user'; metadata: Record<string, unknown> }
export interface Attendance { microcycle_ordinal: number; due: number; completed: number; missed: number; cancelled: number; in_progress: number; ratio: number | null }
export interface OverviewMicrocycle extends MicrocycleRef { revision_changed_here: boolean; is_current: boolean; sessions: Array<{ session_id: number; workout_trace_id: number; workout_name: string; scheduled_date: string; status: SessionStatus; completion_mode: CompletionMode | null }> }
export interface CurrentMicrocycleSession { session_id: number; workout_name: string; scheduled_date: string; status: SessionStatus; started_at: string | null; completed_at: string | null; prescription_completeness: PrescriptionCompleteness; exercise_count: number; performance: { status: PerformanceStatus; synced_exercise_count: number } | null }
export interface AnalysisReadinessItem { workout_trace_id: number; workout_name: string; state: NextState; blocked_reason: BlockedReason | null; basis_date: string | null; exercises_total: number; exercises_prescribed: number }
export interface LatestExposureExercise { exercise_trace_id: number; name: string; execution_mode: ExecutionMode | null; prescribed_summary: { set_count: number; top_load_kg: number | null; rep_min: number | null; rep_max: number | null; target_rir: number | null }; performed_reps: Array<number | null>; performed_rir: Array<number | null>; flags: string[] }
export interface PlanRunOverview { as_of: string; run: RunHeader; position: RunPosition; microcycles: OverviewMicrocycle[]; current_microcycle_sessions: CurrentMicrocycleSession[]; analysis_readiness: { target_microcycle_ordinal: number | null; workouts: AnalysisReadinessItem[] }; latest_exposure: { session_id: number; workout_trace_id: number; workout_name: string; scheduled_date: string; exercises: LatestExposureExercise[] } | null; attendance: Attendance[]; latest_events: EventDTO[] }

export interface QueueExercise { exercise_trace_id: number; slot_ordinal: number; name: string; prescription_saved: boolean; last_summary: { microcycle_ordinal: number; execution_mode: ExecutionMode; top_load_kg: number | null; reps: Array<number | null> } | null }
export interface QueueWorkout { workout_trace_id: number; workout_name: string; day_ordinal: number; target_session: { session_id: number; scheduled_date: string; status: SessionStatus } | null; basis_session: { session_id: number; scheduled_date: string; microcycle_ordinal: number } | null; state: NextState; blocked_reason: BlockedReason | null; blocked_detail: { session_id: number; scheduled_date: string; started_at: string | null; synced_exercise_count: number; exercise_count: number } | null; prescription_completeness: PrescriptionCompleteness; exercises: QueueExercise[] }
export interface AnalysisQueue { as_of: string; target_microcycle: MicrocycleRef | null; workouts: QueueWorkout[] }

export interface SavedPrescription { exercise_prescription_id: number; version: string; workout_prescription_version: string; sets: Array<{ ordinal: number; load_kg: number | null; comment: string | null }>; prescription_comment: string | null; updated_at: string }
export interface NextPrescription { state: NextState; blocked_reason: BlockedReason | null; target: ({ session_id: number; workout_trace_id: number; scheduled_date: string; microcycle: MicrocycleRef; session_status: SessionStatus }) | null; basis: ({ exercise_performance_id: number; microcycle_ordinal: number; scheduled_date: string; status: PerformanceStatus; execution_mode: ExecutionMode }) | null; plan_sets: SetPlan[]; plan_comment: string | null; defaults: { from_previous_prescription: Array<number | null>; from_previous_performance: Array<number | null>; from_seed_run: Array<number | null> | null }; prescription: SavedPrescription | null; suggestion: null }
export interface ExerciseExposure { microcycle: MicrocycleRef; session: { session_id: number; scheduled_date: string; status: SessionStatus; completion_mode: CompletionMode | null }; prescription: { exercise_prescription_id: number; exercise: ExerciseRef; plan_comment: string | null; prescription_comment: string | null; based_on_performance_microcycle_ordinal: number | null; sets: SetPrescription[] }; performance: ({ status: PerformanceStatus; execution_mode: ExecutionMode; actual_exercise: ExerciseRef | null; comment: string | null; sets: SetPerformance[]; summary: { total_reps: number; volume_load_kg: number; top_load_kg: number | null } }) | null }
export interface ExerciseTraceResponse { as_of: string; trace: { exercise_trace_id: number; workout_trace: { workout_trace_id: number; workout_name: string }; slot_ordinal: number; display_name: string; current_plan: { plan_revision_no: number; slot_role: string; exercise: ExerciseRef; sets: SetPlan[]; plan_comment: string | null; progression_model: string | null; load_step_kg: number | null }; continuity: { first_microcycle_ordinal: number; revisions_spanned: number[]; continues_from: { exercise_trace_id: number; display_name: string; from_microcycle_ordinal: number } | null; continued_by: { exercise_trace_id: number; display_name: string; from_microcycle_ordinal: number } | null } }; revision_transitions: Array<{ before_microcycle_ordinal: number; from_revision_no: number; to_revision_no: number; effective_on: string; slot_changes: string[]; event_id: number | null }>; exposures: ExerciseExposure[]; next: NextPrescription | null }
export interface PrescriptionPut { based_on_exercise_performance_id: number | null; sets: Array<{ ordinal: number; load_kg: number | null; comment: string | null }>; prescription_comment: string | null; expected_version: string | null }
export interface PrescriptionWriteResponse { next: NextPrescription; workout_prescription_completeness: PrescriptionCompleteness }

export interface WorkoutTraceListItem { workout_trace_id: number; workout_name: string; day_ordinal: number; exercise_trace_count: number }
export interface WorkoutTraceList { items: WorkoutTraceListItem[] }
export interface WorkoutTraceResponse { as_of: string; workout: { workout_trace_id: number; workout_name: string; day_ordinal: number }; columns: Array<{ exercise_trace_id: number; slot_ordinal: number; display_name: string; scheme: { set_count: number; rep_min: number | null; rep_max: number | null; target_rir: number | null }; top_load_series: Array<number | null>; delta_pct_first_to_latest: number | null; first_microcycle_ordinal: number; last_microcycle_ordinal: number | null }>; revision_transitions: Array<{ before_microcycle_ordinal: number; from_revision_no: number; to_revision_no: number; summary: string }>; rows: Array<{ microcycle: MicrocycleRef; session: { session_id: number; scheduled_date: string; status: SessionStatus; completion_mode: CompletionMode | null; started_at: string | null; completed_at: string | null }; prescription_completeness: PrescriptionCompleteness; performance_comment: string | null; volume_load_kg: number | null; progress_marker: null; cells: Array<{ exercise_trace_id: number; kind: 'performed' | 'prescribed' | 'empty' | 'not_in_trace'; execution_mode: ExecutionMode | null; actual_exercise_name: string | null; prescribed_top_load_kg: number | null; performed_top_load_kg: number | null; reps: Array<number | null>; flags: string[]; next_prescription_saved: boolean | null }> }> }

export interface TimelineDay { day_ordinal: number; date: string; session: { session_id: number; workout_name: string; status: SessionStatus; completion_mode: CompletionMode | null } | null }
export interface TimelineMicrocycle extends MicrocycleRef { revision_changed_here: boolean; is_current: boolean; notes: string | null; version: string; days: TimelineDay[]; attendance: Attendance; volume_load_kg: number | null; progress_marker: null; events: Array<{ event_id: number; event_type: EventType; title: string; occurred_at: string }> }
export interface MicrocycleTimeline { as_of: string; day_columns: Array<{ day_ordinal: number; workout_trace_id: number | null; workout_name: string | null }>; microcycles: TimelineMicrocycle[] }
export interface CalendarSession { session_id: number; scheduled_date: string; microcycle_ordinal: number; day_ordinal: number; workout_trace_id: number; workout_name: string; status: SessionStatus; completion_mode: CompletionMode | null; prescription_completeness: PrescriptionCompleteness; performance_status: PerformanceStatus | null; fallback_workout_name: string | null }
export interface CalendarResponse { as_of: string; sessions: CalendarSession[]; microcycle_bounds: Array<{ ordinal: number; starts_on: string; ends_on: string; classification: MicrocycleClassification }> }
export interface EventListResponse { items: EventDTO[]; next_cursor: string | null }

export interface LoadPoint { microcycle_ordinal: number; date: string; value: number | null; set_count: number; reps: Array<number | null>; status: PerformanceStatus; execution_mode: ExecutionMode }
export interface LoadSeries { exercise_trace_id: number; display_name: string; workout_trace_id: number; workout_name: string; points: LoadPoint[]; first_value: number | null; latest_value: number | null; delta_pct: number | null }
export interface LoadSeriesResponse { as_of: string; metric: 'top_set_load' | 'mean_set_load' | 'volume_load'; x_domain: Array<{ microcycle_ordinal: number; starts_on: string; classification: MicrocycleClassification; plan_revision_no: number }>; series: LoadSeries[]; workout_summaries: Array<{ workout_trace_id: number; workout_name: string; mean_delta_pct: number | null; series_count: number }> }

export interface PlanRunPreview { revision: RevisionRef; microcycle_duration_days: number; ends_on: string; session_count: number; workout_track_count: number; exercise_track_count: number; first_microcycle: Array<{ day_ordinal: number; date: string; workout_unit_name: string | null }>; overlapping_runs: Array<{ plan_run_id: number; name: string; starts_on: string; ends_on: string }> }
