export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      eyebrow: 'ÜBUNGSATLAS · PLANERSTELLUNG · TRAININGSANALYSE', title: 'Verstehe dein Training und baue einen Plan, der Sinn ergibt.', lead: 'Sieh, was eine Übung tatsächlich bewirkt, ordne Übungen zu einem Wochenplan und erkenne dessen modellierte Auswirkungen auf den Körper. Die Antworten bleiben einfach — und bei Bedarf kannst du tiefer einsteigen.', ctaPrimary: 'Atlas öffnen', ctaSecondary: 'Plananalyse ansehen', proof: ['über 150 dokumentierte Techniken', 'interaktive Anatomie', 'vom einzelnen Satz zum Mikrozyklus'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANALYSE',
    },
    audiences: {
      eyebrow: '01 · FÜR WEN', title: 'Und du — wo stehst du gerade?',
      beginner: { tag: 'ICH FANGE GERADE AN', title: 'Du hast gerade mit Krafttraining begonnen und alles wirkt unnötig kompliziert?', body: 'Sieh, welche Muskeln arbeiten, folge der Technik Schritt für Schritt und verstehe, wie Sätze, Wiederholungen und RIR einen Plan bilden.', link: 'Übungsatlas öffnen' },
      advanced: { tag: 'ICH WILL TIEFER EINSTEIGEN', title: 'Du trainierst schon länger und willst deinen Plan wirklich verstehen?', body: 'Vergleiche Varianten und analysiere Reizverteilung, Gelenkexposition und modellierte Erholungsschuld bis zum einzelnen Satz.', link: 'So funktioniert die Analyse' },
      coach: { tag: 'ICH PLANE FÜR ANDERE', title: 'Du betreust Athletinnen und Athleten? Plane und analysiere in einem System.', body: 'Baue Mikrozyklen mit klaren Übungsrollen, Alternativen, Zielen, RIR und Progressionsmodellen und analysiere anschließend den gespeicherten Plan.', link: 'Zum Bereich für Coaches' },
    },
    loop: {
      s1: { title: 'Übung verstehen', body: 'Technik, Muskeln und empfohlene Wiederholungsbereiche.' }, s2: { title: 'Split strukturieren', body: 'PPL, Ganzkörper oder eigener Aufbau — Tage, Pausen, Sätze und RIR.' }, s3: { title: 'Analyse ausführen', body: 'Reizverteilung, Erholung und Gelenkexposition — bis zum Satz.' }, s4: { title: 'Plan ausführen und Fortschritt verfolgen', body: 'Ausführung, Satzhistorie und Krafttrend — die nächste Entwicklungsstufe.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ÜBUNGSATLAS', title: 'Nicht einfach „Bankdrücken“. Eine konkrete Technik mit konkreten Annahmen.', body: 'Jede Übung ist als definierte Variante beschrieben: Gerät, Setup, Bewegungsbahn, Umfang, Kriterien für technisches Versagen und ein eigenes modelliertes Expositionsprofil.', etuRows: { title: 'Muskelexposition in Zahlen', body: 'Rohe cm², Anteil der geschätzten Kapazität und relative Intensität.' }, etuAnatomy: { title: 'Reizverteilung am Körper', body: 'Auf die geschätzte FCSA normalisierte Heatmap.' }, technique: { title: 'Technik dieser Variante', body: 'Setup → Ausführung → wann stoppen.' }, classification: { title: 'Klassifikation der Variante', body: 'Mechanische Stufe, Widerstandsquelle, Ausführungsmuster.' }, disclaimer: 'auf einen gemeinsamen Referenzathleten normalisierte Werte · deine Werte können abweichen',
    },
    planBuilder: {
      eyebrow: '03 · PLANERSTELLUNG', title: 'Baue einen Plan aus den Teilen, die wirklich zählen.', body: 'Definiere Trainings- und Ruhetage, Rollen, Ziele, Alternativen, Sätze, Wiederholungsbereiche und RIR. Ein Plan ist ein geordneter Mikrozyklus, keine Notiz.', roles: { label: 'ROLLEN', body: 'Primäre Progression · sekundäre Progression · Volumenakkumulation · Zubehör.' }, slot: { label: 'SLOT', body: 'Bewahre die Absicht des Slots, auch wenn die Übung ersetzt werden muss.' }, rest: { label: 'PAUSE', body: 'Ein Ruhetag ist kein leeres Feld — er bestimmt die Zeit zwischen Reizen.' }, ctaPrimary: 'Planerstellung öffnen', ctaSecondary: 'Analyse ansehen', panelDays: { left: 'GEORDNETER MIKROZYKLUS', right: '7 Tage · D01–D07' }, panelSlot: { left: 'SLOT · SATZVORGABE', right: 'Rolle · Standardübung · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · PLANANALYSE', title: 'Ein Plan ist mehr als die Summe seiner Sätze.', body: 'Analysiere einen gespeicherten Entwurf und sieh, wohin der Reiz geht, welche Muskeln gezielt oder nebenbei arbeiten und wie das Modell Erholungsschuld zwischen Tagen fortschreibt.', strip: { left: 'MIKROZYKLUS · TAGESGRENZEN', right: 'Analyse des gespeicherten Entwurfs · nach Änderungen aktualisieren' }, recovery: { title: 'Lokale Erholung nach dem Training', meta: 'hours_to_fresh' }, ranking: { title: 'Wöchentliche Reizverteilung', meta: 'ETU/cm²/7d' }, debts: { title: 'Stärkste modellierte Schulden', body: 'Bereitschaft an der Tagesgrenze.' }, targeted: { title: 'Gezielte und beiläufige Arbeit', body: 'Sieh nicht nur die geplante Zielarbeit, sondern auch die Nebenarbeit der gewählten Übungen.' }, provenance: { title: 'Jede Summe hat eine Quelle', body: 'Das Ergebnis führt zu Tag, Übung und Satz — samt effektiven Wiederholungen und Modellparametern.' }, disclaimer: 'Modellergebnis · kein Muskelkater, keine Gewebeheilungszeit und keine Verletzungsrisikobewertung',
    },
    muscleAtlas: {
      eyebrow: '05 · MUSKELATLAS', title: 'Verstehe den Muskel, bevor du seine Sätze zählst.', body: 'Anatomie, Funktion, Architektur, geschätzte Fasertypverteilung und Übungen mit der höchsten modellierten Exposition — an einem Ort.', specs: [{ k: 'MORPHOLOGIE', v: 'Masse, Volumen' }, { k: 'ARCHITEKTUR', v: 'Fiederung, Faserlänge' }, { k: 'FASERN', v: 'geschätzte Verteilung' }, { k: 'FCSA', v: 'Kapazitätsreferenz' }], note: 'FCSA ist weder eine Faserzahl noch ein Maß für Hypertrophiepotenzial. Es ist ein geschätzter kraftübertragender Querschnitt als gemeinsamer Nenner.', link: 'Vom Muskel zu den Übungen',
    },
    features: {
      eyebrow: '06 · WEITERE MÖGLICHKEITEN', title: 'Der Rest des Systems, kurz gefasst', technique: { title: 'Technikbibliothek', body: 'Setup, Bewegung, ROM, Hinweise, technisches Versagen, RIR und häufige Fehler.' }, io: { title: 'Plan importieren / exportieren', body: 'Übertrage eine vereinfachte Struktur zur externen Analyse und importiere ein validiertes Dokument zurück.' }, mobile: { title: 'Mobiler Trainingsmodus', body: 'Heutiges Training und Technik während der Einheit griffbereit.' }, progress: { title: 'Fortschritt verfolgen', body: 'Ausführungshistorie, Krafttrends und automatisierte Progressionsmodelle — auch im Coaching.' }, knowledge: { title: 'Wissensbasis', body: 'Muskelartikel funktionieren bereits; die wachsende Wissensbasis wird auch Gelenke abdecken und Atlas und Analyse verbinden.' },
    },
    model: {
      eyebrow: '07 · UNTER DER HAUBE', title: 'Wir messen Biologie nicht über einen Bildschirm. Wir bauen ein transparentes Entscheidungsmodell.', body: 'Krafttraining findet unter Unsicherheit statt. Agonez ordnet Annahmen, schätzt Folgen eines Plans und zeigt die Herkunft eines Ergebnisses. Wo keine Messung vorliegt, nennen wir es Modell.', chain: ['Übung', 'Muskeln', 'mechanischer Reiz', 'Erholung', 'Planwoche', 'Progression'], expandHint: 'ÖFFNEN, UM DETAILS ZU SEHEN',
      etu: { title: 'ETU', summary: 'Wie viel Spannungsreiz einer effektiven Wiederholung einen Muskel erreicht.', caveat: 'Das ist weder EMG noch Aktivierungsprozent oder eine Hypertrophiemessung.' }, fcsa: { title: 'FCSA', summary: 'Ein gemeinsamer Nenner, um große und kleine Muskeln auf einer Skala zu vergleichen.', caveat: 'Mechanischer Bedarf, nicht Ermüdung und keine Faserzahl.' }, recovery: { title: 'MRU · JRU', summary: 'Modellierte Muskel- und Gelenkschuld: steigt nach einem Satz und sinkt zwischen Einheiten.', caveat: 'Vergleichswerkzeug, keine biologische Uhr und keine Verletzungsrisikobewertung.' }, reference: { title: 'Referenzathlet', summary: 'Atlas-Metriken sind auf eine klar beschriebene Basis kalibriert.', caveat: 'Deine eigenen Werte können deutlich abweichen.' }, limits: { title: 'Grenzen des Modells', summary: 'Was das Modell nicht sieht — offen benannt statt versteckt.', note: 'Modellversion, Annahmen und Diagnostik bleiben in der Anwendung sichtbar' },
    },
    coaches: {
      eyebrow: '08 · FÜR COACHES', title: 'Betreue mehr Athleten, ohne Planqualität aufzugeben.', body: 'Mikrozyklusvorlage, fertige Alternativen und automatische Prüfung ersetzen neu aufgebaute Tabellen. Die bisherige Übertragungszeit bleibt fürs Coaching.', reuse: { title: 'Ein wiederverwendbarer Plan', body: 'Einmal mit Rollen, Sätzen und RIR gebaut, wird der Mikrozyklus zum Ausgangspunkt für die nächste Person.' }, swap: { title: 'Alternative in Sekunden', body: 'Ein besetztes Gerät oder empfindliches Gelenk zerstört den Plan nicht — der Slot behält seine Absicht.' }, audit: { title: 'Prüfung statt Handzählung', body: 'Reizverteilung, Nebenarbeit und modellierte Schuld werden berechnet; du beurteilst das Ergebnis.' }, argument: { title: 'Eine Begründung für Athleten', body: 'Zeige, warum der Plan so aussieht. Der JSON-Export nimmt die ganze Struktur mit.' }, cta: 'Erste Vorlage bauen', note: 'Athletenkonten und Ausführungshistorie sind geplant — heute arbeitest du an deinen eigenen Plänen.',
    },
    roadmap: {
      eyebrow: '09 · WOHIN ES GEHT', title: 'Heute: Planung und Analyse. Als Nächstes: Ausführung und Coaching über Zeit.', athlete: { title: 'Athletenbetreuung', body: 'Die nächste Stufe verbindet den Plan mit der Ausführungshistorie: Lasten, Wiederholungen, RIR, Übungswechsel, Deloads und e1RM-Trends.', flow: ['Plan', 'Vorgabe', 'Ausführung', 'Historie'] }, mobile: { title: 'Mobiler Trainingsmodus', body: 'Im Training zählt der nächste Satz. Der geplante Modus zeigt die heutige Einheit und ermöglicht schnellen Technikzugriff.', flow: ['Heutige Einheit', 'Ausführung erfassen', 'Technik'] },
    },
    cta: { title: 'Beginne mit einer Übung. Sieh, wie tief du gehen kannst.', body: 'Vom Bewegungsverständnis zur Planentscheidung — einfache Antworten oben, transparente Modelle darunter.', primary: 'Übungsatlas öffnen', secondary: 'Planentwurf bauen' }, footer: { navigation: 'Navigation der Startseite', links: { exerciseAtlas: 'Übungsatlas', muscleAtlas: 'Muskelatlas', planBuilder: 'Planerstellung', analysis: 'Analyse', model: 'Modell' }, disclaimer: 'Agonez-Werte sind modellierte Schätzungen auf Basis expliziter Annahmen. Sie sind keine Messungen deines Körpers und keine medizinische Beratung.' }, badges: { comingSoon: 'DEMNÄCHST', experimental: 'EXPERIMENTELLES MODELL' },
  },
}
