export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      betaBadge: 'PRIVATE BETA · HERBST 2026',
      waitlist: { label: 'E-Mail-Adresse', placeholder: "du{'@'}beispiel.de", button: 'Zur Warteliste', note: 'Kein Spam. Nur eine E-Mail, sobald deine Einladung bereit ist.', emailSubject: 'Private Beta von Agonez — Wartelistenanfrage', emailBody: 'Hallo,\n\nich möchte auf die Warteliste für die private Beta von Agonez.\n\nMeine E-Mail-Adresse: {email}\n\nDafür möchte ich Agonez nutzen:\n' },
      eyebrow: 'ÜBUNGSATLAS · PLANERSTELLUNG · PROGRESSIONSBEGLEITUNG', title: 'Verstehe dein Training und baue einen Plan, der Sinn ergibt.', lead: 'Sieh, welche Muskeln deine Übung wirklich anspricht. Baue daraus einen Wochenplan und sieh, was dieser Plan mit deinem Körper macht.', ctaPrimary: 'Atlas öffnen', ctaSecondary: 'Plananalyse ansehen', proof: ['über 150 Übungen', 'interaktive Anatomie', 'von einer Wiederholung zum Mikrozyklus'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANALYSE',
    },
    audiences: {
      eyebrow: '01 · FÜR WEN', title: 'Und du — wo stehst du gerade?',
      beginner: { tag: 'ICH FANGE GERADE AN', title: 'Du fängst mit Krafttraining an und alles wirkt unnötig kompliziert?', body: 'Sieh, welche Muskeln arbeiten, und folge der Technik Schritt für Schritt. Probiere die Planerstellung aus.', link: 'Übungsatlas öffnen' },
      advanced: { tag: 'ICH WILL TIEFER EINSTEIGEN', title: 'Du trainierst schon länger und willst deinen Plan wirklich verstehen?', body: 'Vergleiche Varianten und analysiere Reizverteilung, Gelenkexposition und modellierte Erholungsschuld. Prüfe, ob dein Plan optimal ist.', link: 'So funktioniert die Analyse' },
      coach: { tag: 'ICH PLANE FÜR ANDERE', title: 'Du betreust Athletinnen und Athleten? Du möchtest ein professionelles Werkzeug?', body: 'Baue Mikrozyklen mit klaren Übungsrollen, Alternativen, Zielen, RIR und Progressionsmodellen. Verfolge anschließend den Fortschritt deiner Athleten.', link: 'Zum Bereich für Coaches' },
    },
    loop: {
      s1: { title: 'Übungen verstehen', body: 'Technik, Muskeln und empfohlene Wiederholungsbereiche.' }, s2: { title: 'Split strukturieren', body: 'PPL, Ganzkörper oder eigener Aufbau — Sätze, RIR, Last und Progressionsmodelle.' }, s3: { title: 'Analyse ausführen', body: 'Reizverteilung sowie Muskel- und Gelenkerholung — bis zum einzelnen Satz.' }, s4: { title: 'Plan ausführen und Fortschritt verfolgen', body: 'Ausführung, Satzhistorie und Krafttrend — die nächste Stufe deiner Entwicklung.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ÜBUNGSATLAS', title: 'Nicht einfach „Bankdrücken“. Eine konkrete Technik mit konkreten Annahmen.', body: 'Jede Übung ist als definierte Variante beschrieben: Gerät, Setup, Bewegungsbahn, Umfang, Kriterien für technisches Versagen und ein eigenes modelliertes Expositionsprofil.', etuRows: { title: 'Muskelexposition in Zahlen', body: 'Rohe cm², Anteil der geschätzten Kapazität und relative Intensität.' }, etuAnatomy: { title: 'Reizverteilung am Körper', body: 'Auf die geschätzte FCSA normalisierte Heatmap.' }, technique: { title: 'Technik dieser Variante', body: 'Setup → Ausführung → wann stoppen.' }, classification: { title: 'Klassifikation der Variante', body: 'Mechanische Stufe, Widerstandsquelle, Ausführungsmuster.' }, disclaimer: 'auf einen gemeinsamen Referenzathleten normalisierte Werte · deine Werte können abweichen',
    },
    planBuilder: {
      eyebrow: '03 · PLANERSTELLUNG', title: 'Baue einen Plan aus den Teilen, die wirklich zählen.', body: 'Definiere Trainings- und Ruhetage, Rollen, Ziele, Alternativen, Sätze, Wiederholungsbereiche und RIR. Ein Plan ist ein geordneter Mikrozyklus, keine Notiz.', roles: { label: 'ROLLEN', body: 'Primäre Progression · sekundäre Progression · Volumenakkumulation · Zubehör.' }, slot: { label: 'SLOT', body: 'Bewahre die Absicht des Slots, auch wenn die Übung ersetzt werden muss.' }, rest: { label: 'PAUSE', body: 'Ein Ruhetag ist kein leeres Feld — er bestimmt die Zeit zwischen Reizen.' }, ctaPrimary: 'Planerstellung öffnen', ctaSecondary: 'Analyse ansehen', panelDays: { left: 'GEORDNETER MIKROZYKLUS', right: '7 Tage · D01–D07' }, panelSlot: { left: 'SLOT · SATZVORGABE', right: 'Rolle · Standardübung · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · PLANANALYSE', title: 'Ein Plan ist mehr als die Summe seiner Sätze.', body: 'Analysiere einen gespeicherten Entwurf und sieh, wohin der Reiz geht, welche Muskeln gezielt oder nebenbei arbeiten und ob sie sich zwischen den Tagen erholen können.', strip: { left: 'MIKROZYKLUS · TAGESGRENZEN', right: 'Analyse des gespeicherten Entwurfs · nach Änderungen aktualisieren' }, recovery: { title: 'Erholung nach dem Training', meta: 'hours_to_fresh' }, ranking: { title: 'Wöchentliche Satzzahl für jeden Muskel', meta: 'ETU/cm²/7d' }, debts: { title: 'Erholungsstatus der Muskeln', body: 'Wann ist der Muskel wieder frisch?' }, targeted: { title: 'Gezielte und beiläufige Arbeit', body: 'Sieh nicht nur die geplante Zielarbeit, sondern auch die Nebenarbeit der gewählten Übungen.' }, provenance: { title: 'Jede Summe hat eine Quelle', body: 'Das Ergebnis führt zu Tag, Übung und Satz — samt effektiven Wiederholungen und Modellparametern.' }, disclaimer: 'Modellergebnis · kein Muskelkater, keine Gewebeheilungszeit und keine Verletzungsrisikobewertung',
    },
    muscleAtlas: {
      eyebrow: '05 · MUSKELATLAS', title: 'Verstehe den Muskel, bevor du seine Sätze zählst.', body: 'Anatomie, Funktion, Architektur, geschätzte Fasertypverteilung und die besten Übungen — an einem Ort.', specs: [{ k: 'MORPHOLOGIE', v: 'Masse, Volumen' }, { k: 'ARCHITEKTUR', v: 'Fiederung, Faserlänge' }, { k: 'FASERN', v: 'geschätzter Anteil von Typ I und II' }, { k: 'FCSA', v: 'Krafteinheit' }], note: 'FCSA ist weder eine Faserzahl noch ein Maß für Hypertrophiepotenzial. Es ist ein geschätzter kraftübertragender Querschnitt als gemeinsamer Nenner.', link: 'Vom Muskel zu den Übungen',
    },
    features: {
      eyebrow: '06 · WEITERE MÖGLICHKEITEN', title: 'Der Rest des Systems, kurz gefasst', technique: { title: 'Technikbibliothek', body: 'Setup, Bewegung, ROM, Hinweise, technisches Versagen, RIR und häufige Fehler.' }, io: { title: 'Plan importieren / exportieren', body: 'Ein Plan lässt sich einfach als Text herunterladen oder hochladen. Mit KI kannst du deine eigenen Pläne leicht importieren.' }, mobile: { title: 'Mobiles Training', body: 'Öffne die App beim Training und lass dich durch die Einheit führen.' }, progress: { title: 'Fortschritt verfolgen', body: 'Ausführungshistorie, Krafttrends und automatisierte Progressionsmodelle — auch im Coaching.' }, knowledge: { title: 'Wissensbasis', body: 'Eine wissenschaftlich fundierte Wissensbasis als Blog. Der Atlas wird außerdem Bewegungen und Gelenke abdecken.' },
    },
    model: {
      eyebrow: '07 · UNTER DER HAUBE', title: 'Wir messen Biologie nicht über einen Bildschirm. Wir bauen ein transparentes Entscheidungsmodell.', body: 'Krafttraining findet unter Unsicherheit statt. Agonez ordnet Annahmen, schätzt Folgen eines Plans und zeigt die Herkunft eines Ergebnisses. Wo keine Messung vorliegt, nennen wir es Modell.', chain: ['Übung', 'Muskeln', 'mechanischer Reiz', 'Erholung', 'Planwoche', 'Progression'], expandHint: 'ÖFFNEN, UM DETAILS ZU SEHEN',
      etu: { title: 'ETU', summary: 'Wie viel Spannungsreiz einer effektiven Wiederholung einen Muskel erreicht.', body: 'Eine Übung „trainiert“ nicht einfach die Brust. Sie hat ein Profil: Ein Teil der Spannung geht an die Hauptantriebsmuskeln, ein Teil an die Stabilisatoren. ETU (Effective Tension Unit) schätzt diese Verteilung für eine effektive Wiederholung, sodass zwei Varianten derselben Bewegung numerisch verglichen werden können.', caveat: 'Das ist weder EMG noch Aktivierungsprozent oder eine Hypertrophiemessung.' }, fcsa: { title: 'FCSA', summary: 'Ein gemeinsamer Nenner, um große und kleine Muskeln auf einer Skala zu vergleichen.', caveat: 'Mechanischer Bedarf, nicht Ermüdung und keine Faserzahl.' }, recovery: { title: 'MRU · JRU', summary: 'Modellierte Muskel- und Gelenkschuld: steigt nach einem Satz und sinkt zwischen Einheiten.', body: 'Jeder Satz fügt den Muskeln lokale Schuld hinzu — umso mehr, je näher er am technischen Versagen liegt. Die Schuld sinkt mit der Zeit, daher gehört der Abstand zwischen Reizen für denselben Muskel zum Plan. JRU macht dasselbe für die Gelenke.', caveat: 'Vergleichswerkzeug, keine biologische Uhr und keine Verletzungsrisikobewertung.' }, reference: { title: 'Referenzathlet', summary: 'Atlas-Metriken sind auf eine klar beschriebene Basis kalibriert.', caveat: 'Dein Ausgangswert kann deutlich abweichen, die relativen Verhältnisse jedoch nur geringfügig.' }, limits: { title: 'Grenzen des Modells', summary: 'Was das Modell nicht sieht — offen benannt statt versteckt.', note: 'Modellversion, Annahmen und Diagnostik bleiben in der Anwendung sichtbar' },
    },
    coaches: {
      eyebrow: '08 · FÜR COACHES', title: 'Betreue mehr Athleten, ohne Abstriche bei der Betreuung zu machen.', body: 'Mikrozyklusvorlage, fertige Alternativen und automatische Prüfung ersetzen neu aufgebaute Tabellen. Die bisherige Übertragungszeit bleibt fürs Coaching.', reuse: { title: 'Ein wiederverwendbarer Plan', body: 'Einmal mit Rollen, Sätzen und RIR gebaut, wird der Mikrozyklus zum Ausgangspunkt für die nächste Person.' }, swap: { title: 'Alternative in Sekunden', body: 'Ein besetztes Gerät oder empfindliches Gelenk zerstört den Plan nicht — der Slot behält seine Absicht.' }, audit: { title: 'Prüfung statt Handzählung', body: 'Reizverteilung, Nebenarbeit, modellierte Schuld zwischen Tagen und Lastprogression werden automatisch berechnet — du beurteilst das Ergebnis.' }, argument: { title: 'Einfaches Teilen', body: 'Sende einem Athleten einen Link und er erhält einen fertigen Plan, den er in der App öffnen kann.' }, adaptation: { title: 'Jeder Athlet ist anders', body: 'Du siehst, dass sich ein Athlet mit dem Plan nicht erholt? Mit der Zeit lernst du ihn besser kennen und kannst die Modellparameter gezielt auf ihn abstimmen.' }, cta: 'Erste Vorlage bauen', note: 'Athletenkonten und Ausführungshistorie sind geplant — heute arbeitest du an deinen eigenen Plänen.',
    },
    roadmap: {
      eyebrow: '09 · WOHIN ES GEHT', title: 'Heute: Planung und Analyse. Morgen: Ausführung und Coaching über Zeit.', athlete: { title: 'Athletenbetreuung', body: 'Die nächste Stufe verbindet den Plan mit der Ausführungshistorie: Lasten, Wiederholungen, RIR, Übungswechsel, Deloads und e1RM-Trends.', flow: ['Plan', 'Vorgabe', 'Ausführung', 'Historie'] }, mobile: { title: 'Mobiles Training', body: 'Im Training zählt der nächste Satz. Der geplante Modus zeigt die heutige Einheit und ermöglicht schnellen Technikzugriff.', flow: ['Heutige Einheit', 'Ausführung erfassen', 'Technik'] },
    },
    cta: { eyebrow: 'EINE OFFENE EINLADUNG', title: 'Hilf der Menschheit, Exzellenz im Training zu erreichen.', body: 'Agonez befindet sich in einer frühen Phase. Wir entwickeln es an der Schnittstelle von Training, Wissenschaft, Engineering und Produkt.', bodySecondary: 'Wenn du in einem dieser Bereiche arbeitest und ein Werkzeug mitgestalten möchtest, das auf echten Problemen, Fachwissen und kritischem Feedback basiert, suchen wir genau dich.', rolesLabel: 'Menschen und Perspektiven, die wir kennenlernen möchten', roles: ['Personal Trainer', 'Athletinnen & Athleten', 'Biomechaniker', 'Sportwissenschaft', 'Produkt & Engineering', 'UX / Research', 'Marketing', 'Frühe Partner & Early Adopters'], action: 'Lass uns sprechen', note: 'Offen für fokussierte Gespräche und klar umrissene Zusammenarbeit. Öffnet dein E-Mail-Programm.', emailSubject: 'Agonez gemeinsam aufbauen', emailBody: 'Hallo,\n\nich möchte über eine Mitarbeit an Agonez sprechen.\n\nMein Hintergrund oder meine Idee:\n' }, footer: { navigation: 'Navigation der Startseite', links: { exerciseAtlas: 'Übungsatlas', muscleAtlas: 'Muskelatlas', planBuilder: 'Planerstellung', analysis: 'Analyse', model: 'Modell' }, disclaimer: 'Agonez-Werte sind modellierte Schätzungen auf Basis expliziter Annahmen. Sie sind keine Messungen deines Körpers und keine medizinische Beratung.' }, badges: { comingSoon: 'DEMNÄCHST', experimental: 'EXPERIMENTELLES MODELL' },
  },
}
