export default {
  execution: {
    shellStatus: 'ESECUZIONE · DESKTOP', nav: 'Esecuzione',
    tabs: { overview: 'Panoramica', analysis: 'Analisi', timeline: 'Cronologia', loads: 'Carichi' },
    common: { kg: 'kg', rir: 'RIR', reps: 'rip.', today: 'Oggi', close: 'Chiudi', save: 'Salva', cancel: 'Annulla', edit: 'Modifica', locked: 'Bloccato', loading: 'Caricamento dei dati di esecuzione…', marker: 'MARKER.X', reserved: 'riservato' },
    run: {
      eyebrow: 'Esecuzione del piano', from: 'Da {plan}', all: 'Tutte le esecuzioni ({count})', new: 'Nuova esecuzione', meta: '{start} → {end} · {count} × microcicli di {days} giorni',
      status: { scheduled: 'Pianificata', active: 'Attiva', cancelled: 'Annullata', completed: 'Completata' }, emptyTitle: 'Nessuna esecuzione del piano', emptyBody: 'Un’esecuzione colloca un piano di allenamento nel calendario reale.', loadError: 'Impossibile caricare l’esecuzione', listError: 'Impossibile caricare le esecuzioni.',
    },
    status: { scheduled: 'Pianificata', in_progress: 'In corso', completed: 'Completata', cancelled: 'Annullata', missed: 'Saltata', today: 'Oggi' }, completion: { as_prescribed: 'Come prescritto', fallback: 'Alternativa' }, classification: { normal: 'Normale', deload: 'Deload', reload: 'Reload' },
    blocked: {
      previous_exposure_in_progress: 'L’esposizione precedente è ancora in corso.', previous_exposure_not_performed: 'L’esposizione prescritta precedente non è stata eseguita.', session_started: 'Questa sessione è già iniziata.', no_future_session: 'Non ci sono sessioni successive in questa esecuzione.', run_not_active: 'Questa esecuzione non è attiva.', unknown: 'Questa prescrizione non è ancora modificabile.',
    },
    overview: {
      where: 'Posizione attuale', position: 'Microciclo {current} di {total} · giorno {day} di {days}', positionSub: 'giorno {runDay} di {runDays}, {left} giorni rimanenti', thisMicrocycle: 'Questo microciclo', sessions: 'Sessioni nel calendario', analysisEyebrow: 'Analisi post-allenamento · successivo: MC{mc}', prescriptions: 'Prescrizioni per il prossimo microciclo',
      continue: 'Continua {workout}', waiting: 'In attesa', saved: '{saved} / {total} salvate', latest: 'Ultima esposizione · {workout} · {date}', comparison: 'Prescritto e svolto', exercise: 'Esercizio', prescribed: 'Prescritto', performed: 'Svolto', note: 'Nota', adherence: 'Aderenza', didPlanHappen: 'Il piano è stato eseguito?',
      journal: 'Diario', latestEvents: 'Eventi recenti', allEvents: 'Tutti ({count})', observationPlaceholder: 'Registra un’osservazione…', log: 'Registra', fullCalendar: 'Calendario completo', readOnlyDraft: 'La prestazione in corso proviene dall’app mobile ed è di sola lettura qui.', noCurrentSessions: 'Nessuna sessione nel microciclo corrente.', noExposure: 'Nessuna esposizione finalizzata.', noEvents: 'Nessun evento registrato.',
    },
    analysis: {
      queue: 'Prescrivi MC{mc}', queueToggle: 'Coda', progress: '{saved} di {total} salvate · {locked} bloccate', workoutTrace: 'storico dell’unità di allenamento', ready: 'Pronto', keyboard: 'J / K', notStarted: 'Non iniziato', unsaved: 'Modifiche non salvate', saved: 'Salvato', locked: 'Bloccato',
      confirmLeave: 'Ci sono prescrizioni non salvate. Uscire dall’Analisi? Le bozze resteranno in questa sessione del browser.', basedOn: 'Basato su MC{mc} · {date}', noSummary: 'Nessuna esposizione svolta', loadError: 'Impossibile caricare l’Analisi.', traceEyebrow: '{workout} · slot {slot} · storico dell’esercizio', plan: "piano: {sets} × {min}–{max} {'@'}RIR {rir}",
      continuity: 'uno storico da MC{from} attraverso le revisioni {revisions}', planNote: 'Nota del piano', previous: 'Esercizio precedente', next: 'Esercizio successivo', position: '{current} / {total}', loadStrip: 'Carico per serie · kg', prescribedLegend: 'prescritto', performedLegend: 'svolto', nextLegend: 'successivo',
      exposure: 'Esposizione', set: 'Serie {set}', comments: 'Commenti', prescription: 'Prescrizione', actual: 'Effettivo', draft: 'Bozza', setSkipped: 'serie saltata', notSynced: 'non sincronizzato', additional: '+AGG.', missed: 'Saltata', cancelled: 'Annullata', scheduled: 'Pianificata', inProgress: 'In corso',
      substituted: 'Sostituito con: {exercise}', exerciseSkipped: 'Esercizio saltato — nessuna serie eseguita', noComment: 'Nessun commento', revision: 'Revisione del piano r{from} → r{to}', revisionBody: 'In vigore da MC{mc} · {date}. {changes}. Continua lo stesso storico dell’esercizio.', compare: 'Confronta revisioni',
      expand: 'Espandi i dettagli di MC{mc}', collapse: 'Comprimi i dettagli di MC{mc}', session: 'Sessione', recorded: 'Registrato', setComment: 'Commento della serie', performanceAfterSync: 'La prestazione appare dopo la sincronizzazione della sessione dal mobile.',
      flags: { substituted: 'Sostituito', skipped: 'Saltato', additional_set: 'Serie aggiuntiva', reps_below_range: 'Ripetizioni sotto l’intervallo', reps_at_floor: 'Ripetizioni al limite inferiore', top_of_range: 'Limite superiore dell’intervallo', load_reduced: 'Carico ridotto', personal_record: 'Record personale' },
    },
    editor: {
      eyebrow: 'Prossima prescrizione', title: '{exercise} · MC{mc}', scheduled: '{workout} · {date} · modificabile fino all’inizio della sessione', status: { clean: 'Non iniziato', dirty: 'Non salvato', saving: 'Salvataggio…', saved: 'Salvato', locked: 'Bloccato' },
      basis: 'Basato sulla prestazione MC{mc} · {date} · finalizzata', firstExposure: 'Prima esposizione — non ci sono prestazioni precedenti.', evidence: 'Rip. {reps} · carichi {loads} kg · {top} al limite superiore · {floor} al limite inferiore · {deeper} più profondo del RIR obiettivo',
      startFrom: 'Inizia da', previousPrescription: 'Prescrizione MC{mc}', previousPerformance: 'Prestazione MC{mc}', allMinus: 'tutte −{step}', allPlus: 'tutte +{step}', suggestion: 'Suggerimento', suggestionNone: 'Modello di progressione · nessuno', suggestionBody: 'Nessun modello di progressione è assegnato a questo slot.',
      fromPlan: 'Dal piano', load: 'Carico kg', last: 'ultimo {load}', comment: 'Commento della serie (facoltativo)', selectSet: 'Seleziona serie {set}', minus: 'Serie {set}: sottrai {step} kg', plus: 'Serie {set}: aggiungi {step} kg', apply: 'Applica', selected: 'a {count} selezionate',
      prescriptionComment: 'Commento della prescrizione · solo per questa esposizione', commentPlaceholder: 'Su cosa dovrebbe concentrarsi l’atleta la prossima volta?', planOwned: 'Numero di serie, intervallo di ripetizioni e RIR provengono dalla revisione r{revision}. Modificali nel Creatore di piani per i microcicli futuri.',
      discard: 'Scarta', save: 'Salva', saveNext: 'Salva e vai all’esercizio successivo', reload: 'Ricarica storico', invalid: 'Serie {set}: inserisci un carico valido da 0 a 1000 kg con massimo 2 decimali.', fix: 'Correggi i carichi non validi prima di salvare.', lockedHelp: 'Consulta lo storico durante l’attesa; il backend sbloccherà l’editor quando la condizione di disponibilità sarà soddisfatta.',
      stale_basis: 'Esiste una prestazione più recente. Ricarica lo storico; i valori inseriti verranno conservati.', version_conflict: 'Un’altra persona ha salvato questa prescrizione. Ricarica l’ultima versione; i tuoi valori verranno conservati.', prescription_blocked: 'La prescrizione è bloccata da un’esposizione precedente.', session_locked: 'La sessione è iniziata e la prescrizione è bloccata.',
      not_next_session: 'Questa non è più la prossima sessione.', set_count_mismatch: 'Il numero di serie del piano è cambiato. Ricarica lo storico.', invalid_load: 'Uno o più carichi non sono validi.', genericError: 'Impossibile salvare la prescrizione.', savedToast: 'Salvato · {exercise} · MC{mc}', noLoadStep: 'Il piano non definisce un incremento di carico; usa l’inserimento diretto.',
    },
    workout: {
      breadcrumb: 'Analisi / storico dell’unità di allenamento', title: '{workout}', subtitle: 'giorno {day} di ogni microciclo · {count} slot esercizio', help: 'Cella = carico massimo svolto · ripetizioni per serie. Apri una colonna o cella per consultare lo storico dell’esercizio.', occurrence: 'Occorrenza', volume: 'Carico-volume', comment: 'Commento allenamento', prescribed: 'prescritto', notPerformed: 'non svolto', empty: 'non ancora prescritto', skipped: 'saltato', locked: 'bloccato', loadError: 'Impossibile caricare lo storico dell’allenamento.',
    },
    timeline: {
      eyebrow: 'Storico microcicli · calendario', title: '{count} microcicli · {start} → {end}', microcycles: 'Microcicli', weeks: 'Settimane di calendario', axis: 'Asse temporale', helpMicrocycles: 'Una riga per microciclo, giorni del piano da sinistra a destra.', helpWeeks: 'Settimane da lunedì a domenica. I confini dei microcicli restano visibili.',
      attendance: 'Presenza', volume: 'Carico-vol.', note: '+ nota', notePlaceholder: 'Osservazione per MC{mc}…', saveNote: 'Salva nota', selectSession: 'Seleziona una sessione per i dettagli.', session: 'Sessione · MC{mc} · G{day}', prescription: 'Prescrizione: {state}',
      cancelSession: 'Annulla sessione…', reclassify: 'Riclassifica come annullata…', restore: 'Ripristina come pianificata', restorePast: 'Una sessione passata non può essere ripianificata.', reason: 'Motivo', reasonPlaceholder: 'es. vacanza', logEvent: 'Registra anche un evento nel diario', confirm: 'Conferma',
      journal: 'Storico dell’esecuzione', filters: { all: 'Tutti', plan: 'Modifiche al piano', phases: 'Fasi di carico', breaks: 'Pause', notes: 'Registri e note' }, eventType: 'Tipo di evento', date: 'Data', text: 'Testo', eventPlaceholder: 'es. Stallo da due settimane. Controllare il recupero.', log: 'Registra evento', noEvents: 'Nessun evento di questo tipo.', eventTypes: { observation: 'Osservazione', vacation: 'Vacanza', training_break: 'Pausa dall’allenamento' }, system: 'evento di sistema', user: 'registrato dall’utente', loadError: 'Impossibile caricare la cronologia.',
    },
    loads: {
      eyebrow: 'Analisi di tutti i carichi', title: 'Gli esercizi stanno progredendo insieme?', subtitle: 'Solo prestazioni finalizzate; sostituzioni, salti e sessioni mancate o annullate lasciano spazi vuoti.', traces: 'Storici esercizi · {shown} di {total} mostrati', primary: 'Esercizi principali', all: 'Tutti', none: 'Nessuno', metric: 'Metrica', scale: 'Scala', relative: '% della prima esposizione', kg: 'kg',
      top_set_load: 'Carico della serie massima', mean_set_load: 'Carico medio delle serie', volume_load: 'Carico-volume', chart: 'Grafico della progressione dei carichi', noSelection: 'Nessuno storico selezionato', noSelectionBody: 'Scegli gli storici a sinistra o mostrali tutti.', showAll: 'Mostra tutti', byUnit: 'Per unità di allenamento', loadError: 'Impossibile caricare l’analisi dei carichi.', gap: 'spazio: {reason}',
    },
    newRun: {
      back: 'Torna a Esecuzione', title: 'Nuova esecuzione', subtitle: 'Porta una revisione del piano nel calendario reale.', defaultName: '{plan} — esecuzione', plan: 'Piano di allenamento', revision: 'Revisione del piano', name: 'Nome esecuzione', start: 'Data di inizio', count: 'Microcicli', end: 'Fine (calcolata)',
      preview: 'Anteprima · cosa verrà creato', microcycles: 'microcicli', sessions: 'sessioni pianificate', workouts: 'storici allenamenti', exercises: 'storici esercizi', overlap: 'Questa esecuzione si sovrappone a {count} esecuzione/i esistente/i. Le sessioni saranno collocate nelle stesse date.', draftWarning: 'Le revisioni in bozza possono ancora cambiare.', revisionStatus: { released: 'Pubblicata', draft: 'Bozza', archived: 'Archiviata' },
      invalid: 'Scegli una revisione, una data di inizio valida e da 1 a 52 microcicli.', create: 'Crea esecuzione', creating: 'Creazione…', loadError: 'Impossibile caricare i piani.', previewError: 'Impossibile calcolare l’anteprima.', createError: 'Impossibile creare l’esecuzione.', noPlans: 'Crea un piano di allenamento prima di iniziare un’esecuzione.',
    },
  },
}
