export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      eyebrow: 'ATLANTE DEGLI ESERCIZI · CREAZIONE PROGRAMMI · ANALISI DELL’ALLENAMENTO', title: 'Comprendi il tuo allenamento e costruisci un programma sensato.', lead: 'Scopri cosa fa davvero un esercizio, trasformalo in parte di un programma settimanale e osserva gli effetti modellati sul corpo. Le risposte restano semplici — e puoi approfondire quando vuoi.', ctaPrimary: 'Apri l’Atlante', ctaSecondary: 'Vedi l’analisi del programma', proof: ['oltre 150 tecniche documentate', 'anatomia interattiva', 'dalla singola serie al microciclo'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANALISI',
    },
    audiences: {
      eyebrow: '01 · PER CHI', title: 'E tu — a che punto sei?', beginner: { tag: 'HO APPENA INIZIATO', title: 'Hai appena iniziato e tutto sembra inutilmente complicato?', body: 'Scopri quali muscoli lavorano, segui la tecnica passo dopo passo e capisci come serie, ripetizioni e RIR formano un programma.', link: 'Apri l’Atlante degli esercizi' }, advanced: { tag: 'VOGLIO APPROFONDIRE', title: 'Ti alleni da un po’ e vuoi capire davvero il tuo programma?', body: 'Confronta le varianti e analizza distribuzione dello stimolo, esposizione articolare e debito di recupero modellato fino alla singola serie.', link: 'Scopri come funziona l’Analisi' }, coach: { tag: 'PROGRAMMO PER ALTRI', title: 'Alleni atleti? Progetta e analizza i programmi in un unico sistema.', body: 'Costruisci microcicli con ruoli, sostituzioni, obiettivi, RIR e modelli di progressione espliciti, poi analizza il programma salvato.', link: 'Vai alla sezione per coach' },
    },
    loop: {
      s1: { title: 'Conosci l’esercizio', body: 'Tecnica, muscoli e intervalli di ripetizioni consigliati.' }, s2: { title: 'Organizza la tua split', body: 'PPL, full body o divisione personale — giorni, riposo, serie e RIR.' }, s3: { title: 'Esegui l’analisi', body: 'Distribuzione dello stimolo, recupero ed esposizione articolare — fino alla serie.' }, s4: { title: 'Esegui il programma e monitora i progressi', body: 'Esecuzione, storico delle serie e andamento della forza — la fase successiva.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ATLANTE DEGLI ESERCIZI', title: 'Non solo “panca piana”. Una tecnica precisa con presupposti precisi.', body: 'Ogni esercizio è descritto come variante definita: attrezzatura, assetto, traiettoria, ROM, criteri di cedimento tecnico e profilo di esposizione modellata.', etuRows: { title: 'Esposizione muscolare in numeri', body: 'cm² grezzi, quota della capacità stimata e intensità relativa.' }, etuAnatomy: { title: 'Distribuzione dello stimolo sul corpo', body: 'Mappa normalizzata sulla FCSA stimata.' }, technique: { title: 'Tecnica di questa variante', body: 'Assetto → esecuzione → quando fermarsi.' }, classification: { title: 'Classificazione della variante', body: 'Livello meccanico, fonte di resistenza, schema di esecuzione.' }, disclaimer: 'valori normalizzati su un atleta di riferimento comune · i tuoi valori possono differire',
    },
    planBuilder: {
      eyebrow: '03 · CREAZIONE PROGRAMMI', title: 'Costruisci un programma con gli elementi che contano davvero.', body: 'Definisci giorni di allenamento e riposo, ruolo di ogni esercizio, obiettivi, sostituzioni, serie, intervalli e RIR. Un programma è un microciclo ordinato, non una nota.', roles: { label: 'RUOLI', body: 'Progressione primaria · progressione secondaria · accumulo di volume · accessorio.' }, slot: { label: 'SLOT', body: 'Mantieni l’intento dello slot anche quando devi sostituire l’esercizio.' }, rest: { label: 'RIPOSO', body: 'Un giorno di riposo non è una casella vuota: definisce il tempo tra gli stimoli.' }, ctaPrimary: 'Apri il Creatore', ctaSecondary: 'Vedi l’analisi', panelDays: { left: 'MICROCICLO ORDINATO', right: '7 giorni · D01–D07' }, panelSlot: { left: 'SLOT · PRESCRIZIONE DELLE SERIE', right: 'ruolo · esercizio predefinito · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · ANALISI DEL PROGRAMMA', title: 'Un programma è più della somma delle sue serie.', body: 'Analizza una bozza salvata e scopri dove va lo stimolo, quali muscoli svolgono lavoro mirato o incidentale e come il modello porta il debito di recupero tra i giorni.', strip: { left: 'MICROCICLO · CONFINI DEI GIORNI', right: 'analisi della bozza salvata · aggiorna dopo le modifiche' }, recovery: { title: 'Recupero locale dopo l’allenamento', meta: 'hours_to_fresh' }, ranking: { title: 'Distribuzione settimanale dello stimolo', meta: 'ETU/cm²/7d' }, debts: { title: 'Debiti modellati più forti', body: 'Stato di prontezza al confine del giorno.' }, targeted: { title: 'Lavoro mirato e incidentale', body: 'Osserva ciò che il programma voleva allenare e il lavoro incidentale degli esercizi scelti.' }, provenance: { title: 'Ogni totale ha una fonte', body: 'Il risultato riconduce a giorno, esercizio e serie, con ripetizioni efficaci e parametri del modello.' }, disclaimer: 'risultato del modello · non è indolenzimento, tempo di guarigione o valutazione del rischio di infortunio',
    },
    muscleAtlas: {
      eyebrow: '05 · ATLANTE DEI MUSCOLI', title: 'Conosci il muscolo prima di contarne le serie.', body: 'Anatomia, funzione, architettura, quota stimata dei tipi di fibre ed esercizi con maggiore esposizione modellata — in un unico posto.', specs: [{ k: 'MORFOLOGIA', v: 'massa, volume' }, { k: 'ARCHITETTURA', v: 'pennazione, lunghezza fibre' }, { k: 'FIBRE', v: 'quota stimata' }, { k: 'FCSA', v: 'riferimento di capacità' }], note: 'La FCSA non è un conteggio delle fibre né un indice del potenziale ipertrofico. È una sezione stimata che trasmette forza, usata come denominatore comune.', link: 'Passa dal muscolo agli esercizi',
    },
    features: {
      eyebrow: '06 · ALTRE FUNZIONI', title: 'Il resto del sistema, in breve', technique: { title: 'Libreria tecnica', body: 'Assetto, movimento, ROM, indicazioni, cedimento tecnico, RIR ed errori comuni.' }, io: { title: 'Importazione / esportazione', body: 'Porta una struttura semplificata in un’analisi esterna e torna con un documento validato.' }, mobile: { title: 'Modalità allenamento mobile', body: 'Allenamento di oggi e tecnica a portata di mano durante la sessione.' }, progress: { title: 'Monitoraggio dei progressi', body: 'Storico dell’esecuzione, andamento della forza e modelli automatizzati di progressione — anche nel coaching.' }, knowledge: { title: 'Base di conoscenza', body: 'Gli articoli sui muscoli sono già disponibili; la base in sviluppo includerà articolazioni e collegherà Atlante e Analisi.' },
    },
    model: {
      eyebrow: '07 · SOTTO IL COFANO', title: 'Non misuriamo la biologia da uno schermo. Costruiamo un modello decisionale esplicito.', body: 'L’allenamento di forza avviene nell’incertezza. Agonez ordina le ipotesi, stima le conseguenze del programma e mostra l’origine del risultato. Dove manca una misurazione, parliamo di modello.', chain: ['esercizio', 'muscoli', 'stimolo meccanico', 'recupero', 'settimana del programma', 'progressione'], expandHint: 'ESPANDI PER VEDERE I DETTAGLI',
      etu: { title: 'ETU', summary: 'Quanto stimolo di tensione da una ripetizione efficace raggiunge un muscolo.', caveat: 'Non è EMG, percentuale di attivazione o misura dell’ipertrofia.' }, fcsa: { title: 'FCSA', summary: 'Un denominatore comune per confrontare muscoli grandi e piccoli sulla stessa scala.', caveat: 'È domanda meccanica, non fatica né conteggio delle fibre.' }, recovery: { title: 'MRU · JRU', summary: 'Debito muscolare e articolare modellato: cresce dopo una serie e cala tra le sessioni.', caveat: 'Strumento comparativo, non orologio biologico o valutazione del rischio.' }, reference: { title: 'Atleta di riferimento', summary: 'Le metriche dell’Atlante sono calibrate su una base descritta esplicitamente.', caveat: 'I tuoi valori possono differire sensibilmente.' }, limits: { title: 'Limiti del modello', summary: 'Ciò che il modello non vede — dichiarato apertamente.', note: 'versione, ipotesi e diagnostica restano visibili nell’applicazione' },
    },
    coaches: {
      eyebrow: '08 · PER I COACH', title: 'Segui più atleti senza rinunciare alla qualità del programma.', body: 'Un modello di microciclo, sostituzioni pronte e audit automatico invece di ricostruire un foglio per ogni cliente. Il tempo della ricopiatura resta al coaching.', reuse: { title: 'Un programma riutilizzabile', body: 'Un microciclo creato una volta — con ruoli, serie e RIR — è il punto di partenza per l’atleta successivo.' }, swap: { title: 'Una sostituzione in pochi secondi', body: 'Una macchina occupata o un’articolazione dolente non rompe il programma: lo slot mantiene il suo intento.' }, audit: { title: 'Audit invece del conteggio manuale', body: 'Distribuzione dello stimolo, lavoro incidentale e debito modellato si calcolano; tu giudichi il risultato.' }, argument: { title: 'Una spiegazione per l’atleta', body: 'Mostra perché il programma è fatto così. L’esportazione JSON porta con sé l’intera struttura.' }, cta: 'Crea il primo modello', note: 'Account atleta e storico di esecuzione sono pianificati — oggi lavori sui tuoi programmi.',
    },
    roadmap: {
      eyebrow: '09 · DOVE STIAMO ANDANDO', title: 'Oggi: progettazione e analisi. Poi: esecuzione e coaching nel tempo.', athlete: { title: 'Coaching degli atleti', body: 'La fase successiva collegherà programma e storico: carichi, ripetizioni, RIR, cambi di esercizio, deload e trend e1RM.', flow: ['Programma', 'Prescrizione', 'Esecuzione', 'Storico'] }, mobile: { title: 'Modalità allenamento mobile', body: 'Durante la sessione conta la prossima serie. La modalità prevista mostrerà l’allenamento di oggi e darà accesso rapido alla tecnica.', flow: ['Sessione di oggi', 'Registra esecuzione', 'Tecnica'] },
    },
    cta: { title: 'Inizia da un esercizio. Scopri quanto puoi approfondire.', body: 'Dalla comprensione del movimento alla decisione sul programma — risposte semplici in superficie, modelli espliciti sotto.', primary: 'Apri l’Atlante degli esercizi', secondary: 'Crea una bozza' }, footer: { navigation: 'Navigazione della pagina iniziale', links: { exerciseAtlas: 'Atlante degli esercizi', muscleAtlas: 'Atlante dei muscoli', planBuilder: 'Creazione programmi', analysis: 'Analisi', model: 'Modello' }, disclaimer: 'I valori Agonez sono stime modellate basate su ipotesi esplicite. Non sono misurazioni del tuo corpo né consigli medici.' }, badges: { comingSoon: 'PROSSIMAMENTE', experimental: 'MODELLO SPERIMENTALE' },
  },
}
