export default {
  execution: {
    shellStatus: 'UITVOERING · DESKTOP', nav: 'Uitvoering',
    tabs: { overview: 'Overzicht', analysis: 'Analyse', timeline: 'Tijdlijn', loads: 'Belastingen' },
    common: { kg: 'kg', rir: 'RIR', reps: 'herh.', today: 'Vandaag', close: 'Sluiten', save: 'Opslaan', cancel: 'Annuleren', edit: 'Bewerken', locked: 'Vergrendeld', loading: 'Uitvoeringsgegevens laden…', marker: 'MARKER.X', reserved: 'gereserveerd' },
    run: {
      eyebrow: 'Planuitvoering', from: 'Van {plan}', all: 'Alle uitvoeringen ({count})', new: 'Nieuwe planuitvoering', meta: '{start} → {end} · {count} × microcycli van {days} dagen',
      status: { scheduled: 'Gepland', active: 'Actief', cancelled: 'Geannuleerd', completed: 'Voltooid' }, emptyTitle: 'Nog geen planuitvoeringen', emptyBody: 'Een planuitvoering plaatst een trainingsplan in concrete kalendertijd.', loadError: 'De planuitvoering kon niet worden geladen', listError: 'De planuitvoeringen konden niet worden geladen.',
    },
    status: { scheduled: 'Gepland', in_progress: 'Bezig', completed: 'Voltooid', cancelled: 'Geannuleerd', missed: 'Gemist', today: 'Vandaag' }, completion: { as_prescribed: 'Zoals voorgeschreven', fallback: 'Alternatief' }, classification: { normal: 'Normaal', deload: 'Deload', reload: 'Reload' },
    blocked: {
      previous_exposure_in_progress: 'De vorige blootstelling is nog bezig.', previous_exposure_not_performed: 'De vorige voorgeschreven blootstelling is niet uitgevoerd.', session_started: 'Deze sessie is al begonnen.', no_future_session: 'Er is geen latere sessie in deze uitvoering.', run_not_active: 'Deze planuitvoering is niet actief.', unknown: 'Dit voorschrift kan nog niet worden bewerkt.',
    },
    overview: {
      where: 'Huidige positie', position: 'Microcyclus {current} van {total} · dag {day} van {days}', positionSub: 'uitvoeringsdag {runDay} van {runDays}, nog {left} dagen', thisMicrocycle: 'Deze microcyclus', sessions: 'Sessies in de kalender', analysisEyebrow: 'Analyse na training · volgende: MC{mc}', prescriptions: 'Voorschriften voor de volgende microcyclus',
      continue: 'Doorgaan met {workout}', waiting: 'Wachten', saved: '{saved} / {total} opgeslagen', latest: 'Laatste blootstelling · {workout} · {date}', comparison: 'Voorgeschreven vs. uitgevoerd', exercise: 'Oefening', prescribed: 'Voorgeschreven', performed: 'Uitgevoerd', note: 'Notitie', adherence: 'Naleving', didPlanHappen: 'Is het plan uitgevoerd?',
      journal: 'Logboek', latestEvents: 'Laatste gebeurtenissen', allEvents: 'Alle ({count})', observationPlaceholder: 'Observatie vastleggen…', log: 'Vastleggen', fullCalendar: 'Volledige kalender', readOnlyDraft: 'Lopende prestaties komen uit de mobiele app en zijn hier alleen-lezen.', noCurrentSessions: 'Er zijn geen sessies in de huidige microcyclus.', noExposure: 'Nog geen afgeronde blootstelling.', noEvents: 'Er zijn geen gebeurtenissen vastgelegd.',
    },
    analysis: {
      queue: 'MC{mc} voorschrijven', queueToggle: 'Wachtrij', progress: '{saved} van {total} opgeslagen · {locked} vergrendeld', workoutTrace: 'geschiedenis van de trainingseenheid', ready: 'Gereed', keyboard: 'J / K', notStarted: 'Niet gestart', unsaved: 'Niet-opgeslagen wijzigingen', saved: 'Opgeslagen', locked: 'Vergrendeld',
      confirmLeave: 'Je hebt niet-opgeslagen voorschriften. Analyse verlaten? De concepten blijven in deze browsersessie.', basedOn: 'Gebaseerd op MC{mc} · {date}', noSummary: 'Geen uitgevoerde blootstelling', loadError: 'De Analyse kon niet worden geladen.', traceEyebrow: '{workout} · positie {slot} · oefengeschiedenis', plan: "plan: {sets} × {min}–{max} {'@'}RIR {rir}",
      continuity: 'één geschiedenis vanaf MC{from} door planrevisies {revisions}', planNote: 'Plannotitie', previous: 'Vorige oefening', next: 'Volgende oefening', position: '{current} / {total}', loadStrip: 'Belasting per set · kg', prescribedLegend: 'voorgeschreven', performedLegend: 'uitgevoerd', nextLegend: 'volgende',
      exposure: 'Blootstelling', set: 'Set {set}', comments: 'Opmerkingen', prescription: 'Voorschrift', actual: 'Werkelijk', draft: 'Concept', setSkipped: 'set overgeslagen', notSynced: 'niet gesynchroniseerd', additional: '+EXTRA', missed: 'Gemist', cancelled: 'Geannuleerd', scheduled: 'Gepland', inProgress: 'Bezig',
      substituted: 'Vervangen door: {exercise}', exerciseSkipped: 'Oefening overgeslagen — geen sets uitgevoerd', noComment: 'Geen opmerking', revision: 'Planrevisie r{from} → r{to}', revisionBody: 'Geldig vanaf MC{mc} · {date}. {changes}. Dezelfde oefengeschiedenis loopt door.', compare: 'Revisies vergelijken',
      expand: 'Details van MC{mc} uitvouwen', collapse: 'Details van MC{mc} samenvouwen', session: 'Sessie', recorded: 'Vastgelegd', setComment: 'Setopmerking', performanceAfterSync: 'De prestatie verschijnt nadat de sessie vanaf mobiel is gesynchroniseerd.',
      flags: { substituted: 'Vervangen', skipped: 'Overgeslagen', additional_set: 'Extra set', reps_below_range: 'Herhalingen onder bereik', reps_at_floor: 'Herhalingen op ondergrens', top_of_range: 'Bovengrens van bereik', load_reduced: 'Belasting verlaagd', personal_record: 'Persoonlijk record' },
    },
    editor: {
      eyebrow: 'Volgend voorschrift', title: '{exercise} · MC{mc}', scheduled: '{workout} · {date} · bewerkbaar tot de sessie start', status: { clean: 'Niet gestart', dirty: 'Niet opgeslagen', saving: 'Opslaan…', saved: 'Opgeslagen', locked: 'Vergrendeld' },
      basis: 'Gebaseerd op prestatie in MC{mc} · {date} · afgerond', firstExposure: 'Eerste blootstelling — er is geen eerdere prestatie.', evidence: 'Herh. {reps} · belastingen {loads} kg · {top} op bovengrens · {floor} op ondergrens · {deeper} dieper dan doel-RIR',
      startFrom: 'Beginnen met', previousPrescription: 'Voorschrift MC{mc}', previousPerformance: 'Prestatie MC{mc}', allMinus: 'alle −{step}', allPlus: 'alle +{step}', suggestion: 'Suggestie', suggestionNone: 'Progressiemodel · geen', suggestionBody: 'Er is geen progressiemodel aan deze positie toegewezen.',
      fromPlan: 'Uit plan', load: 'Belasting kg', last: 'laatste {load}', comment: 'Setopmerking (optioneel)', selectSet: 'Set {set} selecteren', minus: 'Set {set}: {step} kg aftrekken', plus: 'Set {set}: {step} kg toevoegen', apply: 'Toepassen', selected: 'op {count} geselecteerde',
      prescriptionComment: 'Voorschriftopmerking · alleen voor deze blootstelling', commentPlaceholder: 'Waar moet de sporter zich de volgende keer op richten?', planOwned: 'Aantal sets, herhalingsbereik en RIR komen uit planrevisie r{revision}. Wijzig ze in de Planmaker voor toekomstige microcycli.',
      discard: 'Verwerpen', save: 'Opslaan', saveNext: 'Opslaan en volgende oefening', reload: 'Geschiedenis herladen', invalid: 'Set {set}: voer een geldige belasting van 0 tot 1000 kg in met maximaal 2 decimalen.', fix: 'Corrigeer ongeldige belastingen voor het opslaan.', lockedHelp: 'Bekijk de geschiedenis tijdens het wachten; de backend ontgrendelt de editor zodra aan de gereedheidsvoorwaarde is voldaan.',
      stale_basis: 'Er is een nieuwere prestatie. Herlaad de geschiedenis; je ingevoerde waarden blijven behouden.', version_conflict: 'Iemand anders heeft dit voorschrift opgeslagen. Herlaad de nieuwste versie; je waarden blijven behouden.', prescription_blocked: 'Het voorschrift wordt geblokkeerd door een eerdere blootstelling.', session_locked: 'De sessie is gestart en het voorschrift is vergrendeld.',
      not_next_session: 'Dit is niet langer de volgende sessie.', set_count_mismatch: 'Het aantal sets in het plan is gewijzigd. Herlaad de geschiedenis.', invalid_load: 'Een of meer belastingen zijn ongeldig.', genericError: 'Het voorschrift kon niet worden opgeslagen.', savedToast: 'Opgeslagen · {exercise} · MC{mc}', noLoadStep: 'Het plan definieert geen belastingstap; gebruik directe invoer.',
    },
    workout: {
      breadcrumb: 'Analyse / geschiedenis van de trainingseenheid', title: '{workout}', subtitle: 'dag {day} van elke microcyclus · {count} oefenposities', help: 'Cel = hoogste uitgevoerde belasting · herhalingen per set. Open een kolom of cel om de oefengeschiedenis te bekijken.', occurrence: 'Voorkomen', volume: 'Volumebelasting', comment: 'Trainingsopmerking', prescribed: 'voorgeschreven', notPerformed: 'niet uitgevoerd', empty: 'nog niet voorgeschreven', skipped: 'overgeslagen', locked: 'vergrendeld', loadError: 'De trainingsgeschiedenis kon niet worden geladen.',
    },
    timeline: {
      eyebrow: 'Microcyclusgeschiedenis · kalender', title: '{count} microcycli · {start} → {end}', microcycles: 'Microcycli', weeks: 'Kalenderweken', axis: 'Tijdas', helpMicrocycles: 'Eén rij per microcyclus, plandagen van links naar rechts.', helpWeeks: 'Kalenderweken van maandag tot zondag. Microcyclusgrenzen blijven zichtbaar.',
      attendance: 'Aanwezigheid', volume: 'Vol.-bel.', note: '+ notitie', notePlaceholder: 'Observatie voor MC{mc}…', saveNote: 'Notitie opslaan', selectSession: 'Selecteer een sessie voor details.', session: 'Sessie · MC{mc} · D{day}', prescription: 'Voorschrift: {state}',
      cancelSession: 'Sessie annuleren…', reclassify: 'Als geannuleerd classificeren…', restore: 'Herstellen als gepland', restorePast: 'Een eerdere sessie kan niet opnieuw worden gepland.', reason: 'Reden', reasonPlaceholder: 'bijv. vakantie', logEvent: 'Ook als logboekgebeurtenis vastleggen', confirm: 'Bevestigen',
      journal: 'Geschiedenis van de planuitvoering', filters: { all: 'Alle', plan: 'Planwijzigingen', phases: 'Belastingsfasen', breaks: 'Pauzes', notes: 'Registraties en notities' }, eventType: 'Gebeurtenistype', date: 'Datum', text: 'Tekst', eventPlaceholder: 'bijv. Twee weken plateau. Herstel controleren.', log: 'Gebeurtenis vastleggen', noEvents: 'Geen gebeurtenissen van dit type.', eventTypes: { observation: 'Observatie', vacation: 'Vakantie', training_break: 'Trainingspauze' }, system: 'systeemgebeurtenis', user: 'door gebruiker vastgelegd', loadError: 'De tijdlijn kon niet worden geladen.',
    },
    loads: {
      eyebrow: 'Analyse van alle belastingen', title: 'Gaan de oefeningen samen vooruit?', subtitle: 'Alleen afgeronde prestaties; vervangingen, overgeslagen oefeningen en gemiste of geannuleerde sessies laten gaten.', traces: 'Oefengeschiedenissen · {shown} van {total} getoond', primary: 'Hoofdoefeningen', all: 'Alle', none: 'Geen', metric: 'Metriek', scale: 'Schaal', relative: '% van eerste blootstelling', kg: 'kg',
      top_set_load: 'Belasting zwaarste set', mean_set_load: 'Gemiddelde setbelasting', volume_load: 'Volumebelasting', chart: 'Grafiek van belastingsprogressie', noSelection: 'Geen oefengeschiedenissen geselecteerd', noSelectionBody: 'Selecteer links geschiedenissen of toon ze allemaal.', showAll: 'Alles tonen', byUnit: 'Per trainingseenheid', loadError: 'De belastingsanalyse kon niet worden geladen.', gap: 'gat: {reason}',
    },
    newRun: {
      back: 'Terug naar Uitvoering', title: 'Nieuwe planuitvoering', subtitle: 'Plaats een planrevisie in concrete kalendertijd.', defaultName: '{plan} — uitvoering', plan: 'Trainingsplan', revision: 'Planrevisie', name: 'Naam van uitvoering', start: 'Startdatum', count: 'Microcycli', end: 'Einde (berekend)',
      preview: 'Voorbeeld · wat wordt gemaakt', microcycles: 'microcycli', sessions: 'geplande sessies', workouts: 'trainingsgeschiedenissen', exercises: 'oefengeschiedenissen', overlap: 'Deze uitvoering overlapt {count} bestaande uitvoering(en). De sessies komen op dezelfde datums.', draftWarning: 'Conceptrevisies kunnen nog veranderen.', revisionStatus: { released: 'Uitgebracht', draft: 'Concept', archived: 'Gearchiveerd' },
      invalid: 'Kies een planrevisie, geldige startdatum en 1–52 microcycli.', create: 'Uitvoering maken', creating: 'Maken…', loadError: 'De plannen konden niet worden geladen.', previewError: 'Het voorbeeld kon niet worden berekend.', createError: 'De uitvoering kon niet worden gemaakt.', noPlans: 'Maak een trainingsplan voordat je een uitvoering start.',
    },
  },
}
