export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      eyebrow: 'OEFENINGENATLAS · PROGRAMMABOUWER · TRAININGSANALYSE', title: 'Begrijp je training en bouw een programma dat klopt.', lead: 'Zie wat een oefening werkelijk doet, maak er een weekprogramma van en bekijk de gemodelleerde effecten op het lichaam. De antwoorden blijven eenvoudig — en je kunt dieper gaan wanneer je wilt.', ctaPrimary: 'Open de Atlas', ctaSecondary: 'Bekijk de programmaanalyse', proof: ['meer dan 150 beschreven technieken', 'interactieve anatomie', 'van één set tot een microcyclus'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANALYSE',
    },
    audiences: {
      eyebrow: '01 · VOOR WIE', title: 'En jij — waar sta je nu?', beginner: { tag: 'IK BEGIN NET', title: 'Net begonnen met trainen en lijkt alles onnodig ingewikkeld?', body: 'Zie welke spieren werken, volg de techniek stap voor stap en begrijp hoe sets, herhalingen en RIR samen een programma vormen.', link: 'Open de Oefeningenatlas' }, advanced: { tag: 'IK WIL DIEPER GAAN', title: 'Train je al een tijd en wil je je programma echt begrijpen?', body: 'Vergelijk varianten en analyseer prikkelverdeling, gewrichtsblootstelling en gemodelleerde herstelschuld tot op setniveau.', link: 'Bekijk hoe Analyse werkt' }, coach: { tag: 'IK PROGRAMMEER VOOR ANDEREN', title: 'Coach je sporters? Ontwerp en analyseer programma’s in één systeem.', body: 'Bouw microcycli met duidelijke rollen, alternatieven, doelen, RIR en progressiemodellen en analyseer daarna het opgeslagen programma.', link: 'Bekijk het coachgedeelte' },
    },
    loop: {
      s1: { title: 'Leer de oefening kennen', body: 'Techniek, spieren en aanbevolen herhalingsbereiken.' }, s2: { title: 'Leg je split vast', body: 'PPL, full body of eigen indeling — dagen, rust, sets en RIR.' }, s3: { title: 'Voer de analyse uit', body: 'Prikkelverdeling, herstel en gewrichtsblootstelling — tot op setniveau.' }, s4: { title: 'Voer het programma uit en volg vooruitgang', body: 'Uitvoering, setgeschiedenis en krachttrend — de volgende ontwikkelfase.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · OEFENINGENATLAS', title: 'Niet zomaar “bankdrukken”. Een specifieke techniek met specifieke aannames.', body: 'Elke oefening is een gedefinieerde variant: materiaal, opstelling, bewegingsbaan, bewegingsbereik, criteria voor technisch falen en een eigen gemodelleerd blootstellingsprofiel.', etuRows: { title: 'Spierblootstelling in cijfers', body: 'Ruwe cm², aandeel van geschatte capaciteit en relatieve intensiteit.' }, etuAnatomy: { title: 'Prikkelverdeling op het lichaam', body: 'Heatmap genormaliseerd naar geschatte FCSA.' }, technique: { title: 'Techniek voor deze variant', body: 'Opstelling → uitvoering → wanneer stoppen.' }, classification: { title: 'Classificatie van de variant', body: 'Mechanisch niveau, weerstandsbron en uitvoeringspatroon.' }, disclaimer: 'waarden genormaliseerd naar één referentiesporter · jouw waarden kunnen afwijken',
    },
    planBuilder: {
      eyebrow: '03 · PROGRAMMABOUWER', title: 'Bouw een programma uit onderdelen die er echt toe doen.', body: 'Definieer trainings- en rustdagen, rollen, doelen, alternatieven, sets, herhalingsbereiken en RIR. Een programma is een geordende microcyclus, geen notitie.', roles: { label: 'ROLLEN', body: 'Primaire progressie · secundaire progressie · volumeaccumulatie · accessoire.' }, slot: { label: 'SLOT', body: 'Behoud de bedoeling van de slot, ook als de oefening moet worden vervangen.' }, rest: { label: 'RUST', body: 'Een rustdag is geen lege cel — hij bepaalt de tijd tussen prikkels.' }, ctaPrimary: 'Open de Programmabouwer', ctaSecondary: 'Bekijk de analyse', panelDays: { left: 'GEORDENDE MICROCYCUS', right: '7 dagen · D01–D07' }, panelSlot: { left: 'SLOT · SETVOORSCHRIFT', right: 'rol · standaardoefening · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · PROGRAMMAANALYSE', title: 'Een programma is meer dan de som van de sets.', body: 'Analyseer een opgeslagen concept en zie waar de prikkel terechtkomt, welke spieren doelgericht of incidenteel werken en hoe het model herstelschuld tussen dagen meeneemt.', strip: { left: 'MICROCYCUS · DAGGRENZEN', right: 'analyse van opgeslagen concept · vernieuw na wijzigingen' }, recovery: { title: 'Lokaal herstel na training', meta: 'hours_to_fresh' }, ranking: { title: 'Wekelijkse prikkelverdeling', meta: 'ETU/cm²/7d' }, debts: { title: 'Sterkste gemodelleerde schulden', body: 'Gereedheid op de daggrens.' }, targeted: { title: 'Doelgericht en incidenteel werk', body: 'Zie niet alleen wat het programma wilde trainen, maar ook het nevenwerk door de gekozen oefeningen.' }, provenance: { title: 'Elk totaal heeft een bron', body: 'Het resultaat leidt terug naar dag, oefening en set, met effectieve herhalingen en modelparameters.' }, disclaimer: 'modeluitkomst · geen spierpijn, genezingstijd of beoordeling van blessurerisico',
    },
    muscleAtlas: {
      eyebrow: '05 · SPIERATLAS', title: 'Leer de spier kennen voordat je sets gaat tellen.', body: 'Anatomie, functie, architectuur, geschatte vezelverdeling en oefeningen met de hoogste gemodelleerde blootstelling — op één plek.', specs: [{ k: 'MORFOLOGIE', v: 'massa, volume' }, { k: 'ARCHITECTUUR', v: 'pennatie, vezellengte' }, { k: 'VEZELS', v: 'geschat aandeel' }, { k: 'FCSA', v: 'capaciteitsreferentie' }], note: 'FCSA is geen vezeltelling of maat voor hypertrofiepotentieel. Het is een geschatte krachtgeleidende doorsnede die als gemeenschappelijke noemer dient.', link: 'Ga van spier naar oefeningen',
    },
    features: {
      eyebrow: '06 · MEER MOGELIJKHEDEN', title: 'De rest van het systeem, in het kort', technique: { title: 'Techniekbibliotheek', body: 'Opstelling, beweging, ROM, aanwijzingen, technisch falen, RIR en veelgemaakte fouten.' }, io: { title: 'Programma importeren / exporteren', body: 'Neem een vereenvoudigde structuur mee naar externe analyse en importeer een gevalideerd document terug.' }, mobile: { title: 'Mobiele trainingsmodus', body: 'De training van vandaag en techniek bij de hand tijdens de sessie.' }, progress: { title: 'Voortgang volgen', body: 'Uitvoeringsgeschiedenis, krachttrends en geautomatiseerde progressiemodellen — ook voor coaching.' }, knowledge: { title: 'Kennisbank', body: 'Spierartikelen werken al; de groeiende kennisbank zal ook gewrichten behandelen en Atlas en Analyse verbinden.' },
    },
    model: {
      eyebrow: '07 · ONDER DE MOTORKAP', title: 'We meten biologie niet via een scherm. We bouwen een expliciet beslismodel.', body: 'Krachttraining gebeurt onder onzekerheid. Agonez ordent aannames, schat de gevolgen van een programma en toont de oorsprong van het resultaat. Waar geen meting is, noemen we het een model.', chain: ['oefening', 'spieren', 'mechanische prikkel', 'herstel', 'programmaweek', 'progressie'], expandHint: 'OPEN VOOR DE DETAILS',
      etu: { title: 'ETU', summary: 'Hoeveel spanningsprikkel van één effectieve herhaling een spier bereikt.', caveat: 'Dit is geen EMG, activeringspercentage of meting van hypertrofie.' }, fcsa: { title: 'FCSA', summary: 'Een gemeenschappelijke noemer om grote en kleine spieren op één schaal te vergelijken.', caveat: 'Dit is mechanische vraag, geen vermoeidheid en geen vezeltelling.' }, recovery: { title: 'MRU · JRU', summary: 'Gemodelleerde spier- en gewrichtsschuld: stijgt na een set en daalt tussen sessies.', caveat: 'Een vergelijkingsinstrument, geen biologische klok of blessurerisicobeoordeling.' }, reference: { title: 'Referentiesporter', summary: 'Atlasmetingen zijn gekalibreerd op één expliciet beschreven basis.', caveat: 'Jouw eigen waarden kunnen aanzienlijk verschillen.' }, limits: { title: 'Grenzen van het model', summary: 'Wat het model niet ziet — openlijk beschreven, niet verborgen.', note: 'modelversie, aannames en diagnostiek blijven zichtbaar in de app' },
    },
    coaches: {
      eyebrow: '08 · VOOR COACHES', title: 'Begeleid meer sporters zonder programmakwaliteit in te leveren.', body: 'Een microcyclussjabloon, klaarliggende alternatieven en automatische controle vervangen een nieuw spreadsheet per klant. De kopieertijd blijft over voor coaching.', reuse: { title: 'Een herbruikbaar programma', body: 'Een microcyclus die eenmaal is gebouwd — met rollen, sets en RIR — is het startpunt voor de volgende sporter.' }, swap: { title: 'Een vervanging in seconden', body: 'Een bezet toestel of gevoelig gewricht breekt het programma niet — de slot behoudt zijn bedoeling.' }, audit: { title: 'Controle in plaats van handmatig tellen', body: 'Prikkelverdeling, incidenteel werk en gemodelleerde schuld worden berekend; jij beoordeelt de uitkomst.' }, argument: { title: 'Een uitleg voor je sporter', body: 'Laat zien waarom het programma zo is opgebouwd. De JSON-export neemt de hele structuur mee.' }, cta: 'Bouw je eerste sjabloon', note: 'Sportersaccounts en uitvoeringsgeschiedenis zijn gepland — vandaag werk je met je eigen programma’s.',
    },
    roadmap: {
      eyebrow: '09 · WAAR HET HEENGAAT', title: 'Vandaag: ontwerpen en analyseren. Daarna: uitvoeren en begeleiden in de tijd.', athlete: { title: 'Sportersbegeleiding', body: 'De volgende stap verbindt het programma met uitvoering: gewichten, herhalingen, RIR, oefenwissels, deloads en e1RM-trends.', flow: ['Programma', 'Voorschrift', 'Uitvoering', 'Geschiedenis'] }, mobile: { title: 'Mobiele trainingsmodus', body: 'Tijdens de training telt de volgende set. De geplande modus toont de sessie van vandaag en snelle toegang tot techniek.', flow: ['Sessie van vandaag', 'Uitvoering loggen', 'Techniek'] },
    },
    cta: { title: 'Begin met één oefening. Ontdek hoe diep je kunt gaan.', body: 'Van beweging begrijpen tot een programmabeslissing — eenvoudige antwoorden aan de oppervlakte, expliciete modellen eronder.', primary: 'Open de Oefeningenatlas', secondary: 'Bouw een conceptprogramma' }, footer: { navigation: 'Navigatie op de startpagina', links: { exerciseAtlas: 'Oefeningenatlas', muscleAtlas: 'Spieratlas', planBuilder: 'Programmabouwer', analysis: 'Analyse', model: 'Model' }, disclaimer: 'Agonez-waarden zijn gemodelleerde schattingen op basis van expliciete aannames. Ze zijn geen metingen van je lichaam en geen medisch advies.' }, badges: { comingSoon: 'BINNENKORT', experimental: 'EXPERIMENTEEL MODEL' },
  },
}
