export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      betaBadge: 'BESLOTEN BÈTA · NAJAAR 2026',
      waitlist: { label: 'E-mailadres', placeholder: "jij{'@'}voorbeeld.nl", button: 'Op de wachtlijst', note: 'Geen spam. Eén e-mail zodra je uitnodiging klaarstaat.', emailSubject: 'Besloten bèta van Agonez — wachtlijstverzoek', emailBody: 'Hallo,\n\nik wil graag op de wachtlijst voor de besloten bèta van Agonez.\n\nMijn e-mailadres: {email}\n\nHiervoor wil ik Agonez gebruiken:\n' },
      eyebrow: 'OEFENINGENATLAS · PROGRAMMABOUWER · PROGRESSIEBEGELEIDING', title: 'Begrijp je training en bouw een programma dat klopt.', lead: 'Zie welke spieren je oefening werkelijk aanspreekt. Bouw met die oefeningen een weekprogramma en zie wat dat programma met je lichaam doet.', ctaPrimary: 'Open de Atlas', ctaSecondary: 'Bekijk de programmaanalyse', proof: ['meer dan 150 oefeningen', 'interactieve anatomie', 'van één herhaling tot een microcyclus'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANALYSE',
    },
    audiences: {
      eyebrow: '01 · VOOR WIE', title: 'En jij — waar sta je nu?', beginner: { tag: 'IK BEGIN NET', title: 'Begin je met trainen en lijkt alles onnodig ingewikkeld?', body: 'Zie welke spieren werken en volg de techniek stap voor stap. Probeer de Programmabouwer.', link: 'Open de Oefeningenatlas' }, advanced: { tag: 'IK WIL DIEPER GAAN', title: 'Train je al een tijd en wil je je programma echt begrijpen?', body: 'Vergelijk varianten en analyseer prikkelverdeling, gewrichtsblootstelling en gemodelleerde herstelschuld. Controleer of je programma optimaal is.', link: 'Bekijk hoe Analyse werkt' }, coach: { tag: 'IK PROGRAMMEER VOOR ANDEREN', title: 'Coach je sporters? Wil je een professionele tool?', body: 'Bouw microcycli met duidelijke rollen, alternatieven, doelen, RIR en progressiemodellen. Volg daarna de voortgang van je sporters.', link: 'Bekijk het coachgedeelte' },
    },
    loop: {
      s1: { title: 'Leer de oefeningen kennen', body: 'Techniek, spieren en aanbevolen herhalingsbereiken.' }, s2: { title: 'Leg je split vast', body: 'PPL, full body of eigen indeling — sets, RIR, belasting en progressiemodellen.' }, s3: { title: 'Voer de analyse uit', body: 'Prikkelverdeling en spier- en gewrichtsherstel — tot op setniveau.' }, s4: { title: 'Voer het programma uit en volg vooruitgang', body: 'Uitvoering, setgeschiedenis en krachttrend — de volgende fase van jouw ontwikkeling.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · OEFENINGENATLAS', title: 'Niet zomaar “bankdrukken”. Een specifieke techniek met specifieke aannames.', body: 'Elke oefening is een gedefinieerde variant: materiaal, opstelling, bewegingsbaan, bewegingsbereik, criteria voor technisch falen en een eigen gemodelleerd blootstellingsprofiel.', etuRows: { title: 'Spierblootstelling in cijfers', body: 'Ruwe cm², aandeel van geschatte capaciteit en relatieve intensiteit.' }, etuAnatomy: { title: 'Prikkelverdeling op het lichaam', body: 'Heatmap genormaliseerd naar geschatte FCSA.' }, technique: { title: 'Techniek voor deze variant', body: 'Opstelling → uitvoering → wanneer stoppen.' }, classification: { title: 'Classificatie van de variant', body: 'Mechanisch niveau, weerstandsbron en uitvoeringspatroon.' }, disclaimer: 'waarden genormaliseerd naar één referentiesporter · jouw waarden kunnen afwijken',
    },
    planBuilder: {
      eyebrow: '03 · PROGRAMMABOUWER', title: 'Bouw een programma uit onderdelen die er echt toe doen.', body: 'Definieer trainings- en rustdagen, rollen, doelen, alternatieven, sets, herhalingsbereiken en RIR. Een programma is een geordende microcyclus, geen notitie.', roles: { label: 'ROLLEN', body: 'Primaire progressie · secundaire progressie · volumeaccumulatie · accessoire.' }, slot: { label: 'SLOT', body: 'Behoud de bedoeling van de slot, ook als de oefening moet worden vervangen.' }, rest: { label: 'RUST', body: 'Een rustdag is geen lege cel — hij bepaalt de tijd tussen prikkels.' }, ctaPrimary: 'Open de Programmabouwer', ctaSecondary: 'Bekijk de analyse', panelDays: { left: 'GEORDENDE MICROCYCUS', right: '7 dagen · D01–D07' }, panelSlot: { left: 'SLOT · SETVOORSCHRIFT', right: 'rol · standaardoefening · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · PROGRAMMAANALYSE', title: 'Een programma is meer dan de som van de sets.', body: 'Analyseer een opgeslagen concept en zie waar de prikkel terechtkomt, welke spieren doelgericht of incidenteel werken en of ze tussen de dagen kunnen herstellen.', strip: { left: 'MICROCYCUS · DAGGRENZEN', right: 'analyse van opgeslagen concept · vernieuw na wijzigingen' }, recovery: { title: 'Herstel na training', meta: 'hours_to_fresh' }, ranking: { title: 'Wekelijks aantal sets per spier', meta: 'ETU/cm²/7d' }, debts: { title: 'Status van spierherstel', body: 'Wanneer is de spier weer fris?' }, targeted: { title: 'Doelgericht en incidenteel werk', body: 'Zie niet alleen wat het programma wilde trainen, maar ook het nevenwerk door de gekozen oefeningen.' }, provenance: { title: 'Elk totaal heeft een bron', body: 'Het resultaat leidt terug naar dag, oefening en set, met effectieve herhalingen en modelparameters.' }, disclaimer: 'modeluitkomst · geen spierpijn, genezingstijd of beoordeling van blessurerisico',
    },
    muscleAtlas: {
      eyebrow: '05 · SPIERATLAS', title: 'Leer de spier kennen voordat je sets gaat tellen.', body: 'Anatomie, functie, architectuur, geschatte vezelverdeling en de beste oefeningen — op één plek.', specs: [{ k: 'MORFOLOGIE', v: 'massa, volume' }, { k: 'ARCHITECTUUR', v: 'pennatie, vezellengte' }, { k: 'VEZELS', v: 'geschat aandeel type I en II' }, { k: 'FCSA', v: 'krachteenheid' }], note: 'FCSA is geen vezeltelling of maat voor hypertrofiepotentieel. Het is een geschatte krachtgeleidende doorsnede die als gemeenschappelijke noemer dient.', link: 'Ga van spier naar oefeningen',
    },
    features: {
      eyebrow: '06 · MEER MOGELIJKHEDEN', title: 'De rest van het systeem, in het kort', technique: { title: 'Techniekbibliotheek', body: 'Opstelling, beweging, ROM, aanwijzingen, technisch falen, RIR en veelgemaakte fouten.' }, io: { title: 'Programma importeren / exporteren', body: 'Download of upload een programma eenvoudig als tekst. Met AI importeer je je eigen programma’s gemakkelijk.' }, mobile: { title: 'Mobiel trainen', body: 'Open de app tijdens de training en laat je door de sessie begeleiden.' }, progress: { title: 'Voortgang volgen', body: 'Uitvoeringsgeschiedenis, krachttrends en geautomatiseerde progressiemodellen — ook voor coaching.' }, knowledge: { title: 'Kennisbank', body: 'Een wetenschappelijk onderbouwde kennisbank in blogvorm. De Atlas zal ook bewegingen en gewrichten omvatten.' },
    },
    model: {
      eyebrow: '07 · ONDER DE MOTORKAP', title: 'We meten biologie niet via een scherm. We bouwen een expliciet beslismodel.', body: 'Krachttraining gebeurt onder onzekerheid. Agonez ordent aannames, schat de gevolgen van een programma en toont de oorsprong van het resultaat. Waar geen meting is, noemen we het een model.', chain: ['oefening', 'spieren', 'mechanische prikkel', 'herstel', 'programmaweek', 'progressie'], expandHint: 'OPEN VOOR DE DETAILS',
      etu: { title: 'ETU', summary: 'Hoeveel spanningsprikkel van één effectieve herhaling een spier bereikt.', body: 'Een oefening ‘traint’ niet simpelweg de borst. Ze heeft een profiel: een deel van de spanning gaat naar de primaire bewegers en een deel naar de stabilisatoren. ETU (Effective Tension Unit) schat die verdeling voor één effectieve herhaling, zodat twee varianten van dezelfde beweging numeriek kunnen worden vergeleken.', caveat: 'Dit is geen EMG, activeringspercentage of meting van hypertrofie.' }, fcsa: { title: 'FCSA', summary: 'Een gemeenschappelijke noemer om grote en kleine spieren op één schaal te vergelijken.', caveat: 'Dit is mechanische vraag, geen vermoeidheid en geen vezeltelling.' }, recovery: { title: 'MRU · JRU', summary: 'Gemodelleerde spier- en gewrichtsschuld: stijgt na een set en daalt tussen sessies.', body: 'Elke set voegt lokale schuld toe aan de spieren, en meer naarmate de set dichter bij technisch falen komt. De schuld daalt met de tijd, dus de afstand tussen prikkels voor dezelfde spier hoort bij het programma. JRU doet hetzelfde voor de gewrichten.', caveat: 'Een vergelijkingsinstrument, geen biologische klok of blessurerisicobeoordeling.' }, reference: { title: 'Referentiesporter', summary: 'Atlasmetingen zijn gekalibreerd op één expliciet beschreven basis.', caveat: 'Jouw uitgangswaarde kan aanzienlijk verschillen, terwijl de onderlinge verhoudingen slechts minimaal zouden moeten afwijken.' }, limits: { title: 'Grenzen van het model', summary: 'Wat het model niet ziet — openlijk beschreven, niet verborgen.', note: 'modelversie, aannames en diagnostiek blijven zichtbaar in de app' },
    },
    coaches: {
      eyebrow: '08 · VOOR COACHES', title: 'Begeleid meer sporters zonder in te leveren op de kwaliteit van je begeleiding.', body: 'Een microcyclussjabloon, klaarliggende alternatieven en automatische controle vervangen een nieuw spreadsheet per klant. De kopieertijd blijft over voor coaching.', reuse: { title: 'Een herbruikbaar programma', body: 'Een microcyclus die eenmaal is gebouwd — met rollen, sets en RIR — is het startpunt voor de volgende sporter.' }, swap: { title: 'Een vervanging in seconden', body: 'Een bezet toestel of gevoelig gewricht breekt het programma niet — de slot behoudt zijn bedoeling.' }, audit: { title: 'Controle in plaats van handmatig tellen', body: 'Prikkelverdeling, incidenteel werk, gemodelleerde schuld tussen dagen en belastingsprogressie worden automatisch berekend; jij beoordeelt de uitkomst.' }, argument: { title: 'Eenvoudig delen', body: 'Stuur de sporter een link en die heeft een kant-en-klaar programma om in de app te openen.' }, adaptation: { title: 'Elke sporter is anders', body: 'Zie je dat een sporter niet herstelt van het programma? Na verloop van tijd leer je diegene beter kennen en kun je de modelparameters specifiek afstemmen.' }, cta: 'Bouw je eerste sjabloon', note: 'Sportersaccounts en uitvoeringsgeschiedenis zijn gepland — vandaag werk je met je eigen programma’s.',
    },
    roadmap: {
      eyebrow: '09 · WAAR HET HEENGAAT', title: 'Vandaag: ontwerpen en analyseren. Morgen: uitvoeren en begeleiden in de tijd.', athlete: { title: 'Sportersbegeleiding', body: 'De volgende stap verbindt het programma met uitvoering: gewichten, herhalingen, RIR, oefenwissels, deloads en e1RM-trends.', flow: ['Programma', 'Voorschrift', 'Uitvoering', 'Geschiedenis'] }, mobile: { title: 'Mobiel trainen', body: 'Tijdens de training telt de volgende set. De geplande modus toont de sessie van vandaag en snelle toegang tot techniek.', flow: ['Sessie van vandaag', 'Uitvoering loggen', 'Techniek'] },
    },
    cta: { eyebrow: 'EEN OPEN UITNODIGING', title: 'Help de mensheid uitmuntendheid in training te bereiken.', body: 'Agonez bevindt zich in een vroege fase. We bouwen het op het snijvlak van training, wetenschap, engineering en product.', bodySecondary: 'Werk je in een van deze domeinen en wil je meebouwen aan een hulpmiddel dat steunt op echte problemen, vakkennis en kritische feedback, dan zoeken we jou.', rolesLabel: 'Mensen en perspectieven die we graag ontmoeten', roles: ['Personal trainers', 'Sporters', 'Biomechanici', 'Sportwetenschap', 'Product & engineering', 'UX / onderzoek', 'Marketing', 'Eerste partners & early adopters'], action: 'Laten we praten', note: 'Open voor gerichte gesprekken en afgebakende samenwerkingen. Opent je e-mailapp.', emailSubject: 'Samen Agonez bouwen', emailBody: 'Hallo,\n\nik praat graag over een bijdrage aan Agonez.\n\nMijn achtergrond of idee:\n' }, footer: { navigation: 'Navigatie op de startpagina', links: { exerciseAtlas: 'Oefeningenatlas', muscleAtlas: 'Spieratlas', planBuilder: 'Programmabouwer', analysis: 'Analyse', model: 'Model' }, disclaimer: 'Agonez-waarden zijn gemodelleerde schattingen op basis van expliciete aannames. Ze zijn geen metingen van je lichaam en geen medisch advies.' }, badges: { comingSoon: 'BINNENKORT', experimental: 'EXPERIMENTEEL MODEL' },
  },
}
