export default {
  execution: {
    shellStatus: 'EJECUCIÓN · ESCRITORIO', nav: 'Ejecución',
    tabs: { overview: 'Resumen', analysis: 'Análisis', timeline: 'Cronología', loads: 'Cargas' },
    common: { kg: 'kg', rir: 'RIR', reps: 'reps.', today: 'Hoy', close: 'Cerrar', save: 'Guardar', cancel: 'Cancelar', edit: 'Editar', locked: 'Bloqueado', loading: 'Cargando datos de ejecución…', marker: 'MARKER.X', reserved: 'reservado' },
    run: {
      eyebrow: 'Ejecución del plan', from: 'Desde {plan}', all: 'Todas las ejecuciones ({count})', new: 'Nueva ejecución', meta: '{start} → {end} · {count} × microciclos de {days} días',
      status: { scheduled: 'Programada', active: 'Activa', cancelled: 'Cancelada', completed: 'Completada' }, emptyTitle: 'Aún no hay ejecuciones', emptyBody: 'Una ejecución sitúa un plan de entrenamiento en un calendario real.', loadError: 'No se pudo cargar la ejecución', listError: 'No se pudieron cargar las ejecuciones.',
    },
    status: { scheduled: 'Programada', in_progress: 'En curso', completed: 'Completada', cancelled: 'Cancelada', missed: 'Perdida', today: 'Hoy' }, completion: { as_prescribed: 'Según lo prescrito', fallback: 'Alternativa' }, classification: { normal: 'Normal', deload: 'Descarga', reload: 'Recarga' },
    blocked: {
      previous_exposure_in_progress: 'La exposición anterior sigue en curso.', previous_exposure_not_performed: 'La exposición prescrita anterior no se ha realizado.', session_started: 'Esta sesión ya ha comenzado.', no_future_session: 'No hay una sesión posterior en esta ejecución.', run_not_active: 'Esta ejecución no está activa.', unknown: 'Esta prescripción aún no se puede editar.',
    },
    overview: {
      where: 'Dónde estás', position: 'Microciclo {current} de {total} · día {day} de {days}', positionSub: 'día {runDay} de {runDays}, quedan {left} días', thisMicrocycle: 'Este microciclo', sessions: 'Sesiones del calendario', analysisEyebrow: 'Análisis postentrenamiento · siguiente: MC{mc}', prescriptions: 'Prescripciones para el siguiente microciclo',
      continue: 'Continuar {workout}', waiting: 'En espera', saved: '{saved} / {total} guardadas', latest: 'Última exposición · {workout} · {date}', comparison: 'Prescrito frente a realizado', exercise: 'Ejercicio', prescribed: 'Prescrito', performed: 'Realizado', note: 'Nota', adherence: 'Cumplimiento', didPlanHappen: '¿Se cumplió el plan?',
      journal: 'Diario', latestEvents: 'Últimos eventos', allEvents: 'Todos ({count})', observationPlaceholder: 'Registrar una observación…', log: 'Registrar', fullCalendar: 'Calendario completo', readOnlyDraft: 'El rendimiento en curso llega desde la aplicación móvil y aquí es de solo lectura.', noCurrentSessions: 'No hay sesiones en el microciclo actual.', noExposure: 'Aún no hay una exposición finalizada.', noEvents: 'No se ha registrado ningún evento.',
    },
    analysis: {
      queue: 'Prescribir MC{mc}', queueToggle: 'Cola', progress: '{saved} de {total} guardadas · {locked} bloqueadas', workoutTrace: 'historial de la unidad de entrenamiento', ready: 'Listo', keyboard: 'J / K', notStarted: 'Sin empezar', unsaved: 'Cambios sin guardar', saved: 'Guardado', locked: 'Bloqueado',
      confirmLeave: 'Hay prescripciones sin guardar. ¿Salir del Análisis? Los borradores permanecerán en esta sesión del navegador.', basedOn: 'Basado en MC{mc} · {date}', noSummary: 'Sin exposición realizada', loadError: 'No se pudo cargar el Análisis.', traceEyebrow: '{workout} · posición {slot} · historial del ejercicio', plan: "plan: {sets} × {min}–{max} {'@'}RIR {rir}",
      continuity: 'un historial desde MC{from} a través de las revisiones {revisions}', planNote: 'Nota del plan', previous: 'Ejercicio anterior', next: 'Ejercicio siguiente', position: '{current} / {total}', loadStrip: 'Carga por serie · kg', prescribedLegend: 'prescrito', performedLegend: 'realizado', nextLegend: 'siguiente',
      exposure: 'Exposición', set: 'Serie {set}', comments: 'Comentarios', prescription: 'Prescripción', actual: 'Real', draft: 'Borrador', setSkipped: 'serie omitida', notSynced: 'sin sincronizar', additional: '+ADIC.', missed: 'Perdida', cancelled: 'Cancelada', scheduled: 'Programada', inProgress: 'En curso',
      substituted: 'Sustituido por: {exercise}', exerciseSkipped: 'Ejercicio omitido — no se realizó ninguna serie', noComment: 'Sin comentario', revision: 'Revisión del plan r{from} → r{to}', revisionBody: 'Vigente desde MC{mc} · {date}. {changes}. Continúa el mismo historial del ejercicio.', compare: 'Comparar revisiones',
      expand: 'Ampliar detalles de MC{mc}', collapse: 'Contraer detalles de MC{mc}', session: 'Sesión', recorded: 'Registrado', setComment: 'Comentario de la serie', performanceAfterSync: 'El rendimiento aparece después de sincronizar la sesión desde el móvil.',
      flags: { substituted: 'Sustituido', skipped: 'Omitido', additional_set: 'Serie adicional', reps_below_range: 'Repeticiones bajo el rango', reps_at_floor: 'Repeticiones en el límite inferior', top_of_range: 'Límite superior del rango', load_reduced: 'Carga reducida', personal_record: 'Récord personal' },
    },
    editor: {
      eyebrow: 'Siguiente prescripción', title: '{exercise} · MC{mc}', scheduled: '{workout} · {date} · editable hasta que empiece la sesión', status: { clean: 'Sin empezar', dirty: 'Sin guardar', saving: 'Guardando…', saved: 'Guardado', locked: 'Bloqueado' },
      basis: 'Basado en el rendimiento de MC{mc} · {date} · finalizado', firstExposure: 'Primera exposición — no hay rendimiento anterior.', evidence: 'Reps. {reps} · cargas {loads} kg · {top} en el límite superior · {floor} en el inferior · {deeper} más profundo que el RIR objetivo',
      startFrom: 'Empezar desde', previousPrescription: 'Prescripción MC{mc}', previousPerformance: 'Rendimiento MC{mc}', allMinus: 'todas −{step}', allPlus: 'todas +{step}', suggestion: 'Sugerencia', suggestionNone: 'Modelo de progresión · ninguno', suggestionBody: 'No hay un modelo de progresión asignado a esta posición.',
      fromPlan: 'Del plan', load: 'Carga kg', last: 'última {load}', comment: 'Comentario de la serie (opcional)', selectSet: 'Seleccionar serie {set}', minus: 'Serie {set}: restar {step} kg', plus: 'Serie {set}: sumar {step} kg', apply: 'Aplicar', selected: 'a {count} seleccionadas',
      prescriptionComment: 'Comentario de prescripción · solo para esta exposición', commentPlaceholder: '¿En qué debe centrarse el atleta la próxima vez?', planOwned: 'El número de series, el rango de repeticiones y el RIR proceden de la revisión r{revision}. Cámbialos en el Creador de planes para futuros microciclos.',
      discard: 'Descartar', save: 'Guardar', saveNext: 'Guardar y siguiente ejercicio', reload: 'Recargar historial', invalid: 'Serie {set}: introduce una carga válida entre 0 y 1000 kg con un máximo de 2 decimales.', fix: 'Corrige las cargas no válidas antes de guardar.', lockedHelp: 'Revisa el historial mientras esperas; el backend desbloqueará el editor cuando se cumpla la condición de disponibilidad.',
      stale_basis: 'Existe un rendimiento más reciente. Recarga el historial; se conservarán los valores escritos.', version_conflict: 'Otra persona ha guardado esta prescripción. Recarga la última versión; se conservarán tus valores.', prescription_blocked: 'La prescripción está bloqueada por una exposición anterior.', session_locked: 'La sesión ha comenzado y su prescripción está bloqueada.',
      not_next_session: 'Esta ya no es la siguiente sesión.', set_count_mismatch: 'El número de series del plan ha cambiado. Recarga el historial.', invalid_load: 'Una o más cargas no son válidas.', genericError: 'No se pudo guardar la prescripción.', savedToast: 'Guardado · {exercise} · MC{mc}', noLoadStep: 'El plan no define un incremento de carga; usa la entrada directa.',
    },
    workout: {
      breadcrumb: 'Análisis / historial de la unidad de entrenamiento', title: '{workout}', subtitle: 'día {day} de cada microciclo · {count} posiciones de ejercicio', help: 'Celda = carga máxima realizada · repeticiones por serie. Abre una columna o celda para consultar el historial del ejercicio.', occurrence: 'Ocurrencia', volume: 'Carga-volumen', comment: 'Comentario del entrenamiento', prescribed: 'prescrito', notPerformed: 'no realizado', empty: 'aún no prescrito', skipped: 'omitido', locked: 'bloqueado', loadError: 'No se pudo cargar el historial del entrenamiento.',
    },
    timeline: {
      eyebrow: 'Historial de microciclos · calendario', title: '{count} microciclos · {start} → {end}', microcycles: 'Microciclos', weeks: 'Semanas naturales', axis: 'Eje temporal', helpMicrocycles: 'Una fila por microciclo, días del plan de izquierda a derecha.', helpWeeks: 'Semanas de lunes a domingo. Los límites de los microciclos permanecen visibles.',
      attendance: 'Asistencia', volume: 'Carga-vol.', note: '+ nota', notePlaceholder: 'Observación para MC{mc}…', saveNote: 'Guardar nota', selectSession: 'Selecciona una sesión para ver los detalles.', session: 'Sesión · MC{mc} · D{day}', prescription: 'Prescripción: {state}',
      cancelSession: 'Cancelar sesión…', reclassify: 'Reclasificar como cancelada…', restore: 'Restaurar como programada', restorePast: 'No se puede volver a programar una sesión pasada.', reason: 'Motivo', reasonPlaceholder: 'p. ej., vacaciones', logEvent: 'Registrar también un evento en el diario', confirm: 'Confirmar',
      journal: 'Historial de la ejecución', filters: { all: 'Todos', plan: 'Cambios del plan', phases: 'Fases de carga', breaks: 'Pausas', notes: 'Registros y notas' }, eventType: 'Tipo de evento', date: 'Fecha', text: 'Texto', eventPlaceholder: 'p. ej., Estancamiento de dos semanas. Revisar la recuperación.', log: 'Registrar evento', noEvents: 'No hay eventos de este tipo.', eventTypes: { observation: 'Observación', vacation: 'Vacaciones', training_break: 'Pausa de entrenamiento' }, system: 'evento del sistema', user: 'registrado por el usuario', loadError: 'No se pudo cargar la cronología.',
    },
    loads: {
      eyebrow: 'Análisis de todas las cargas', title: '¿Progresan los levantamientos conjuntamente?', subtitle: 'Solo rendimientos finalizados; sustituciones, omisiones y sesiones perdidas o canceladas dejan huecos.', traces: 'Historiales de ejercicios · {shown} de {total} mostrados', primary: 'Levantamientos principales', all: 'Todos', none: 'Ninguno', metric: 'Métrica', scale: 'Escala', relative: '% de la primera exposición', kg: 'kg',
      top_set_load: 'Carga de la serie superior', mean_set_load: 'Carga media de las series', volume_load: 'Carga-volumen', chart: 'Gráfico de progresión de cargas', noSelection: 'No hay historiales seleccionados', noSelectionBody: 'Selecciona historiales a la izquierda o muéstralos todos.', showAll: 'Mostrar todos', byUnit: 'Por unidad de entrenamiento', loadError: 'No se pudo cargar el análisis de cargas.', gap: 'hueco: {reason}',
    },
    newRun: {
      back: 'Volver a Ejecución', title: 'Nueva ejecución', subtitle: 'Lleva una revisión del plan a un calendario real.', defaultName: '{plan} — ejecución', plan: 'Plan de entrenamiento', revision: 'Revisión del plan', name: 'Nombre de la ejecución', start: 'Fecha de inicio', count: 'Microciclos', end: 'Fin (calculado)',
      preview: 'Vista previa · qué se creará', microcycles: 'microciclos', sessions: 'sesiones programadas', workouts: 'historiales de entrenamiento', exercises: 'historiales de ejercicios', overlap: 'Esta ejecución se solapa con {count} ejecución(es) existente(s). Las sesiones se colocarán en las mismas fechas.', draftWarning: 'Las revisiones en borrador aún pueden cambiar.', revisionStatus: { released: 'Publicada', draft: 'Borrador', archived: 'Archivada' },
      invalid: 'Elige una revisión, una fecha de inicio válida y entre 1 y 52 microciclos.', create: 'Crear ejecución', creating: 'Creando…', loadError: 'No se pudieron cargar los planes.', previewError: 'No se pudo calcular la vista previa.', createError: 'No se pudo crear la ejecución.', noPlans: 'Crea un plan de entrenamiento antes de iniciar una ejecución.',
    },
  },
}
