export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      eyebrow: 'ATLAS DE EJERCICIOS · CREADOR DE PLANES · SEGUIMIENTO DE LA PROGRESIÓN',
      title: 'Comprende tu entrenamiento y crea un plan con sentido.',
      lead: 'Descubre qué músculos trabaja realmente tu ejercicio. Organiza esos ejercicios en un plan semanal y observa lo que ese plan hace en tu cuerpo.',
      ctaPrimary: 'Abrir el Atlas', ctaSecondary: 'Ver el análisis del plan', proof: ['más de 150 ejercicios', 'anatomía interactiva', 'de una repetición al microciclo'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANÁLISIS',
    },
    audiences: {
      eyebrow: '01 · PARA QUIÉN', title: '¿Y tú, en qué punto estás?',
      beginner: { tag: 'ACABO DE EMPEZAR', title: '¿Estás empezando y todo parece innecesariamente complicado?', body: 'Mira qué músculos trabajan y sigue la técnica paso a paso. Prueba el Creador de planes.', link: 'Abrir el Atlas de ejercicios' },
      advanced: { tag: 'QUIERO PROFUNDIZAR', title: '¿Llevas tiempo entrenando y quieres comprender de verdad tu plan?', body: 'Compara variantes y analiza la distribución del estímulo, la exposición articular y la deuda de recuperación modelada. Comprueba si tu plan es óptimo.', link: 'Ver cómo funciona el Análisis' },
      coach: { tag: 'PROGRAMO PARA OTROS', title: '¿Entrenas a deportistas? ¿Quieres una herramienta profesional?', body: 'Crea microciclos con roles, sustituciones, objetivos, RIR y modelos de progresión explícitos. Después controla el progreso de tus deportistas.', link: 'Ver la sección para entrenadores' },
    },
    loop: {
      s1: { title: 'Conoce los ejercicios', body: 'Técnica, músculos y rangos de repeticiones recomendados.' }, s2: { title: 'Organiza tu rutina', body: 'PPL, cuerpo completo o tu propia división — series, RIR, carga y modelos de progresión.' }, s3: { title: 'Ejecuta el análisis', body: 'Distribución del estímulo y recuperación muscular y articular — hasta cada serie.' }, s4: { title: 'Ejecuta el plan y sigue el progreso', body: 'Ejecución, historial de series y tendencia de fuerza — la siguiente etapa de tu desarrollo.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ATLAS DE EJERCICIOS', title: 'No solo «press de banca». Una técnica concreta con supuestos concretos.', body: 'Cada ejercicio se describe como una variante definida: equipo, colocación, trayectoria, rango, criterios de fallo técnico y su propio perfil de exposición modelada.',
      etuRows: { title: 'Exposición muscular en cifras', body: 'cm² brutos, proporción de la capacidad estimada e intensidad relativa.' }, etuAnatomy: { title: 'Distribución del estímulo en el cuerpo', body: 'Mapa de calor normalizado según la FCSA estimada.' }, technique: { title: 'Técnica de esta variante', body: 'Colocación → ejecución → cuándo parar.' }, classification: { title: 'Clasificación de la variante', body: 'Nivel mecánico, fuente de resistencia y patrón de ejecución.' }, disclaimer: 'valores normalizados para un deportista de referencia común · tus resultados pueden variar',
    },
    planBuilder: {
      eyebrow: '03 · CREADOR DE PLANES', title: 'Construye un plan con las piezas que importan.', body: 'Define días de entrenamiento y descanso, el papel de cada ejercicio, objetivos, sustituciones, series, rangos de repeticiones y RIR. Un plan es un microciclo ordenado, no una nota.',
      roles: { label: 'ROLES', body: 'Progresión principal · progresión secundaria · acumulación de volumen · accesorio.' }, slot: { label: 'SLOT', body: 'Conserva la intención del slot aunque haya que cambiar el ejercicio.' }, rest: { label: 'DESCANSO', body: 'Un día de descanso no es una celda vacía: define el tiempo entre estímulos.' }, ctaPrimary: 'Abrir el Creador', ctaSecondary: 'Ver el análisis', panelDays: { left: 'MICROCICLO ORDENADO', right: '7 días · D01–D07' }, panelSlot: { left: 'SLOT · PRESCRIPCIÓN DE SERIES', right: 'rol · ejercicio predeterminado · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · ANÁLISIS DEL PLAN', title: 'Un plan es más que la suma de sus series.', body: 'Analiza un borrador guardado y descubre dónde llega el estímulo, qué músculos realizan trabajo intencional o incidental y si pueden recuperarse entre días.',
      strip: { left: 'MICROCICLO · LÍMITES DE DÍA', right: 'análisis del borrador guardado · actualizar tras cambios' }, recovery: { title: 'Recuperación tras entrenar', meta: 'hours_to_fresh' }, ranking: { title: 'Número semanal de series por músculo', meta: 'ETU/cm²/7d' }, debts: { title: 'Estado de recuperación muscular', body: '¿Cuándo volverá a estar fresco el músculo?' }, targeted: { title: 'Trabajo intencional e incidental', body: 'Observa lo que el plan pretendía entrenar y el trabajo incidental de los ejercicios elegidos.' }, provenance: { title: 'Cada total tiene un origen', body: 'El resultado conduce al día, ejercicio y serie, junto con las repeticiones efectivas y los parámetros del modelo.' }, disclaimer: 'resultado del modelo · no es dolor muscular, tiempo de curación ni evaluación del riesgo de lesión',
    },
    muscleAtlas: {
      eyebrow: '05 · ATLAS DE MÚSCULOS', title: 'Conoce el músculo antes de contar sus series.', body: 'Anatomía, función, arquitectura, proporción estimada de tipos de fibras y los mejores ejercicios — en un mismo lugar.', specs: [{ k: 'MORFOLOGÍA', v: 'masa, volumen' }, { k: 'ARQUITECTURA', v: 'pennación, longitud de fibras' }, { k: 'FIBRAS', v: 'proporción estimada de tipos I y II' }, { k: 'FCSA', v: 'unidad de fuerza' }], note: 'La FCSA no es un recuento de fibras ni un indicador del potencial hipertrófico. Es una sección transmisora de fuerza estimada que se usa como denominador común.', link: 'Ir del músculo a los ejercicios',
    },
    features: {
      eyebrow: '06 · MÁS FUNCIONES', title: 'El resto del sistema, en breve', technique: { title: 'Biblioteca de técnica', body: 'Colocación, movimiento, ROM, indicaciones, fallo técnico, RIR y errores frecuentes.' }, io: { title: 'Importar / exportar planes', body: 'Descarga o sube fácilmente un plan como texto. Con ayuda de la IA, importar tus planes es sencillo.' }, mobile: { title: 'Modo de entrenamiento móvil', body: 'Abre la aplicación durante el entrenamiento y deja que te guíe por la sesión.' }, progress: { title: 'Seguimiento del progreso', body: 'Historial de ejecución, tendencias de fuerza y modelos automatizados de progresión — también para deportistas.' }, knowledge: { title: 'Base de conocimiento', body: 'Una base de conocimiento en forma de blog con fundamento científico. El Atlas también incluirá movimientos y articulaciones.' },
    },
    model: {
      eyebrow: '07 · BAJO EL CAPÓ', title: 'No medimos la biología desde una pantalla. Construimos un modelo de decisión explícito.', body: 'El entrenamiento de fuerza ocurre bajo incertidumbre. Agonez ordena supuestos, estima las consecuencias del plan y muestra de dónde sale el resultado. Donde no hay medición, hablamos de modelo.', chain: ['ejercicio', 'músculos', 'estímulo mecánico', 'recuperación', 'semana del plan', 'progresión'], expandHint: 'DESPLIEGA PARA VER LOS DETALLES',
      etu: { title: 'ETU', summary: 'Cuánto estímulo de tensión de una repetición efectiva llega a cada músculo.', body: 'Un ejercicio no se limita a «entrenar el pecho». Tiene un perfil: parte de la tensión va a los motores principales y parte a los estabilizadores. ETU (Effective Tension Unit) estima esa distribución para una repetición efectiva, de modo que dos variantes del mismo movimiento puedan compararse numéricamente.', caveat: 'No es EMG, porcentaje de activación ni una medida de hipertrofia.' }, fcsa: { title: 'FCSA', summary: 'Un denominador común para comparar un músculo grande y uno pequeño en la misma escala.', caveat: 'Es demanda mecánica, no fatiga ni un recuento de fibras.' }, recovery: { title: 'MRU · JRU', summary: 'Deuda muscular y articular modelada: aumenta tras una serie y baja entre sesiones.', body: 'Cada serie añade deuda local a los músculos, y más cuanto más cerca está del fallo técnico. La deuda disminuye con el tiempo, por lo que espaciar los estímulos del mismo músculo forma parte del plan. JRU hace lo mismo para las articulaciones.', caveat: 'Herramienta comparativa, no reloj biológico ni evaluación del riesgo de lesión.' }, reference: { title: 'Deportista de referencia', summary: 'Las métricas del Atlas se calibran con una base descrita explícitamente.', caveat: 'Tu punto de partida puede diferir considerablemente, mientras que las relaciones relativas deberían variar muy poco.' }, limits: { title: 'Límites del modelo', summary: 'Lo que el modelo no ve — escrito claramente, no oculto.', note: 'la versión, los supuestos y los diagnósticos siguen visibles en la aplicación' },
    },
    coaches: {
      eyebrow: '08 · PARA ENTRENADORES', title: 'Atiende a más deportistas sin renunciar a la calidad del seguimiento.', body: 'Una plantilla de microciclo, sustituciones preparadas y una auditoría automática en lugar de rehacer una hoja de cálculo por cliente. El tiempo de copiar series queda para entrenar de verdad.', reuse: { title: 'Un plan reutilizable', body: 'Un microciclo creado una vez — con roles, series y RIR — es el punto de partida del siguiente deportista.' }, swap: { title: 'Una sustitución en segundos', body: 'Una máquina ocupada o una articulación molesta no rompe el plan: el slot conserva su intención.' }, audit: { title: 'Auditoría en vez de recuento manual', body: 'La distribución del estímulo, el trabajo incidental, la deuda modelada entre días y la progresión de la carga se calculan automáticamente; tú juzgas el resultado.' }, argument: { title: 'Compartir fácilmente', body: 'Envía un enlace al deportista y tendrá un plan listo para abrir en la aplicación.' }, adaptation: { title: 'Cada deportista es diferente', body: '¿Ves que un deportista no se recupera con el plan? Con el tiempo lo conoces mejor y puedes adaptar los parámetros del modelo específicamente a sus necesidades.' }, cta: 'Crear tu primera plantilla', note: 'Las cuentas de deportistas y el historial de ejecución están previstos; hoy trabajas en tus propios planes.',
    },
    roadmap: {
      eyebrow: '09 · HACIA DÓNDE VAMOS', title: 'Hoy: diseño y análisis. Mañana: ejecución y seguimiento en el tiempo.', athlete: { title: 'Seguimiento de deportistas', body: 'La siguiente etapa conectará el plan con el historial de ejecución: cargas, repeticiones, RIR, cambios de ejercicio, deloads y tendencias de e1RM.', flow: ['Plan', 'Prescripción', 'Ejecución', 'Historial'] }, mobile: { title: 'Modo de entrenamiento móvil', body: 'Durante una sesión importa la siguiente serie. El modo previsto mostrará el entrenamiento del día y dará acceso rápido a la técnica.', flow: ['Sesión de hoy', 'Registrar ejecución', 'Técnica'] },
    },
    cta: { title: 'Empieza con un ejercicio. Descubre hasta dónde puedes llegar.', body: 'Desde la anatomía del movimiento hasta las decisiones del plan — respuestas sencillas en la superficie, modelos explícitos debajo.', primary: 'Abrir el Atlas de ejercicios', secondary: 'Crear un borrador' },
    footer: { navigation: 'Navegación de la página de inicio', links: { exerciseAtlas: 'Atlas de ejercicios', muscleAtlas: 'Atlas de músculos', planBuilder: 'Creador de planes', analysis: 'Análisis', model: 'Modelo' }, disclaimer: 'Los valores de Agonez son estimaciones modeladas basadas en supuestos explícitos. No son mediciones de tu cuerpo ni consejo médico.' },
    badges: { comingSoon: 'PRÓXIMAMENTE', experimental: 'MODELO EXPERIMENTAL' },
  },
}
