export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      eyebrow: 'ATLAS DE EJERCICIOS · CREADOR DE PLANES · ANÁLISIS DEL ENTRENAMIENTO',
      title: 'Comprende tu entrenamiento y crea un plan con sentido.',
      lead: 'Descubre qué hace realmente un ejercicio, conviértelo en parte de un plan semanal y observa sus efectos modelados sobre el cuerpo. Las respuestas siguen siendo sencillas — y puedes profundizar cuando quieras.',
      ctaPrimary: 'Abrir el Atlas', ctaSecondary: 'Ver el análisis del plan', proof: ['más de 150 técnicas documentadas', 'anatomía interactiva', 'de una serie al microciclo'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANÁLISIS',
    },
    audiences: {
      eyebrow: '01 · PARA QUIÉN', title: '¿Y tú, en qué punto estás?',
      beginner: { tag: 'ACABO DE EMPEZAR', title: '¿Acabas de empezar y todo parece innecesariamente complicado?', body: 'Mira qué músculos trabajan, sigue la técnica paso a paso y entiende cómo series, repeticiones y RIR forman un plan.', link: 'Abrir el Atlas de ejercicios' },
      advanced: { tag: 'QUIERO PROFUNDIZAR', title: '¿Llevas tiempo entrenando y quieres comprender de verdad tu plan?', body: 'Compara variantes, analiza la distribución del estímulo, la exposición articular y la deuda de recuperación modelada, hasta cada serie.', link: 'Ver cómo funciona el Análisis' },
      coach: { tag: 'PROGRAMO PARA OTROS', title: '¿Entrenas a deportistas? Diseña y analiza planes en un mismo sistema.', body: 'Crea microciclos con roles, sustituciones, objetivos, RIR y modelos de progresión explícitos. Después analiza el plan guardado.', link: 'Ver la sección para entrenadores' },
    },
    loop: {
      s1: { title: 'Conoce el ejercicio', body: 'Técnica, músculos y rangos de repeticiones recomendados.' }, s2: { title: 'Organiza tu rutina', body: 'PPL, cuerpo completo o tu propia división — días, descanso, series y RIR.' }, s3: { title: 'Ejecuta el análisis', body: 'Distribución del estímulo, recuperación y exposición articular — hasta la serie.' }, s4: { title: 'Ejecuta el plan y sigue el progreso', body: 'Ejecución, historial de series y tendencia de fuerza — la siguiente etapa.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ATLAS DE EJERCICIOS', title: 'No solo «press de banca». Una técnica concreta con supuestos concretos.', body: 'Cada ejercicio se describe como una variante definida: equipo, colocación, trayectoria, rango, criterios de fallo técnico y su propio perfil de exposición modelada.',
      etuRows: { title: 'Exposición muscular en cifras', body: 'cm² brutos, proporción de la capacidad estimada e intensidad relativa.' }, etuAnatomy: { title: 'Distribución del estímulo en el cuerpo', body: 'Mapa de calor normalizado según la FCSA estimada.' }, technique: { title: 'Técnica de esta variante', body: 'Colocación → ejecución → cuándo parar.' }, classification: { title: 'Clasificación de la variante', body: 'Nivel mecánico, fuente de resistencia y patrón de ejecución.' }, disclaimer: 'valores normalizados para un deportista de referencia común · tus resultados pueden variar',
    },
    planBuilder: {
      eyebrow: '03 · CREADOR DE PLANES', title: 'Construye un plan con las piezas que importan.', body: 'Define días de entrenamiento y descanso, el papel de cada ejercicio, objetivos, sustituciones, series, rangos de repeticiones y RIR. Un plan es un microciclo ordenado, no una nota.',
      roles: { label: 'ROLES', body: 'Progresión principal · progresión secundaria · acumulación de volumen · accesorio.' }, slot: { label: 'SLOT', body: 'Conserva la intención del slot aunque haya que cambiar el ejercicio.' }, rest: { label: 'DESCANSO', body: 'Un día de descanso no es una celda vacía: define el tiempo entre estímulos.' }, ctaPrimary: 'Abrir el Creador', ctaSecondary: 'Ver el análisis', panelDays: { left: 'MICROCICLO ORDENADO', right: '7 días · D01–D07' }, panelSlot: { left: 'SLOT · PRESCRIPCIÓN DE SERIES', right: 'rol · ejercicio predeterminado · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · ANÁLISIS DEL PLAN', title: 'Un plan es más que la suma de sus series.', body: 'Analiza un borrador guardado y descubre dónde llega el estímulo, qué músculos realizan trabajo intencional o incidental y cómo el modelo mantiene la deuda de recuperación entre días.',
      strip: { left: 'MICROCICLO · LÍMITES DE DÍA', right: 'análisis del borrador guardado · actualizar tras cambios' }, recovery: { title: 'Recuperación local tras entrenar', meta: 'hours_to_fresh' }, ranking: { title: 'Distribución semanal del estímulo', meta: 'ETU/cm²/7d' }, debts: { title: 'Mayores deudas modeladas', body: 'Estado de preparación en el límite del día.' }, targeted: { title: 'Trabajo intencional e incidental', body: 'Observa lo que el plan pretendía entrenar y el trabajo incidental de los ejercicios elegidos.' }, provenance: { title: 'Cada total tiene un origen', body: 'El resultado conduce al día, ejercicio y serie, junto con las repeticiones efectivas y los parámetros del modelo.' }, disclaimer: 'resultado del modelo · no es dolor muscular, tiempo de curación ni evaluación del riesgo de lesión',
    },
    muscleAtlas: {
      eyebrow: '05 · ATLAS DE MÚSCULOS', title: 'Conoce el músculo antes de contar sus series.', body: 'Anatomía, función, arquitectura, proporción estimada de tipos de fibras y ejercicios con mayor exposición modelada — en un mismo lugar.', specs: [{ k: 'MORFOLOGÍA', v: 'masa, volumen' }, { k: 'ARQUITECTURA', v: 'pennación, longitud de fibras' }, { k: 'FIBRAS', v: 'proporción estimada' }, { k: 'FCSA', v: 'referencia de capacidad' }], note: 'La FCSA no es un recuento de fibras ni un indicador del potencial hipertrófico. Es una sección transmisora de fuerza estimada que se usa como denominador común.', link: 'Ir del músculo a los ejercicios',
    },
    features: {
      eyebrow: '06 · MÁS FUNCIONES', title: 'El resto del sistema, en breve', technique: { title: 'Biblioteca de técnica', body: 'Colocación, movimiento, ROM, indicaciones, fallo técnico, RIR y errores frecuentes.' }, io: { title: 'Importar / exportar planes', body: 'Lleva una estructura simplificada a un análisis externo y vuelve con un documento validado.' }, mobile: { title: 'Modo de entrenamiento móvil', body: 'La sesión de hoy y la técnica a mano, sin volver al ordenador.' }, progress: { title: 'Seguimiento del progreso', body: 'Historial de ejecución, tendencias de fuerza y modelos automatizados de progresión — también para deportistas.' }, knowledge: { title: 'Base de conocimiento', body: 'Los artículos musculares ya funcionan; la base en desarrollo incluirá articulaciones y se conectará al Atlas y al Análisis.' },
    },
    model: {
      eyebrow: '07 · BAJO EL CAPÓ', title: 'No medimos la biología desde una pantalla. Construimos un modelo de decisión explícito.', body: 'El entrenamiento de fuerza ocurre bajo incertidumbre. Agonez ordena supuestos, estima las consecuencias del plan y muestra de dónde sale el resultado. Donde no hay medición, hablamos de modelo.', chain: ['ejercicio', 'músculos', 'estímulo mecánico', 'recuperación', 'semana del plan', 'progresión'], expandHint: 'DESPLIEGA PARA VER LOS DETALLES',
      etu: { title: 'ETU', summary: 'Cuánto estímulo de tensión de una repetición efectiva llega a cada músculo.', caveat: 'No es EMG, porcentaje de activación ni una medida de hipertrofia.' }, fcsa: { title: 'FCSA', summary: 'Un denominador común para comparar un músculo grande y uno pequeño en la misma escala.', caveat: 'Es demanda mecánica, no fatiga ni un recuento de fibras.' }, recovery: { title: 'MRU · JRU', summary: 'Deuda muscular y articular modelada: aumenta tras una serie y baja entre sesiones.', caveat: 'Herramienta comparativa, no reloj biológico ni evaluación del riesgo de lesión.' }, reference: { title: 'Deportista de referencia', summary: 'Las métricas del Atlas se calibran con una base descrita explícitamente.', caveat: 'Tus propios valores pueden diferir considerablemente.' }, limits: { title: 'Límites del modelo', summary: 'Lo que el modelo no ve — escrito claramente, no oculto.', note: 'la versión, los supuestos y los diagnósticos siguen visibles en la aplicación' },
    },
    coaches: {
      eyebrow: '08 · PARA ENTRENADORES', title: 'Atiende a más deportistas sin renunciar a la calidad del plan.', body: 'Una plantilla de microciclo, sustituciones preparadas y una auditoría automática en lugar de rehacer una hoja de cálculo por cliente. El tiempo de copiar series queda para entrenar de verdad.', reuse: { title: 'Un plan reutilizable', body: 'Un microciclo creado una vez — con roles, series y RIR — es el punto de partida del siguiente deportista.' }, swap: { title: 'Una sustitución en segundos', body: 'Una máquina ocupada o una articulación molesta no rompe el plan: el slot conserva su intención.' }, audit: { title: 'Auditoría en vez de recuento manual', body: 'La distribución del estímulo, el trabajo incidental y la deuda modelada se calculan; tú juzgas el resultado.' }, argument: { title: 'Una explicación para tu deportista', body: 'Muestra por qué el plan es así. La exportación JSON lleva toda la estructura.' }, cta: 'Crear tu primera plantilla', note: 'Las cuentas de deportistas y el historial de ejecución están previstos; hoy trabajas en tus propios planes.',
    },
    roadmap: {
      eyebrow: '09 · HACIA DÓNDE VAMOS', title: 'Hoy: diseño y análisis. Después: ejecución y seguimiento en el tiempo.', athlete: { title: 'Seguimiento de deportistas', body: 'La siguiente etapa conectará el plan con el historial de ejecución: cargas, repeticiones, RIR, cambios de ejercicio, deloads y tendencias de e1RM.', flow: ['Plan', 'Prescripción', 'Ejecución', 'Historial'] }, mobile: { title: 'Modo de entrenamiento móvil', body: 'Durante una sesión importa la siguiente serie. El modo previsto mostrará el entrenamiento del día y dará acceso rápido a la técnica.', flow: ['Sesión de hoy', 'Registrar ejecución', 'Técnica'] },
    },
    cta: { title: 'Empieza con un ejercicio. Descubre hasta dónde puedes llegar.', body: 'De comprender el movimiento a decidir el plan — respuestas sencillas en la superficie, modelos explícitos debajo.', primary: 'Abrir el Atlas de ejercicios', secondary: 'Crear un borrador' },
    footer: { navigation: 'Navegación de la página de inicio', links: { exerciseAtlas: 'Atlas de ejercicios', muscleAtlas: 'Atlas de músculos', planBuilder: 'Creador de planes', analysis: 'Análisis', model: 'Modelo' }, disclaimer: 'Los valores de Agonez son estimaciones modeladas basadas en supuestos explícitos. No son mediciones de tu cuerpo ni consejo médico.' },
    badges: { comingSoon: 'PRÓXIMAMENTE', experimental: 'MODELO EXPERIMENTAL' },
  },
}
