export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      betaBadge: 'PRIVAT BETA · HÖSTEN 2026',
      waitlist: { label: 'E-postadress', placeholder: "du{'@'}exempel.se", button: 'Gå med i kön', note: 'Ingen spam. Bara ett mejl när din inbjudan är klar.', submitting: 'Registrerar…', joined: 'Registrerad', success: 'Du står på listan. Vi mejlar dig när din inbjudan är klar.', error: 'Vi kunde inte spara din adress. Försök igen.', emailSubject: 'Agonez privata beta — intresseanmälan', emailBody: 'Hej,\n\njag vill stå på väntelistan för Agonez privata beta.\n\nMin e-postadress: {email}\n\nJag vill använda Agonez till:\n' },
      eyebrow: 'ÖVNINGSATLAS · PROGRAMBYGGARE · PROGRESSIONSCOACHING', title: 'Förstå din träning och bygg ett program som hänger ihop.', lead: 'Se vilka muskler din övning faktiskt riktar sig mot. Bygg ett veckoprogram av övningarna och se vad programmet gör med din kropp.', ctaPrimary: 'Öppna Atlasen', ctaSecondary: 'Se programanalysen', proof: ['över 150 övningar', 'interaktiv anatomi', 'från en repetition till en mikrocykel'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANALYS',
    },
    audiences: {
      eyebrow: '01 · FÖR VEM', title: 'Och du — var befinner du dig?', beginner: { tag: 'JAG HAR NYSS BÖRJAT', title: 'Börjar du träna och allt känns onödigt komplicerat?', body: 'Se vilka muskler som arbetar och följ tekniken steg för steg. Prova Programbyggaren.', link: 'Öppna Övningsatlasen' }, advanced: { tag: 'JAG VILL GÅ DJUPARE', title: 'Har du tränat ett tag och vill verkligen förstå ditt program?', body: 'Jämför varianter och analysera stimulansfördelning, ledexponering och modellerad återhämtningsskuld. Kontrollera om ditt program är optimalt.', link: 'Se hur Analysen fungerar' }, coach: { tag: 'JAG PROGRAMMERAR ÅT ANDRA', title: 'Coachar du idrottare? Vill du ha ett professionellt verktyg?', body: 'Bygg mikrocykler med tydliga roller, alternativ, mål, RIR och progressionsmodeller. Följ sedan dina idrottares utveckling.', link: 'Se coachavsnittet' },
    },
    loop: {
      s1: { title: 'Lär känna övningarna', body: 'Teknik, muskler och rekommenderade repetitionsintervall.' }, s2: { title: 'Lägg upp din split', body: 'PPL, helkropp eller egen struktur — set, RIR, belastning och progressionsmodeller.' }, s3: { title: 'Kör analysen', body: 'Stimulansfördelning samt muskel- och ledåterhämtning — ner till setnivå.' }, s4: { title: 'Genomför programmet och följ utvecklingen', body: 'Utförande, sethistorik och styrketrend — nästa steg i din utveckling.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ÖVNINGSATLAS', title: 'Inte bara ”bänkpress”. En specifik teknik med specifika antaganden.', body: 'Varje övning beskrivs som en definierad variant: utrustning, position, rörelsebana, rörelseomfång, tekniska stoppkriterier och en egen modellerad exponeringsprofil.', etuRows: { title: 'Muskelexponering i siffror', body: 'Råa cm², andel av uppskattad kapacitet och relativ intensitet.' }, etuAnatomy: { title: 'Stimulansfördelning på kroppen', body: 'Värmekarta normaliserad mot uppskattad FCSA.' }, technique: { title: 'Teknik för den här varianten', body: 'Position → utförande → när du ska avbryta.' }, classification: { title: 'Variantklassificering', body: 'Mekanisk nivå, motståndskälla och utförandemönster.' }, disclaimer: 'värden normaliserade mot en gemensam referensidrottare · dina värden kan skilja sig',
    },
    planBuilder: {
      eyebrow: '03 · PROGRAMBYGGARE', title: 'Bygg programmet av delarna som faktiskt spelar roll.', body: 'Definiera tränings- och vilodagar, övningsroller, mål, alternativ, set, repetitionsintervall och RIR. Ett program är en ordnad mikrocykel, inte en anteckning.', roles: { label: 'ROLLER', body: 'Primär progression · sekundär progression · volymackumulering · tillbehör.' }, slot: { label: 'SLOT', body: 'Behåll slotens avsikt även när övningen behöver bytas.' }, rest: { label: 'VILA', body: 'En vilodag är inte en tom ruta — den anger tiden mellan stimuli.' }, ctaPrimary: 'Öppna Programbyggaren', ctaSecondary: 'Se analysen', panelDays: { left: 'ORDNAD MIKROCYKEL', right: '7 dagar · D01–D07' }, panelSlot: { left: 'SLOT · SETORDINATION', right: 'roll · standardövning · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · PROGRAMANALYS', title: 'Ett program är mer än summan av sina set.', body: 'Analysera ett sparat utkast och se vart stimulansen går, vilka muskler som arbetar avsiktligt eller indirekt och om de hinner återhämta sig mellan dagarna.', strip: { left: 'MIKROCYKEL · DAGSGRÄNSER', right: 'analys av sparat utkast · uppdatera efter ändringar' }, recovery: { title: 'Återhämtning efter träning', meta: 'hours_to_fresh' }, ranking: { title: 'Veckovis antal set per muskel', meta: 'ETU/cm²/7d' }, debts: { title: 'Muskelns återhämtningsstatus', body: 'När är muskeln fräsch igen?' }, targeted: { title: 'Avsiktligt och indirekt arbete', body: 'Se både vad programmet avsåg och det indirekta arbete som övningsvalen skapar.' }, provenance: { title: 'Varje summa har en källa', body: 'Resultatet leder tillbaka till dag, övning och set, med effektiva repetitioner och modellparametrar.' }, disclaimer: 'modellresultat · inte träningsvärk, vävnadsläkningstid eller bedömning av skaderisk',
    },
    muscleAtlas: {
      eyebrow: '05 · MUSKELATLAS', title: 'Lär känna muskeln innan du börjar räkna set.', body: 'Anatomi, funktion, arkitektur, uppskattad fibertypsfördelning och de bästa övningarna — på samma plats.', specs: [{ k: 'MORFOLOGI', v: 'massa, volym' }, { k: 'ARKITEKTUR', v: 'pennation, fiberlängd' }, { k: 'FIBRER', v: 'uppskattad andel typ I och II' }, { k: 'FCSA', v: 'kraftenhet' }], note: 'FCSA är varken ett fiberantal eller ett mått på hypertrofipotential. Det är en uppskattad kraftöverförande tvärsnittsarea som används som gemensam nämnare.', link: 'Gå från muskel till övningar',
    },
    features: {
      eyebrow: '06 · FLER FUNKTIONER', title: 'Resten av systemet, kortfattat', technique: { title: 'Teknikbibliotek', body: 'Position, rörelse, ROM, instruktioner, tekniskt stopp, RIR och vanliga misstag.' }, io: { title: 'Import / export av program', body: 'Ladda enkelt ner eller upp ett program som text. Med hjälp av AI blir det lätt att importera dina egna program.' }, mobile: { title: 'Träning i mobilen', body: 'Öppna appen under träningen och låt den guida dig genom passet.' }, progress: { title: 'Följ utvecklingen', body: 'Utförandehistorik, styrketrender och automatiserade progressionsmodeller — även för coaching.' }, knowledge: { title: 'Kunskapsbas', body: 'En vetenskapsbaserad kunskapsblogg. Atlasen kommer också att omfatta rörelser och leder.' },
    },
    model: {
      eyebrow: '07 · UNDER HUVEN', title: 'Vi mäter inte biologi genom en skärm. Vi bygger en transparent beslutsmodell.', body: 'Styrketräning sker under osäkerhet. Agonez ordnar antaganden, uppskattar följder och visar var resultatet kommer ifrån. Där mätning saknas kallar vi det en modell.', chain: ['övning', 'muskler', 'mekanisk stimulans', 'återhämtning', 'programvecka', 'progression'], expandHint: 'ÖPPNA FÖR ATT SE DETALJER',
      etu: { title: 'ETU', summary: 'Hur mycket spänningsstimulans från en effektiv repetition som når en muskel.', body: 'En övning ”tränar” inte bara bröstet. Den har en profil: en del av spänningen går till de primära musklerna och en del till stabilisatorerna. ETU (Effective Tension Unit) uppskattar fördelningen för en effektiv repetition, så att två varianter av samma rörelse kan jämföras numeriskt.', caveat: 'Det är inte EMG, aktiveringsprocent eller en mätning av hypertrofi.' }, fcsa: { title: 'FCSA', summary: 'En gemensam nämnare för att jämföra stora och små muskler på samma skala.', caveat: 'Detta är mekaniskt krav, inte trötthet eller fiberantal.' }, recovery: { title: 'MRU · JRU', summary: 'Modellerad muskel- och ledskuld: ökar efter set och sjunker mellan pass.', body: 'Varje set lägger till lokal skuld i musklerna, och mer ju närmare teknisk failure setet ligger. Skulden minskar med tiden, så avståndet mellan stimuli för samma muskel är en del av programmet. JRU gör samma sak för lederna.', caveat: 'Ett jämförelseverktyg, inte biologisk klocka eller skaderiskbedömning.' }, reference: { title: 'Referensidrottare', summary: 'Atlasens mätvärden kalibreras mot en tydligt beskriven bas.', caveat: 'Din utgångspunkt kan skilja sig avsevärt, medan de relativa relationerna bara bör skilja sig marginellt.' }, limits: { title: 'Modellens gränser', summary: 'Det modellen inte ser — öppet redovisat, inte dolt.', note: 'modellversion, antaganden och diagnostik förblir synliga i appen' },
    },
    coaches: {
      eyebrow: '08 · FÖR COACHER', title: 'Hjälp fler idrottare utan att ge upp kvaliteten i coachningen.', body: 'En mikrocykelmall, färdiga alternativ och automatisk granskning ersätter ett nytt kalkylblad för varje klient. Tiden som gick åt till kopiering kan läggas på coaching.', reuse: { title: 'Ett program att återanvända', body: 'En mikrocykel byggd en gång — med roller, set och RIR — blir startpunkten för nästa idrottare.' }, swap: { title: 'Ett byte på några sekunder', body: 'En upptagen maskin eller öm led förstör inte programmet — sloten behåller sin avsikt.' }, audit: { title: 'Granskning i stället för manuell räkning', body: 'Stimulansfördelning, indirekt arbete, modellerad skuld mellan dagar och belastningsprogression beräknas automatiskt; du bedömer resultatet.' }, argument: { title: 'Enkel delning', body: 'Skicka en länk till idrottaren så får hen ett färdigt program att öppna i appen.' }, adaptation: { title: 'Varje idrottare är unik', body: 'Ser du att en idrottare inte återhämtar sig från programmet? Med tiden lär du känna personen bättre och kan anpassa modellparametrarna specifikt efter hen.' }, cta: 'Bygg din första mall', note: 'Idrottarkonton och utförandehistorik är planerade — i dag arbetar du med dina egna program.',
    },
    roadmap: {
      eyebrow: '09 · VART DET ÄR PÅ VÄG', title: 'I dag: planering och analys. I morgon: genomförande och coaching över tid.', athlete: { title: 'Idrottscoaching', body: 'Nästa steg kopplar programmet till utförandehistorik: belastning, repetitioner, RIR, övningsbyten, deloads och e1RM-trender.', flow: ['Program', 'Ordination', 'Utförande', 'Historik'] }, mobile: { title: 'Träning i mobilen', body: 'Under passet är nästa set det viktiga. Det planerade läget visar dagens pass och ger snabb tillgång till teknik.', flow: ['Dagens pass', 'Logga utförande', 'Teknik'] },
    },
    cta: { eyebrow: 'EN ÖPPEN INBJUDAN', title: 'Hjälp mänskligheten att nå excellens inom träning.', body: 'Agonez befinner sig i ett tidigt skede. Vi bygger det i skärningspunkten mellan träning, vetenskap, teknik och produktutveckling.', bodySecondary: 'Om du arbetar inom något av dessa områden och vill samskapa ett verktyg grundat i verkliga problem, domänkunskap och kritisk återkoppling söker vi dig.', rolesLabel: 'Människor och perspektiv vi gärna möter', roles: ['Personliga tränare', 'Idrottare', 'Biomekaniker', 'Idrottsvetenskap', 'Produkt & utveckling', 'UX / forskning', 'Marknadsföring', 'Tidiga partner & early adopters'], action: 'Låt oss prata', note: 'Öppet för fokuserade samtal och tydligt avgränsade samarbeten. Öppnar din e-postapp.', emailSubject: 'Bygg Agonez tillsammans med oss', emailBody: 'Hej,\n\njag vill prata om att bidra till Agonez.\n\nMin bakgrund eller idé:\n' }, footer: { navigation: 'Navigering på startsidan', links: { exerciseAtlas: 'Övningsatlas', muscleAtlas: 'Muskelatlas', planBuilder: 'Programbyggare', analysis: 'Analys', model: 'Modell' }, disclaimer: 'Agonez-värden är modellerade uppskattningar baserade på tydliga antaganden. De är inte mätningar av din kropp och inte medicinska råd.' }, badges: { comingSoon: 'KOMMER SNART', experimental: 'EXPERIMENTELL MODELL' },
  },
}
