export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      eyebrow: 'ÖVNINGSATLAS · PROGRAMBYGGARE · TRÄNINGSANALYS', title: 'Förstå din träning och bygg ett program som hänger ihop.', lead: 'Se vad en övning faktiskt gör, bygg in övningarna i ett veckoprogram och se dess modellerade effekter på kroppen. Svaren förblir enkla — och du kan gå djupare när du vill.', ctaPrimary: 'Öppna Atlasen', ctaSecondary: 'Se programanalysen', proof: ['över 150 dokumenterade tekniker', 'interaktiv anatomi', 'från ett set till en mikrocykel'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANALYS',
    },
    audiences: {
      eyebrow: '01 · FÖR VEM', title: 'Och du — var befinner du dig?', beginner: { tag: 'JAG HAR NYSS BÖRJAT', title: 'Har du nyss börjat och allt känns onödigt komplicerat?', body: 'Se vilka muskler som arbetar, följ tekniken steg för steg och förstå hur set, repetitioner och RIR blir ett program.', link: 'Öppna Övningsatlasen' }, advanced: { tag: 'JAG VILL GÅ DJUPARE', title: 'Har du tränat ett tag och vill verkligen förstå ditt program?', body: 'Jämför varianter och analysera stimulansfördelning, ledexponering och modellerad återhämtningsskuld ända ner till setet.', link: 'Se hur Analysen fungerar' }, coach: { tag: 'JAG PROGRAMMERAR ÅT ANDRA', title: 'Coachar du idrottare? Bygg och analysera program i samma system.', body: 'Bygg mikrocykler med tydliga roller, alternativ, mål, RIR och progressionsmodeller och analysera sedan det sparade programmet.', link: 'Se coachavsnittet' },
    },
    loop: {
      s1: { title: 'Lär känna övningen', body: 'Teknik, muskler och rekommenderade repetitionsintervall.' }, s2: { title: 'Lägg upp din split', body: 'PPL, helkropp eller egen struktur — dagar, vila, set och RIR.' }, s3: { title: 'Kör analysen', body: 'Stimulansfördelning, återhämtning och ledexponering — ner till setnivå.' }, s4: { title: 'Genomför programmet och följ utvecklingen', body: 'Utförande, sethistorik och styrketrend — nästa utvecklingssteg.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ÖVNINGSATLAS', title: 'Inte bara ”bänkpress”. En specifik teknik med specifika antaganden.', body: 'Varje övning beskrivs som en definierad variant: utrustning, position, rörelsebana, rörelseomfång, tekniska stoppkriterier och en egen modellerad exponeringsprofil.', etuRows: { title: 'Muskelexponering i siffror', body: 'Råa cm², andel av uppskattad kapacitet och relativ intensitet.' }, etuAnatomy: { title: 'Stimulansfördelning på kroppen', body: 'Värmekarta normaliserad mot uppskattad FCSA.' }, technique: { title: 'Teknik för den här varianten', body: 'Position → utförande → när du ska avbryta.' }, classification: { title: 'Variantklassificering', body: 'Mekanisk nivå, motståndskälla och utförandemönster.' }, disclaimer: 'värden normaliserade mot en gemensam referensidrottare · dina värden kan skilja sig',
    },
    planBuilder: {
      eyebrow: '03 · PROGRAMBYGGARE', title: 'Bygg programmet av delarna som faktiskt spelar roll.', body: 'Definiera tränings- och vilodagar, övningsroller, mål, alternativ, set, repetitionsintervall och RIR. Ett program är en ordnad mikrocykel, inte en anteckning.', roles: { label: 'ROLLER', body: 'Primär progression · sekundär progression · volymackumulering · tillbehör.' }, slot: { label: 'SLOT', body: 'Behåll slotens avsikt även när övningen behöver bytas.' }, rest: { label: 'VILA', body: 'En vilodag är inte en tom ruta — den anger tiden mellan stimuli.' }, ctaPrimary: 'Öppna Programbyggaren', ctaSecondary: 'Se analysen', panelDays: { left: 'ORDNAD MIKROCYKEL', right: '7 dagar · D01–D07' }, panelSlot: { left: 'SLOT · SETORDINATION', right: 'roll · standardövning · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · PROGRAMANALYS', title: 'Ett program är mer än summan av sina set.', body: 'Analysera ett sparat utkast och se vart stimulansen går, vilka muskler som arbetar avsiktligt eller indirekt och hur modellen för återhämtningsskuld mellan dagar.', strip: { left: 'MIKROCYKEL · DAGSGRÄNSER', right: 'analys av sparat utkast · uppdatera efter ändringar' }, recovery: { title: 'Lokal återhämtning efter träning', meta: 'hours_to_fresh' }, ranking: { title: 'Veckovis stimulansfördelning', meta: 'ETU/cm²/7d' }, debts: { title: 'Största modellerade skulder', body: 'Beredskap vid dagsgränsen.' }, targeted: { title: 'Avsiktligt och indirekt arbete', body: 'Se både vad programmet avsåg och det indirekta arbete som övningsvalen skapar.' }, provenance: { title: 'Varje summa har en källa', body: 'Resultatet leder tillbaka till dag, övning och set, med effektiva repetitioner och modellparametrar.' }, disclaimer: 'modellresultat · inte träningsvärk, vävnadsläkningstid eller bedömning av skaderisk',
    },
    muscleAtlas: {
      eyebrow: '05 · MUSKELATLAS', title: 'Lär känna muskeln innan du börjar räkna set.', body: 'Anatomi, funktion, arkitektur, uppskattad fibertypsfördelning och övningar med störst modellerad exponering — på samma plats.', specs: [{ k: 'MORFOLOGI', v: 'massa, volym' }, { k: 'ARKITEKTUR', v: 'pennation, fiberlängd' }, { k: 'FIBRER', v: 'uppskattad fördelning' }, { k: 'FCSA', v: 'kapacitetsreferens' }], note: 'FCSA är varken ett fiberantal eller ett mått på hypertrofipotential. Det är en uppskattad kraftöverförande tvärsnittsarea som används som gemensam nämnare.', link: 'Gå från muskel till övningar',
    },
    features: {
      eyebrow: '06 · FLER FUNKTIONER', title: 'Resten av systemet, kortfattat', technique: { title: 'Teknikbibliotek', body: 'Position, rörelse, ROM, instruktioner, tekniskt stopp, RIR och vanliga misstag.' }, io: { title: 'Import / export av program', body: 'Ta en förenklad struktur till extern analys och importera tillbaka ett validerat dokument.' }, mobile: { title: 'Mobilt träningsläge', body: 'Dagens pass och teknik nära till hands under träningen.' }, progress: { title: 'Följ utvecklingen', body: 'Utförandehistorik, styrketrender och automatiserade progressionsmodeller — även för coaching.' }, knowledge: { title: 'Kunskapsbas', body: 'Muskelartiklar fungerar redan; den växande basen ska även omfatta leder och kopplas till Atlas och Analys.' },
    },
    model: {
      eyebrow: '07 · UNDER HUVEN', title: 'Vi mäter inte biologi genom en skärm. Vi bygger en transparent beslutsmodell.', body: 'Styrketräning sker under osäkerhet. Agonez ordnar antaganden, uppskattar följder och visar var resultatet kommer ifrån. Där mätning saknas kallar vi det en modell.', chain: ['övning', 'muskler', 'mekanisk stimulans', 'återhämtning', 'programvecka', 'progression'], expandHint: 'ÖPPNA FÖR ATT SE DETALJER',
      etu: { title: 'ETU', summary: 'Hur mycket spänningsstimulans från en effektiv repetition som når en muskel.', caveat: 'Det är inte EMG, aktiveringsprocent eller en mätning av hypertrofi.' }, fcsa: { title: 'FCSA', summary: 'En gemensam nämnare för att jämföra stora och små muskler på samma skala.', caveat: 'Detta är mekaniskt krav, inte trötthet eller fiberantal.' }, recovery: { title: 'MRU · JRU', summary: 'Modellerad muskel- och ledskuld: ökar efter set och sjunker mellan pass.', caveat: 'Ett jämförelseverktyg, inte biologisk klocka eller skaderiskbedömning.' }, reference: { title: 'Referensidrottare', summary: 'Atlasens mätvärden kalibreras mot en tydligt beskriven bas.', caveat: 'Dina egna värden kan skilja sig avsevärt.' }, limits: { title: 'Modellens gränser', summary: 'Det modellen inte ser — öppet redovisat, inte dolt.', note: 'modellversion, antaganden och diagnostik förblir synliga i appen' },
    },
    coaches: {
      eyebrow: '08 · FÖR COACHER', title: 'Hjälp fler idrottare utan att ge upp programkvalitet.', body: 'En mikrocykelmall, färdiga alternativ och automatisk granskning ersätter ett nytt kalkylblad för varje klient. Tiden som gick åt till kopiering kan läggas på coaching.', reuse: { title: 'Ett program att återanvända', body: 'En mikrocykel byggd en gång — med roller, set och RIR — blir startpunkten för nästa idrottare.' }, swap: { title: 'Ett byte på några sekunder', body: 'En upptagen maskin eller öm led förstör inte programmet — sloten behåller sin avsikt.' }, audit: { title: 'Granskning i stället för manuell räkning', body: 'Stimulansfördelning, indirekt arbete och modellerad skuld beräknas; du bedömer resultatet.' }, argument: { title: 'En förklaring för idrottaren', body: 'Visa varför programmet ser ut som det gör. JSON-exporten tar hela strukturen med sig.' }, cta: 'Bygg din första mall', note: 'Idrottarkonton och utförandehistorik är planerade — i dag arbetar du med dina egna program.',
    },
    roadmap: {
      eyebrow: '09 · VART DET ÄR PÅ VÄG', title: 'I dag: planering och analys. Nästa steg: genomförande och coaching över tid.', athlete: { title: 'Idrottscoaching', body: 'Nästa steg kopplar programmet till utförandehistorik: belastning, repetitioner, RIR, övningsbyten, deloads och e1RM-trender.', flow: ['Program', 'Ordination', 'Utförande', 'Historik'] }, mobile: { title: 'Mobilt träningsläge', body: 'Under passet är nästa set det viktiga. Det planerade läget visar dagens pass och ger snabb tillgång till teknik.', flow: ['Dagens pass', 'Logga utförande', 'Teknik'] },
    },
    cta: { title: 'Börja med en övning. Se hur djupt du kan gå.', body: 'Från rörelseförståelse till programbeslut — enkla svar på ytan, transparenta modeller under.', primary: 'Öppna Övningsatlasen', secondary: 'Bygg ett programutkast' }, footer: { navigation: 'Navigering på startsidan', links: { exerciseAtlas: 'Övningsatlas', muscleAtlas: 'Muskelatlas', planBuilder: 'Programbyggare', analysis: 'Analys', model: 'Modell' }, disclaimer: 'Agonez-värden är modellerade uppskattningar baserade på tydliga antaganden. De är inte mätningar av din kropp och inte medicinska råd.' }, badges: { comingSoon: 'KOMMER SNART', experimental: 'EXPERIMENTELL MODELL' },
  },
}
