CREATE SCHEMA plans;

CREATE TYPE plans.plan_revision_status AS ENUM ('DRAFT', 'RELEASED', 'ARCHIVED');
CREATE TYPE plans.exercise_slot_role AS ENUM (
    'PRIMARY_PROGRESSIVE',
    'SECONDARY_PROGRESSIVE',
    'VOLUME_ACCUMULATION',
    'ACCESSORY'
);
CREATE TYPE plans.exercise_variant_type AS ENUM ('DEFAULT', 'FALLBACK');

CREATE TABLE plans.workout_plans (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT workout_plans_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE plans.plan_revisions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES plans.workout_plans(id) ON DELETE CASCADE,
    revision_no integer NOT NULL,
    status plans.plan_revision_status NOT NULL DEFAULT 'DRAFT',
    based_on_revision_id integer REFERENCES plans.plan_revisions(id) ON DELETE SET NULL,
    lock_version integer NOT NULL DEFAULT 1,
    snapshot jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    released_at timestamptz,
    CONSTRAINT plan_revisions_revision_positive CHECK (revision_no > 0),
    CONSTRAINT plan_revisions_lock_positive CHECK (lock_version > 0),
    CONSTRAINT plan_revisions_plan_revision_unique UNIQUE (plan_id, revision_no)
);

CREATE UNIQUE INDEX plan_revisions_one_draft_per_plan
    ON plans.plan_revisions (plan_id)
    WHERE status = 'DRAFT';
CREATE INDEX plan_revisions_by_plan ON plans.plan_revisions (plan_id, revision_no DESC);

CREATE TABLE plans.day_prescriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id integer NOT NULL REFERENCES plans.plan_revisions(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    name varchar(200) NOT NULL,
    description text,
    weekday smallint,
    CONSTRAINT day_prescriptions_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT day_prescriptions_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT day_prescriptions_weekday_iso CHECK (weekday BETWEEN 1 AND 7),
    CONSTRAINT day_prescriptions_revision_ordinal_unique
        UNIQUE (revision_id, ordinal) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX day_prescriptions_by_revision
    ON plans.day_prescriptions (revision_id, ordinal);

CREATE TABLE plans.workout_unit_prescriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id integer NOT NULL REFERENCES plans.day_prescriptions(id) ON DELETE CASCADE,
    name varchar(200) NOT NULL,
    description text,
    warmup_notes text,
    stretch_notes text,
    CONSTRAINT workout_unit_prescriptions_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT workout_unit_prescriptions_day_unique
        UNIQUE (day_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX workout_unit_prescriptions_by_day
    ON plans.workout_unit_prescriptions (day_id);

CREATE TABLE plans.exercise_slots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_unit_id integer NOT NULL
        REFERENCES plans.workout_unit_prescriptions(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    name varchar(200),
    description text,
    goal text,
    role plans.exercise_slot_role NOT NULL,
    volume_axis varchar(100),
    CONSTRAINT exercise_slots_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT exercise_slots_unit_ordinal_unique
        UNIQUE (workout_unit_id, ordinal) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX exercise_slots_by_workout_unit
    ON plans.exercise_slots (workout_unit_id, ordinal);

CREATE TABLE plans.exercise_slot_target_muscles (
    slot_id integer NOT NULL REFERENCES plans.exercise_slots(id) ON DELETE CASCADE,
    muscle_id integer NOT NULL REFERENCES core.muscles(id) ON DELETE RESTRICT,
    PRIMARY KEY (slot_id, muscle_id)
);
CREATE INDEX exercise_slot_targets_by_muscle
    ON plans.exercise_slot_target_muscles (muscle_id, slot_id);

CREATE TABLE plans.exercise_variants (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id integer NOT NULL REFERENCES plans.exercise_slots(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    variant_type plans.exercise_variant_type NOT NULL,
    exercise_id integer NOT NULL REFERENCES core.exercises(id) ON DELETE RESTRICT,
    CONSTRAINT exercise_variants_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT exercise_variants_slot_ordinal_unique
        UNIQUE (slot_id, ordinal) DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX exercise_variants_one_default_per_slot
    ON plans.exercise_variants (slot_id)
    WHERE variant_type = 'DEFAULT';
CREATE INDEX exercise_variants_by_slot
    ON plans.exercise_variants (slot_id, ordinal);

CREATE TABLE plans.set_infra_prescriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_variant_id integer NOT NULL
        REFERENCES plans.exercise_variants(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    rep_min smallint NOT NULL,
    rep_max smallint NOT NULL,
    rir smallint NOT NULL,
    min_volume_level smallint NOT NULL DEFAULT 0,
    CONSTRAINT set_infra_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT set_infra_rep_min_positive CHECK (rep_min > 0),
    CONSTRAINT set_infra_rep_range_valid CHECK (rep_max >= rep_min),
    CONSTRAINT set_infra_rir_valid CHECK (rir BETWEEN 0 AND 4),
    CONSTRAINT set_infra_min_volume_level_nonnegative CHECK (min_volume_level >= 0),
    CONSTRAINT set_infra_variant_ordinal_unique
        UNIQUE (exercise_variant_id, ordinal) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX set_infra_prescriptions_by_variant
    ON plans.set_infra_prescriptions (exercise_variant_id, ordinal);
