CREATE SCHEMA exec;

CREATE TYPE exec.plan_run_status AS ENUM (
    'scheduled',
    'active',
    'cancelled',
    'completed'
);

CREATE TYPE exec.microcycle_classification AS ENUM (
    'normal',
    'deload',
    'reload'
);

CREATE TYPE exec.workout_session_status AS ENUM (
    'scheduled',
    'in_progress',
    'completed',
    'cancelled',
    'missed'
);

CREATE TYPE exec.completion_mode AS ENUM (
    'as_prescribed',
    'fallback'
);

CREATE TYPE exec.performance_status AS ENUM (
    'draft',
    'finalized'
);

CREATE TYPE exec.exercise_execution_mode AS ENUM (
    'as_prescribed',
    'substituted',
    'skipped',
    'additional'
);

CREATE TYPE exec.performed_set_status AS ENUM (
    'performed',
    'skipped'
);

CREATE TYPE exec.plan_run_event_type AS ENUM (
    'plan_revision_changed',
    'personal_record',
    'deload_started',
    'reload_started',
    'vacation',
    'training_break',
    'observation'
);

CREATE TABLE exec.plan_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    description text,
    initial_plan_revision_id integer NOT NULL
        REFERENCES plans.plan_revisions(id) ON DELETE RESTRICT,
    starts_on date NOT NULL,
    microcycle_count integer NOT NULL,
    microcycle_duration_days integer NOT NULL,
    ends_on date GENERATED ALWAYS AS (
        starts_on + (microcycle_count * microcycle_duration_days - 1)
    ) STORED,
    status exec.plan_run_status NOT NULL DEFAULT 'scheduled',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT plan_runs_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT plan_runs_microcycle_count_positive CHECK (microcycle_count > 0),
    CONSTRAINT plan_runs_microcycle_duration_positive CHECK (microcycle_duration_days > 0)
);

CREATE INDEX plan_runs_by_initial_revision
    ON exec.plan_runs (initial_plan_revision_id);
CREATE INDEX plan_runs_by_status_and_start
    ON exec.plan_runs (status, starts_on);

COMMENT ON COLUMN exec.plan_runs.microcycle_duration_days IS
    'Snapshot of the initial plan revision day count; used with starts_on and microcycle_count to derive ends_on.';

CREATE TABLE exec.microcycles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_run_id integer NOT NULL REFERENCES exec.plan_runs(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    plan_revision_id integer NOT NULL
        REFERENCES plans.plan_revisions(id) ON DELETE RESTRICT,
    classification exec.microcycle_classification NOT NULL DEFAULT 'normal',
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT microcycles_ordinal_positive CHECK (ordinal > 0),
    CONSTRAINT microcycles_date_range_valid CHECK (ends_on >= starts_on),
    CONSTRAINT microcycles_plan_run_ordinal_unique UNIQUE (plan_run_id, ordinal),
    CONSTRAINT microcycles_plan_run_id_unique UNIQUE (plan_run_id, id)
);

CREATE INDEX microcycles_by_revision
    ON exec.microcycles (plan_revision_id, starts_on);

CREATE TABLE exec.workout_unit_tracks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_run_id integer NOT NULL REFERENCES exec.plan_runs(id) ON DELETE CASCADE,
    logical_key text NOT NULL,
    name varchar(200) NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT workout_unit_tracks_key_not_blank CHECK (btrim(logical_key) <> ''),
    CONSTRAINT workout_unit_tracks_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT workout_unit_tracks_plan_run_key_unique UNIQUE (plan_run_id, logical_key),
    CONSTRAINT workout_unit_tracks_plan_run_id_unique UNIQUE (plan_run_id, id)
);

CREATE TABLE exec.exercise_unit_tracks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_run_id integer NOT NULL,
    workout_unit_track_id integer NOT NULL,
    logical_key text NOT NULL,
    name varchar(200) NOT NULL,
    source_progression_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT exercise_unit_tracks_key_not_blank CHECK (btrim(logical_key) <> ''),
    CONSTRAINT exercise_unit_tracks_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT exercise_unit_tracks_workout_key_unique
        UNIQUE (workout_unit_track_id, logical_key),
    CONSTRAINT exercise_unit_tracks_plan_run_id_unique UNIQUE (plan_run_id, id),
    CONSTRAINT exercise_unit_tracks_workout_track_fk
        FOREIGN KEY (plan_run_id, workout_unit_track_id)
        REFERENCES exec.workout_unit_tracks(plan_run_id, id) ON DELETE CASCADE
);

CREATE INDEX exercise_unit_tracks_by_progression
    ON exec.exercise_unit_tracks (source_progression_id)
    WHERE source_progression_id IS NOT NULL;

CREATE TABLE exec.workout_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_run_id integer NOT NULL,
    microcycle_id integer NOT NULL,
    workout_unit_track_id integer NOT NULL,
    source_plan_day_id integer NOT NULL
        REFERENCES plans.day_prescriptions(id) ON DELETE RESTRICT,
    source_plan_workout_unit_id integer NOT NULL
        REFERENCES plans.workout_unit_prescriptions(id) ON DELETE RESTRICT,
    fallback_source_plan_workout_unit_id integer
        REFERENCES plans.workout_unit_prescriptions(id) ON DELETE RESTRICT,
    scheduled_date date NOT NULL,
    status exec.workout_session_status NOT NULL DEFAULT 'scheduled',
    completion_mode exec.completion_mode,
    started_at timestamptz,
    completed_at timestamptz,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT workout_sessions_plan_run_microcycle_fk
        FOREIGN KEY (plan_run_id, microcycle_id)
        REFERENCES exec.microcycles(plan_run_id, id) ON DELETE CASCADE,
    CONSTRAINT workout_sessions_plan_run_track_fk
        FOREIGN KEY (plan_run_id, workout_unit_track_id)
        REFERENCES exec.workout_unit_tracks(plan_run_id, id) ON DELETE RESTRICT,
    CONSTRAINT workout_sessions_occurrence_unique
        UNIQUE (microcycle_id, workout_unit_track_id),
    CONSTRAINT workout_sessions_completion_state_valid CHECK (
        (status = 'completed' AND completion_mode IS NOT NULL)
        OR (status <> 'completed' AND completion_mode IS NULL)
    ),
    CONSTRAINT workout_sessions_timestamps_valid CHECK (
        (status = 'scheduled' AND started_at IS NULL AND completed_at IS NULL)
        OR (status = 'in_progress' AND started_at IS NOT NULL AND completed_at IS NULL)
        OR (
            status = 'completed'
            AND started_at IS NOT NULL
            AND completed_at IS NOT NULL
            AND completed_at >= started_at
        )
        OR (status IN ('cancelled', 'missed') AND started_at IS NULL AND completed_at IS NULL)
    ),
    CONSTRAINT workout_sessions_fallback_valid CHECK (
        (completion_mode = 'fallback' AND fallback_source_plan_workout_unit_id IS NOT NULL)
        OR (
            completion_mode IS DISTINCT FROM 'fallback'
            AND fallback_source_plan_workout_unit_id IS NULL
        )
    )
);

CREATE INDEX workout_sessions_calendar
    ON exec.workout_sessions (plan_run_id, scheduled_date, id);
CREATE INDEX workout_sessions_by_status
    ON exec.workout_sessions (plan_run_id, status, scheduled_date);

CREATE TABLE exec.workout_unit_prescriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_session_id integer NOT NULL UNIQUE
        REFERENCES exec.workout_sessions(id) ON DELETE CASCADE,
    source_plan_revision_id integer NOT NULL
        REFERENCES plans.plan_revisions(id) ON DELETE RESTRICT,
    source_plan_workout_unit_id integer NOT NULL
        REFERENCES plans.workout_unit_prescriptions(id) ON DELETE RESTRICT,
    name_snapshot varchar(200) NOT NULL,
    description_snapshot text,
    warmup_notes_snapshot text,
    stretch_notes_snapshot text,
    prescription_comment text,
    prescribed_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT workout_unit_prescriptions_name_not_blank
        CHECK (btrim(name_snapshot) <> '')
);

CREATE INDEX workout_unit_prescriptions_by_revision
    ON exec.workout_unit_prescriptions (source_plan_revision_id);

CREATE TABLE exec.exercise_unit_prescriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_unit_prescription_id integer NOT NULL
        REFERENCES exec.workout_unit_prescriptions(id) ON DELETE CASCADE,
    exercise_unit_track_id integer NOT NULL
        REFERENCES exec.exercise_unit_tracks(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    source_plan_exercise_slot_id integer NOT NULL
        REFERENCES plans.exercise_slots(id) ON DELETE RESTRICT,
    source_plan_exercise_variant_id integer NOT NULL
        REFERENCES plans.exercise_variants(id) ON DELETE RESTRICT,
    source_progression_id uuid,
    prescribed_exercise_id integer NOT NULL
        REFERENCES core.exercises(id) ON DELETE RESTRICT,
    slot_name_snapshot varchar(200),
    plan_description_snapshot text,
    plan_goal_snapshot text,
    slot_role_snapshot plans.exercise_slot_role NOT NULL,
    progression_model_slug_snapshot text,
    prescription_comment text,
    previous_exercise_performance_id integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT exercise_unit_prescriptions_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT exercise_unit_prescriptions_order_unique
        UNIQUE (workout_unit_prescription_id, ordinal),
    CONSTRAINT exercise_unit_prescriptions_track_unique
        UNIQUE (workout_unit_prescription_id, exercise_unit_track_id)
);

CREATE INDEX exercise_unit_prescriptions_trace
    ON exec.exercise_unit_prescriptions (exercise_unit_track_id, workout_unit_prescription_id);

CREATE TABLE exec.set_prescriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_unit_prescription_id integer NOT NULL
        REFERENCES exec.exercise_unit_prescriptions(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    source_plan_set_infra_id integer NOT NULL
        REFERENCES plans.set_infra_prescriptions(id) ON DELETE RESTRICT,
    set_role_snapshot plans.set_role NOT NULL,
    rep_min smallint NOT NULL,
    rep_max smallint NOT NULL,
    target_rir plans.rir_prescription NOT NULL,
    prescribed_load_kg numeric(8,3),
    prescription_comment text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT set_prescriptions_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT set_prescriptions_rep_min_positive CHECK (rep_min > 0),
    CONSTRAINT set_prescriptions_rep_range_valid CHECK (rep_max >= rep_min),
    CONSTRAINT set_prescriptions_load_nonnegative
        CHECK (prescribed_load_kg IS NULL OR prescribed_load_kg >= 0),
    CONSTRAINT set_prescriptions_order_unique
        UNIQUE (exercise_unit_prescription_id, ordinal)
);

CREATE TABLE exec.workout_unit_performances (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_unit_prescription_id integer NOT NULL UNIQUE
        REFERENCES exec.workout_unit_prescriptions(id) ON DELETE CASCADE,
    status exec.performance_status NOT NULL DEFAULT 'draft',
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    performance_comment text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT workout_unit_performances_completion_valid CHECK (
        (status = 'draft' AND completed_at IS NULL)
        OR (
            status = 'finalized'
            AND completed_at IS NOT NULL
            AND completed_at >= started_at
        )
    )
);

CREATE TABLE exec.exercise_unit_performances (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_unit_performance_id integer NOT NULL
        REFERENCES exec.workout_unit_performances(id) ON DELETE CASCADE,
    prescribed_exercise_unit_id integer
        REFERENCES exec.exercise_unit_prescriptions(id) ON DELETE CASCADE,
    exercise_unit_track_id integer NOT NULL
        REFERENCES exec.exercise_unit_tracks(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    execution_mode exec.exercise_execution_mode NOT NULL,
    actual_exercise_id integer REFERENCES core.exercises(id) ON DELETE RESTRICT,
    actual_plan_exercise_variant_id integer
        REFERENCES plans.exercise_variants(id) ON DELETE RESTRICT,
    performance_comment text,
    engine_model_version text,
    etu_vector_snapshot jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT exercise_unit_performances_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT exercise_unit_performances_order_unique
        UNIQUE (workout_unit_performance_id, ordinal),
    CONSTRAINT exercise_unit_performances_prescribed_unique
        UNIQUE (prescribed_exercise_unit_id),
    CONSTRAINT exercise_unit_performances_mode_valid CHECK (
        (
            execution_mode IN ('as_prescribed', 'substituted')
            AND prescribed_exercise_unit_id IS NOT NULL
            AND actual_exercise_id IS NOT NULL
        )
        OR (
            execution_mode = 'skipped'
            AND prescribed_exercise_unit_id IS NOT NULL
            AND actual_exercise_id IS NULL
            AND actual_plan_exercise_variant_id IS NULL
        )
        OR (
            execution_mode = 'additional'
            AND prescribed_exercise_unit_id IS NULL
            AND actual_exercise_id IS NOT NULL
        )
    ),
    CONSTRAINT exercise_unit_performances_etu_snapshot_object CHECK (
        etu_vector_snapshot IS NULL OR jsonb_typeof(etu_vector_snapshot) = 'object'
    )
);

CREATE INDEX exercise_unit_performances_trace
    ON exec.exercise_unit_performances (exercise_unit_track_id, workout_unit_performance_id);

CREATE TABLE exec.set_performances (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_unit_performance_id integer NOT NULL
        REFERENCES exec.exercise_unit_performances(id) ON DELETE CASCADE,
    prescribed_set_id integer REFERENCES exec.set_prescriptions(id) ON DELETE CASCADE,
    ordinal integer NOT NULL,
    status exec.performed_set_status NOT NULL DEFAULT 'performed',
    load_kg numeric(8,3),
    repetitions smallint,
    rir smallint,
    performance_comment text,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT set_performances_ordinal_nonnegative CHECK (ordinal >= 0),
    CONSTRAINT set_performances_load_nonnegative CHECK (load_kg IS NULL OR load_kg >= 0),
    CONSTRAINT set_performances_repetitions_nonnegative
        CHECK (repetitions IS NULL OR repetitions >= 0),
    CONSTRAINT set_performances_rir_valid CHECK (rir IS NULL OR rir BETWEEN 0 AND 10),
    CONSTRAINT set_performances_order_unique
        UNIQUE (exercise_unit_performance_id, ordinal),
    CONSTRAINT set_performances_prescribed_unique UNIQUE (prescribed_set_id),
    CONSTRAINT set_performances_status_values_valid CHECK (
        (status = 'performed' AND repetitions IS NOT NULL)
        OR (
            status = 'skipped'
            AND load_kg IS NULL
            AND repetitions IS NULL
            AND rir IS NULL
        )
    )
);

ALTER TABLE exec.exercise_unit_prescriptions
    ADD CONSTRAINT exercise_unit_prescriptions_previous_performance_fk
    FOREIGN KEY (previous_exercise_performance_id)
    REFERENCES exec.exercise_unit_performances(id) ON DELETE SET NULL;

CREATE TABLE exec.plan_run_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_run_id integer NOT NULL REFERENCES exec.plan_runs(id) ON DELETE CASCADE,
    microcycle_id integer,
    workout_session_id integer REFERENCES exec.workout_sessions(id) ON DELETE SET NULL,
    exercise_unit_track_id integer
        REFERENCES exec.exercise_unit_tracks(id) ON DELETE SET NULL,
    event_type exec.plan_run_event_type NOT NULL,
    occurred_at timestamptz NOT NULL,
    title varchar(200) NOT NULL,
    details text,
    from_plan_revision_id integer
        REFERENCES plans.plan_revisions(id) ON DELETE RESTRICT,
    to_plan_revision_id integer
        REFERENCES plans.plan_revisions(id) ON DELETE RESTRICT,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT plan_run_events_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT plan_run_events_metadata_object CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT plan_run_events_plan_run_microcycle_fk
        FOREIGN KEY (plan_run_id, microcycle_id)
        REFERENCES exec.microcycles(plan_run_id, id) ON DELETE CASCADE,
    CONSTRAINT plan_run_events_revision_change_valid CHECK (
        event_type <> 'plan_revision_changed'
        OR (
            from_plan_revision_id IS NOT NULL
            AND to_plan_revision_id IS NOT NULL
            AND from_plan_revision_id <> to_plan_revision_id
        )
    )
);

CREATE INDEX plan_run_events_chronological
    ON exec.plan_run_events (plan_run_id, occurred_at, id);

CREATE FUNCTION exec.enforce_session_performance_consistency()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_session_id integer;
    session_state exec.workout_session_status;
    artifact_state exec.performance_status;
BEGIN
    IF TG_TABLE_NAME = 'workout_sessions' THEN
        target_session_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    ELSE
        SELECT prescription.workout_session_id
        INTO target_session_id
        FROM exec.workout_unit_prescriptions AS prescription
        WHERE prescription.id = CASE
            WHEN TG_OP = 'DELETE' THEN OLD.workout_unit_prescription_id
            ELSE NEW.workout_unit_prescription_id
        END;
    END IF;

    SELECT session.status
    INTO session_state
    FROM exec.workout_sessions AS session
    WHERE session.id = target_session_id;

    IF NOT FOUND THEN
        RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
    END IF;

    SELECT performance.status
    INTO artifact_state
    FROM exec.workout_unit_performances AS performance
    JOIN exec.workout_unit_prescriptions AS prescription
        ON prescription.id = performance.workout_unit_prescription_id
    WHERE prescription.workout_session_id = target_session_id;

    IF session_state = 'completed' AND artifact_state IS DISTINCT FROM 'finalized' THEN
        RAISE EXCEPTION
            'completed workout session % requires a finalized performance artifact',
            target_session_id;
    ELSIF session_state = 'in_progress' AND artifact_state IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION
            'in-progress workout session % requires a draft performance artifact',
            target_session_id;
    ELSIF session_state IN ('scheduled', 'cancelled', 'missed') AND artifact_state IS NOT NULL THEN
        RAISE EXCEPTION
            'workout session % in state % cannot own a performance artifact',
            target_session_id,
            session_state;
    END IF;

    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE CONSTRAINT TRIGGER workout_sessions_performance_consistency
AFTER INSERT OR UPDATE OR DELETE ON exec.workout_sessions
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION exec.enforce_session_performance_consistency();

CREATE CONSTRAINT TRIGGER workout_performances_session_consistency
AFTER INSERT OR UPDATE OR DELETE ON exec.workout_unit_performances
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION exec.enforce_session_performance_consistency();

CREATE VIEW exec.workout_session_calendar AS
SELECT
    run.id AS plan_run_id,
    run.name AS plan_run_name,
    microcycle.id AS microcycle_id,
    microcycle.ordinal AS microcycle_ordinal,
    microcycle.plan_revision_id,
    revision.revision_no AS plan_revision_no,
    session.id AS workout_session_id,
    session.scheduled_date,
    session.status,
    session.completion_mode,
    track.id AS workout_unit_track_id,
    track.logical_key AS workout_unit_logical_key,
    track.name AS workout_unit_name,
    prescription.id AS workout_unit_prescription_id,
    performance.id AS workout_unit_performance_id,
    performance.status AS performance_status,
    session.started_at,
    session.completed_at,
    session.notes
FROM exec.workout_sessions AS session
JOIN exec.plan_runs AS run ON run.id = session.plan_run_id
JOIN exec.microcycles AS microcycle ON microcycle.id = session.microcycle_id
JOIN plans.plan_revisions AS revision ON revision.id = microcycle.plan_revision_id
JOIN exec.workout_unit_tracks AS track ON track.id = session.workout_unit_track_id
LEFT JOIN exec.workout_unit_prescriptions AS prescription
    ON prescription.workout_session_id = session.id
LEFT JOIN exec.workout_unit_performances AS performance
    ON performance.workout_unit_prescription_id = prescription.id;

CREATE VIEW exec.exercise_unit_trace AS
SELECT
    run.id AS plan_run_id,
    run.name AS plan_run_name,
    microcycle.ordinal AS microcycle_ordinal,
    session.scheduled_date,
    session.status AS session_status,
    session.completion_mode,
    workout_track.id AS workout_unit_track_id,
    workout_track.name AS workout_unit_name,
    exercise_track.id AS exercise_unit_track_id,
    exercise_track.logical_key AS exercise_unit_logical_key,
    exercise_track.name AS exercise_unit_name,
    prescription.source_plan_revision_id AS plan_revision_id,
    exercise_prescription.source_plan_exercise_variant_id
        AS prescribed_plan_exercise_variant_id,
    exercise_performance.actual_plan_exercise_variant_id
        AS performed_plan_exercise_variant_id,
    prescribed_exercise.id AS prescribed_exercise_id,
    prescribed_exercise.slug AS prescribed_exercise_slug,
    prescribed_exercise.name AS prescribed_exercise_name,
    actual_exercise.id AS performed_exercise_id,
    actual_exercise.slug AS performed_exercise_slug,
    actual_exercise.name AS performed_exercise_name,
    exercise_performance.execution_mode,
    set_prescription.ordinal AS prescribed_set_ordinal,
    set_performance.ordinal AS performed_set_ordinal,
    set_prescription.set_role_snapshot,
    set_prescription.rep_min AS prescribed_rep_min,
    set_prescription.rep_max AS prescribed_rep_max,
    set_prescription.target_rir,
    set_prescription.prescribed_load_kg,
    set_performance.status AS performed_set_status,
    set_performance.load_kg AS performed_load_kg,
    set_performance.repetitions AS performed_repetitions,
    set_performance.rir AS performed_rir,
    exercise_prescription.prescription_comment AS exercise_prescription_comment,
    set_prescription.prescription_comment AS set_prescription_comment,
    exercise_performance.performance_comment AS exercise_performance_comment,
    set_performance.performance_comment AS set_performance_comment,
    exercise_performance.engine_model_version,
    exercise_performance.etu_vector_snapshot,
    CASE
        WHEN exercise_performance.id IS NULL THEN NULL
        ELSE
            exercise_performance.execution_mode IS DISTINCT FROM 'as_prescribed'
            OR set_performance.prescribed_set_id IS NULL
            OR set_performance.status = 'skipped'
            OR set_performance.load_kg IS DISTINCT FROM set_prescription.prescribed_load_kg
    END AS diverged_from_prescription
FROM exec.set_prescriptions AS set_prescription
JOIN exec.exercise_unit_prescriptions AS exercise_prescription
    ON exercise_prescription.id = set_prescription.exercise_unit_prescription_id
JOIN exec.workout_unit_prescriptions AS prescription
    ON prescription.id = exercise_prescription.workout_unit_prescription_id
JOIN exec.workout_sessions AS session
    ON session.id = prescription.workout_session_id
JOIN exec.plan_runs AS run ON run.id = session.plan_run_id
JOIN exec.microcycles AS microcycle ON microcycle.id = session.microcycle_id
JOIN exec.workout_unit_tracks AS workout_track
    ON workout_track.id = session.workout_unit_track_id
JOIN exec.exercise_unit_tracks AS exercise_track
    ON exercise_track.id = exercise_prescription.exercise_unit_track_id
JOIN core.exercises AS prescribed_exercise
    ON prescribed_exercise.id = exercise_prescription.prescribed_exercise_id
LEFT JOIN exec.exercise_unit_performances AS exercise_performance
    ON exercise_performance.prescribed_exercise_unit_id = exercise_prescription.id
LEFT JOIN core.exercises AS actual_exercise
    ON actual_exercise.id = exercise_performance.actual_exercise_id
LEFT JOIN exec.set_performances AS set_performance
    ON set_performance.prescribed_set_id = set_prescription.id

UNION ALL

SELECT
    run.id AS plan_run_id,
    run.name AS plan_run_name,
    microcycle.ordinal AS microcycle_ordinal,
    session.scheduled_date,
    session.status AS session_status,
    session.completion_mode,
    workout_track.id AS workout_unit_track_id,
    workout_track.name AS workout_unit_name,
    exercise_track.id AS exercise_unit_track_id,
    exercise_track.logical_key AS exercise_unit_logical_key,
    exercise_track.name AS exercise_unit_name,
    prescription.source_plan_revision_id AS plan_revision_id,
    exercise_prescription.source_plan_exercise_variant_id
        AS prescribed_plan_exercise_variant_id,
    exercise_performance.actual_plan_exercise_variant_id
        AS performed_plan_exercise_variant_id,
    prescribed_exercise.id AS prescribed_exercise_id,
    prescribed_exercise.slug AS prescribed_exercise_slug,
    prescribed_exercise.name AS prescribed_exercise_name,
    actual_exercise.id AS performed_exercise_id,
    actual_exercise.slug AS performed_exercise_slug,
    actual_exercise.name AS performed_exercise_name,
    exercise_performance.execution_mode,
    NULL::integer AS prescribed_set_ordinal,
    set_performance.ordinal AS performed_set_ordinal,
    NULL::plans.set_role AS set_role_snapshot,
    NULL::smallint AS prescribed_rep_min,
    NULL::smallint AS prescribed_rep_max,
    NULL::plans.rir_prescription AS target_rir,
    NULL::numeric(8,3) AS prescribed_load_kg,
    set_performance.status AS performed_set_status,
    set_performance.load_kg AS performed_load_kg,
    set_performance.repetitions AS performed_repetitions,
    set_performance.rir AS performed_rir,
    exercise_prescription.prescription_comment AS exercise_prescription_comment,
    NULL::text AS set_prescription_comment,
    exercise_performance.performance_comment AS exercise_performance_comment,
    set_performance.performance_comment AS set_performance_comment,
    exercise_performance.engine_model_version,
    exercise_performance.etu_vector_snapshot,
    true AS diverged_from_prescription
FROM exec.set_performances AS set_performance
JOIN exec.exercise_unit_performances AS exercise_performance
    ON exercise_performance.id = set_performance.exercise_unit_performance_id
JOIN exec.workout_unit_performances AS performance
    ON performance.id = exercise_performance.workout_unit_performance_id
JOIN exec.workout_unit_prescriptions AS prescription
    ON prescription.id = performance.workout_unit_prescription_id
JOIN exec.workout_sessions AS session
    ON session.id = prescription.workout_session_id
JOIN exec.plan_runs AS run ON run.id = session.plan_run_id
JOIN exec.microcycles AS microcycle ON microcycle.id = session.microcycle_id
JOIN exec.workout_unit_tracks AS workout_track
    ON workout_track.id = session.workout_unit_track_id
JOIN exec.exercise_unit_tracks AS exercise_track
    ON exercise_track.id = exercise_performance.exercise_unit_track_id
LEFT JOIN exec.exercise_unit_prescriptions AS exercise_prescription
    ON exercise_prescription.id = exercise_performance.prescribed_exercise_unit_id
LEFT JOIN core.exercises AS prescribed_exercise
    ON prescribed_exercise.id = exercise_prescription.prescribed_exercise_id
LEFT JOIN core.exercises AS actual_exercise
    ON actual_exercise.id = exercise_performance.actual_exercise_id
WHERE set_performance.prescribed_set_id IS NULL;

CREATE VIEW exec.workout_unit_trace AS
SELECT
    calendar.plan_run_id,
    calendar.microcycle_ordinal,
    calendar.scheduled_date,
    calendar.plan_revision_id,
    calendar.plan_revision_no,
    calendar.workout_unit_track_id,
    calendar.workout_unit_logical_key,
    calendar.workout_unit_name,
    calendar.workout_session_id,
    calendar.status,
    calendar.completion_mode,
    calendar.workout_unit_prescription_id,
    calendar.workout_unit_performance_id,
    calendar.performance_status,
    performance.performance_comment,
    calendar.notes
FROM exec.workout_session_calendar AS calendar
LEFT JOIN exec.workout_unit_performances AS performance
    ON performance.id = calendar.workout_unit_performance_id;

CREATE VIEW exec.microcycle_trace AS
WITH session_summary AS (
    SELECT
        session.microcycle_id,
        count(*) AS scheduled_session_count,
        count(*) FILTER (WHERE session.status = 'completed') AS completed_session_count,
        count(*) FILTER (WHERE session.status = 'missed') AS missed_session_count,
        count(*) FILTER (WHERE session.status = 'cancelled') AS cancelled_session_count,
        count(*) FILTER (WHERE session.status = 'in_progress') AS in_progress_session_count
    FROM exec.workout_sessions AS session
    GROUP BY session.microcycle_id
), volume_summary AS (
    SELECT
        session.microcycle_id,
        sum(set_performance.load_kg * set_performance.repetitions) FILTER (
            WHERE set_performance.status = 'performed'
        ) AS performed_volume_load_kg
    FROM exec.workout_sessions AS session
    JOIN exec.workout_unit_prescriptions AS prescription
        ON prescription.workout_session_id = session.id
    JOIN exec.workout_unit_performances AS performance
        ON performance.workout_unit_prescription_id = prescription.id
    JOIN exec.exercise_unit_performances AS exercise_performance
        ON exercise_performance.workout_unit_performance_id = performance.id
    JOIN exec.set_performances AS set_performance
        ON set_performance.exercise_unit_performance_id = exercise_performance.id
    GROUP BY session.microcycle_id
)
SELECT
    run.id AS plan_run_id,
    microcycle.id AS microcycle_id,
    microcycle.ordinal,
    microcycle.starts_on,
    microcycle.ends_on,
    microcycle.plan_revision_id,
    revision.revision_no AS plan_revision_no,
    microcycle.classification,
    microcycle.notes,
    COALESCE(summary.scheduled_session_count, 0) AS scheduled_session_count,
    COALESCE(summary.completed_session_count, 0) AS completed_session_count,
    COALESCE(summary.missed_session_count, 0) AS missed_session_count,
    COALESCE(summary.cancelled_session_count, 0) AS cancelled_session_count,
    COALESCE(summary.in_progress_session_count, 0) AS in_progress_session_count,
    CASE
        WHEN COALESCE(summary.scheduled_session_count, 0) = 0 THEN NULL
        ELSE summary.completed_session_count::numeric / summary.scheduled_session_count
    END AS attendance_ratio,
    volume.performed_volume_load_kg
FROM exec.microcycles AS microcycle
JOIN exec.plan_runs AS run ON run.id = microcycle.plan_run_id
JOIN plans.plan_revisions AS revision ON revision.id = microcycle.plan_revision_id
LEFT JOIN session_summary AS summary ON summary.microcycle_id = microcycle.id
LEFT JOIN volume_summary AS volume ON volume.microcycle_id = microcycle.id;

CREATE VIEW exec.performed_load_time_series AS
SELECT
    run.id AS plan_run_id,
    workout_track.id AS workout_unit_track_id,
    workout_track.logical_key AS workout_unit_logical_key,
    exercise_track.id AS exercise_unit_track_id,
    exercise_track.logical_key AS exercise_unit_logical_key,
    actual_exercise.id AS exercise_id,
    actual_exercise.slug AS exercise_slug,
    actual_exercise.name AS exercise_name,
    microcycle.ordinal AS microcycle_ordinal,
    session.scheduled_date,
    set_performance.ordinal AS set_ordinal,
    set_performance.load_kg,
    set_performance.repetitions,
    set_performance.rir,
    set_performance.performance_comment,
    exercise_performance.engine_model_version,
    exercise_performance.etu_vector_snapshot
FROM exec.set_performances AS set_performance
JOIN exec.exercise_unit_performances AS exercise_performance
    ON exercise_performance.id = set_performance.exercise_unit_performance_id
JOIN exec.workout_unit_performances AS performance
    ON performance.id = exercise_performance.workout_unit_performance_id
JOIN exec.workout_unit_prescriptions AS prescription
    ON prescription.id = performance.workout_unit_prescription_id
JOIN exec.workout_sessions AS session
    ON session.id = prescription.workout_session_id
JOIN exec.plan_runs AS run ON run.id = session.plan_run_id
JOIN exec.microcycles AS microcycle ON microcycle.id = session.microcycle_id
JOIN exec.workout_unit_tracks AS workout_track
    ON workout_track.id = session.workout_unit_track_id
JOIN exec.exercise_unit_tracks AS exercise_track
    ON exercise_track.id = exercise_performance.exercise_unit_track_id
JOIN core.exercises AS actual_exercise
    ON actual_exercise.id = exercise_performance.actual_exercise_id
WHERE set_performance.status = 'performed';

CREATE VIEW exec.plan_run_event_history AS
SELECT
    event.plan_run_id,
    event.id AS event_id,
    event.occurred_at,
    event.event_type,
    event.title,
    event.details,
    microcycle.ordinal AS microcycle_ordinal,
    session.scheduled_date AS workout_session_date,
    exercise_track.name AS exercise_unit_name,
    from_revision.revision_no AS from_plan_revision_no,
    to_revision.revision_no AS to_plan_revision_no,
    event.metadata
FROM exec.plan_run_events AS event
LEFT JOIN exec.microcycles AS microcycle ON microcycle.id = event.microcycle_id
LEFT JOIN exec.workout_sessions AS session ON session.id = event.workout_session_id
LEFT JOIN exec.exercise_unit_tracks AS exercise_track
    ON exercise_track.id = event.exercise_unit_track_id
LEFT JOIN plans.plan_revisions AS from_revision
    ON from_revision.id = event.from_plan_revision_id
LEFT JOIN plans.plan_revisions AS to_revision
    ON to_revision.id = event.to_plan_revision_id;

COMMENT ON TABLE exec.workout_unit_tracks IS
    'Run-scoped stable workout-unit identity. Sessions from different plan revisions map to the same track when they are the same logical repeatable unit.';
COMMENT ON TABLE exec.exercise_unit_tracks IS
    'Run-scoped stable exercise-unit identity. progression_id is retained as lineage evidence but is not treated as a globally unique trace key.';
COMMENT ON TABLE exec.workout_unit_prescriptions IS
    'Immutable exposure-specific snapshot of the prescribed workout-unit.';
COMMENT ON TABLE exec.workout_unit_performances IS
    'Draft or finalized field-data artifact for a workout prescription; drafts support partial mobile synchronization.';
COMMENT ON COLUMN exec.exercise_unit_prescriptions.previous_exercise_performance_id IS
    'Prior finalized performance used during Post-Workout-Analysis for this independent exercise trace; null for its first prescription.';
COMMENT ON COLUMN exec.exercise_unit_performances.etu_vector_snapshot IS
    'Optional engine ETU input snapshot for future reproducible derived metrics; central performed facts remain relational.';
