export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      eyebrow: 'ATLAS DE EXERCÍCIOS · CRIADOR DE PLANOS · ANÁLISE DE TREINO', title: 'Entenda seu treino e monte um plano que faça sentido.', lead: 'Veja o que um exercício realmente faz, transforme exercícios em um plano semanal e observe os efeitos modelados no corpo. As respostas continuam simples — e você pode aprofundar quando quiser.', ctaPrimary: 'Abrir o Atlas', ctaSecondary: 'Ver a análise do plano', proof: ['mais de 150 técnicas documentadas', 'anatomia interativa', 'de uma série ao microciclo'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANÁLISE',
    },
    audiences: {
      eyebrow: '01 · PARA QUEM', title: 'E você — em que ponto está?', beginner: { tag: 'ESTOU COMEÇANDO', title: 'Começou a treinar e tudo parece desnecessariamente complicado?', body: 'Veja quais músculos trabalham, acompanhe a técnica passo a passo e entenda como séries, repetições e RIR formam um plano.', link: 'Abrir o Atlas de exercícios' }, advanced: { tag: 'QUERO IR MAIS FUNDO', title: 'Treina há algum tempo e quer entender de verdade o seu plano?', body: 'Compare variações e analise distribuição do estímulo, exposição articular e dívida de recuperação modelada até cada série.', link: 'Ver como a Análise funciona' }, coach: { tag: 'MONTO PLANOS PARA OUTROS', title: 'Treina atletas? Planeje e analise em um só sistema.', body: 'Crie microciclos com papéis, substituições, metas, RIR e modelos de progressão explícitos e depois analise o plano salvo.', link: 'Ver a seção para treinadores' },
    },
    loop: {
      s1: { title: 'Conheça o exercício', body: 'Técnica, músculos e faixas de repetições recomendadas.' }, s2: { title: 'Organize sua divisão', body: 'PPL, corpo inteiro ou estrutura própria — dias, descanso, séries e RIR.' }, s3: { title: 'Execute a análise', body: 'Distribuição do estímulo, recuperação e exposição articular — até a série.' }, s4: { title: 'Execute o plano e acompanhe o progresso', body: 'Execução, histórico de séries e tendência de força — a próxima etapa.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ATLAS DE EXERCÍCIOS', title: 'Não apenas “supino”. Uma técnica específica com premissas específicas.', body: 'Cada exercício é descrito como uma variação definida: equipamento, posição, trajetória, amplitude, critérios de falha técnica e perfil próprio de exposição modelada.', etuRows: { title: 'Exposição muscular em números', body: 'cm² brutos, parcela da capacidade estimada e intensidade relativa.' }, etuAnatomy: { title: 'Distribuição do estímulo no corpo', body: 'Mapa de calor normalizado pela FCSA estimada.' }, technique: { title: 'Técnica desta variação', body: 'Posição → execução → quando parar.' }, classification: { title: 'Classificação da variação', body: 'Nível mecânico, fonte de resistência e padrão de execução.' }, disclaimer: 'valores normalizados para um atleta de referência comum · seus resultados podem variar',
    },
    planBuilder: {
      eyebrow: '03 · CRIADOR DE PLANOS', title: 'Monte um plano com as partes que realmente importam.', body: 'Defina dias de treino e descanso, o papel de cada exercício, metas, substituições, séries, faixas de repetições e RIR. Um plano é um microciclo ordenado, não uma anotação.', roles: { label: 'PAPÉIS', body: 'Progressão principal · progressão secundária · acúmulo de volume · acessório.' }, slot: { label: 'SLOT', body: 'Preserve a intenção do slot mesmo quando for preciso trocar o exercício.' }, rest: { label: 'DESCANSO', body: 'Um dia de descanso não é uma célula vazia — ele define o tempo entre estímulos.' }, ctaPrimary: 'Abrir o Criador', ctaSecondary: 'Ver a análise', panelDays: { left: 'MICROCICLO ORDENADO', right: '7 dias · D01–D07' }, panelSlot: { left: 'SLOT · PRESCRIÇÃO DE SÉRIES', right: 'papel · exercício padrão · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · ANÁLISE DO PLANO', title: 'Um plano é mais do que a soma das séries.', body: 'Analise um rascunho salvo e veja para onde vai o estímulo, quais músculos fazem trabalho intencional ou incidental e como o modelo transporta a dívida de recuperação entre os dias.', strip: { left: 'MICROCICLO · LIMITES DOS DIAS', right: 'análise do rascunho salvo · atualize após mudanças' }, recovery: { title: 'Recuperação local após o treino', meta: 'hours_to_fresh' }, ranking: { title: 'Distribuição semanal do estímulo', meta: 'ETU/cm²/7d' }, debts: { title: 'Maiores dívidas modeladas', body: 'Estado de prontidão no limite do dia.' }, targeted: { title: 'Trabalho intencional e incidental', body: 'Veja o que o plano pretendia treinar e também o trabalho incidental dos exercícios escolhidos.' }, provenance: { title: 'Cada total tem uma origem', body: 'O resultado leva ao dia, exercício e série, com repetições efetivas e parâmetros do modelo.' }, disclaimer: 'resultado do modelo · não é dor muscular, tempo de cicatrização nem avaliação de risco de lesão',
    },
    muscleAtlas: {
      eyebrow: '05 · ATLAS DE MÚSCULOS', title: 'Conheça o músculo antes de contar séries para ele.', body: 'Anatomia, função, arquitetura, participação estimada dos tipos de fibra e exercícios com maior exposição modelada — em um só lugar.', specs: [{ k: 'MORFOLOGIA', v: 'massa, volume' }, { k: 'ARQUITETURA', v: 'penação, comprimento das fibras' }, { k: 'FIBRAS', v: 'participação estimada' }, { k: 'FCSA', v: 'referência de capacidade' }], note: 'FCSA não é contagem de fibras nem indicador de potencial hipertrófico. É uma área estimada de transmissão de força usada como denominador comum.', link: 'Ir do músculo aos exercícios',
    },
    features: {
      eyebrow: '06 · OUTROS RECURSOS', title: 'O restante do sistema, em resumo', technique: { title: 'Biblioteca de técnica', body: 'Posição, movimento, ROM, instruções, falha técnica, RIR e erros comuns.' }, io: { title: 'Importar / exportar plano', body: 'Leve uma estrutura simplificada para análise externa e volte com um documento validado.' }, mobile: { title: 'Modo de treino no celular', body: 'O treino de hoje e a técnica à mão durante a sessão.' }, progress: { title: 'Acompanhamento de progresso', body: 'Histórico de execução, tendências de força e modelos automatizados de progressão — também no coaching.' }, knowledge: { title: 'Base de conhecimento', body: 'Os artigos sobre músculos já funcionam; a base em expansão também cobrirá articulações e ligará Atlas e Análise.' },
    },
    model: {
      eyebrow: '07 · POR DENTRO', title: 'Não medimos biologia pela tela. Construímos um modelo de decisão explícito.', body: 'O treino de força acontece sob incerteza. O Agonez organiza premissas, estima consequências do plano e mostra a origem do resultado. Quando não há medição, chamamos de modelo.', chain: ['exercício', 'músculos', 'estímulo mecânico', 'recuperação', 'semana do plano', 'progressão'], expandHint: 'EXPANDA PARA VER OS DETALHES',
      etu: { title: 'ETU', summary: 'Quanto do estímulo de tensão de uma repetição efetiva chega a cada músculo.', caveat: 'Não é EMG, percentual de ativação nem medida de hipertrofia.' }, fcsa: { title: 'FCSA', summary: 'Um denominador comum para comparar músculos grandes e pequenos na mesma escala.', caveat: 'É demanda mecânica, não fadiga nem contagem de fibras.' }, recovery: { title: 'MRU · JRU', summary: 'Dívida muscular e articular modelada: sobe após a série e cai entre sessões.', caveat: 'Ferramenta comparativa, não relógio biológico nem avaliação de risco.' }, reference: { title: 'Atleta de referência', summary: 'As métricas do Atlas são calibradas em uma base descrita explicitamente.', caveat: 'Seus valores podem ser bem diferentes.' }, limits: { title: 'Limites do modelo', summary: 'O que o modelo não enxerga — escrito claramente, não escondido.', note: 'versão do modelo, premissas e diagnósticos continuam visíveis no aplicativo' },
    },
    coaches: {
      eyebrow: '08 · PARA TREINADORES', title: 'Atenda mais atletas sem abrir mão da qualidade do plano.', body: 'Modelo de microciclo, substituições prontas e auditoria automática no lugar de refazer uma planilha para cada cliente. O tempo de copiar séries fica para o coaching.', reuse: { title: 'Um plano reutilizável', body: 'Um microciclo criado uma vez — com papéis, séries e RIR — vira o ponto de partida do próximo atleta.' }, swap: { title: 'Uma substituição em segundos', body: 'Máquina ocupada ou articulação dolorida não destrói o plano: o slot mantém sua intenção.' }, audit: { title: 'Auditoria em vez de contagem manual', body: 'Distribuição do estímulo, trabalho incidental e dívida modelada são calculados; você julga o resultado.' }, argument: { title: 'Uma justificativa para o atleta', body: 'Mostre por que o plano é assim. A exportação JSON leva a estrutura completa.' }, cta: 'Criar o primeiro modelo', note: 'Contas de atletas e histórico de execução estão planejados — hoje você trabalha nos seus próprios planos.',
    },
    roadmap: {
      eyebrow: '09 · PARA ONDE VAMOS', title: 'Hoje: criação e análise. Depois: execução e acompanhamento ao longo do tempo.', athlete: { title: 'Acompanhamento de atletas', body: 'A próxima etapa conectará o plano ao histórico de execução: cargas, repetições, RIR, trocas, deloads e tendências de e1RM.', flow: ['Plano', 'Prescrição', 'Execução', 'Histórico'] }, mobile: { title: 'Modo de treino no celular', body: 'Durante a sessão, a próxima série é o que importa. O modo planejado mostrará o treino do dia e acesso rápido à técnica.', flow: ['Treino de hoje', 'Registrar execução', 'Técnica'] },
    },
    cta: { title: 'Comece com um exercício. Veja até onde pode aprofundar.', body: 'Da compreensão do movimento à decisão sobre o plano — respostas simples na superfície, modelos explícitos por baixo.', primary: 'Abrir o Atlas de exercícios', secondary: 'Criar um rascunho' }, footer: { navigation: 'Navegação da página inicial', links: { exerciseAtlas: 'Atlas de exercícios', muscleAtlas: 'Atlas de músculos', planBuilder: 'Criador de planos', analysis: 'Análise', model: 'Modelo' }, disclaimer: 'Os valores do Agonez são estimativas modeladas baseadas em premissas explícitas. Não são medições do seu corpo nem aconselhamento médico.' }, badges: { comingSoon: 'EM BREVE', experimental: 'MODELO EXPERIMENTAL' },
  },
}
