export default {
  home: {
    brand: { name: 'AGONEZ' },
    hero: {
      betaBadge: 'BETA PRIVADO · OUTONO DE 2026',
      waitlist: { label: 'Endereço de e-mail', placeholder: "voce{'@'}exemplo.com", button: 'Entrar na lista', note: 'Sem spam. Apenas um e-mail quando seu convite estiver pronto.', submitting: 'Entrando…', joined: 'Inscrito', success: 'Você está na lista. Enviaremos um e-mail quando seu convite estiver pronto.', error: 'Não foi possível salvar seu endereço. Tente novamente.', emailSubject: 'Beta privado do Agonez — pedido de acesso', emailBody: 'Olá,\n\nquero entrar na lista de espera do beta privado do Agonez.\n\nMeu e-mail: {email}\n\nQuero usar o Agonez para:\n' },
      eyebrow: 'ATLAS DE EXERCÍCIOS · CRIADOR DE PLANOS · ACOMPANHAMENTO DA PROGRESSÃO', title: 'Entenda seu treino e monte um plano que faça sentido.', lead: 'Veja quais músculos seu exercício realmente trabalha. Organize esses exercícios em um plano semanal e veja o que esse plano faz com seu corpo.', ctaPrimary: 'Abrir o Atlas', ctaSecondary: 'Ver a análise do plano', proof: ['mais de 150 exercícios', 'anatomia interativa', 'de uma repetição ao microciclo'], frameLabel: 'agonez · /plans/4x-week-lu-pp · ANÁLISE',
    },
    audiences: {
      eyebrow: '01 · PARA QUEM', title: 'E você — em que ponto está?', beginner: { tag: 'ESTOU COMEÇANDO', title: 'Está começando a treinar e tudo parece desnecessariamente complicado?', body: 'Veja quais músculos trabalham e acompanhe a técnica passo a passo. Experimente o Criador de Planos.', link: 'Abrir o Atlas de exercícios' }, advanced: { tag: 'QUERO IR MAIS FUNDO', title: 'Treina há algum tempo e quer entender de verdade o seu plano?', body: 'Compare variações e analise distribuição do estímulo, exposição articular e dívida de recuperação modelada. Confira se o seu plano é ideal.', link: 'Ver como a Análise funciona' }, coach: { tag: 'MONTO PLANOS PARA OUTROS', title: 'Treina atletas? Quer uma ferramenta profissional?', body: 'Crie microciclos com papéis, substituições, metas, RIR e modelos de progressão explícitos. Depois acompanhe o progresso dos seus atletas.', link: 'Ver a seção para treinadores' },
    },
    loop: {
      s1: { title: 'Conheça os exercícios', body: 'Técnica, músculos e faixas de repetições recomendadas.' }, s2: { title: 'Organize sua divisão', body: 'PPL, corpo inteiro ou estrutura própria — séries, RIR, carga e modelos de progressão.' }, s3: { title: 'Execute a análise', body: 'Distribuição do estímulo e recuperação muscular e articular — até cada série.' }, s4: { title: 'Execute o plano e acompanhe o progresso', body: 'Execução, histórico de séries e tendência de força — a próxima etapa do seu desenvolvimento.' },
    },
    exerciseAtlas: {
      eyebrow: '02 · ATLAS DE EXERCÍCIOS', title: 'Não apenas “supino”. Uma técnica específica com premissas específicas.', body: 'Cada exercício é descrito como uma variação definida: equipamento, posição, trajetória, amplitude, critérios de falha técnica e perfil próprio de exposição modelada.', etuRows: { title: 'Exposição muscular em números', body: 'cm² brutos, parcela da capacidade estimada e intensidade relativa.' }, etuAnatomy: { title: 'Distribuição do estímulo no corpo', body: 'Mapa de calor normalizado pela FCSA estimada.' }, technique: { title: 'Técnica desta variação', body: 'Posição → execução → quando parar.' }, classification: { title: 'Classificação da variação', body: 'Nível mecânico, fonte de resistência e padrão de execução.' }, disclaimer: 'valores normalizados para um atleta de referência comum · seus resultados podem variar',
    },
    planBuilder: {
      eyebrow: '03 · CRIADOR DE PLANOS', title: 'Monte um plano com as partes que realmente importam.', body: 'Defina dias de treino e descanso, o papel de cada exercício, metas, substituições, séries, faixas de repetições e RIR. Um plano é um microciclo ordenado, não uma anotação.', roles: { label: 'PAPÉIS', body: 'Progressão principal · progressão secundária · acúmulo de volume · acessório.' }, slot: { label: 'SLOT', body: 'Preserve a intenção do slot mesmo quando for preciso trocar o exercício.' }, rest: { label: 'DESCANSO', body: 'Um dia de descanso não é uma célula vazia — ele define o tempo entre estímulos.' }, ctaPrimary: 'Abrir o Criador', ctaSecondary: 'Ver a análise', panelDays: { left: 'MICROCICLO ORDENADO', right: '7 dias · D01–D07' }, panelSlot: { left: 'SLOT · PRESCRIÇÃO DE SÉRIES', right: 'papel · exercício padrão · RIR' },
    },
    planAnalysis: {
      eyebrow: '04 · ANÁLISE DO PLANO', title: 'Um plano é mais do que a soma das séries.', body: 'Analise um rascunho salvo e veja para onde vai o estímulo, quais músculos fazem trabalho intencional ou incidental e se conseguem se recuperar entre os dias.', strip: { left: 'MICROCICLO · LIMITES DOS DIAS', right: 'análise do rascunho salvo · atualize após mudanças' }, recovery: { title: 'Recuperação após o treino', meta: 'hours_to_fresh' }, ranking: { title: 'Número semanal de séries por músculo', meta: 'ETU/cm²/7d' }, debts: { title: 'Estado da recuperação muscular', body: 'Quando o músculo estará recuperado novamente?' }, targeted: { title: 'Trabalho intencional e incidental', body: 'Veja o que o plano pretendia treinar e também o trabalho incidental dos exercícios escolhidos.' }, provenance: { title: 'Cada total tem uma origem', body: 'O resultado leva ao dia, exercício e série, com repetições efetivas e parâmetros do modelo.' }, disclaimer: 'resultado do modelo · não é dor muscular, tempo de cicatrização nem avaliação de risco de lesão',
    },
    muscleAtlas: {
      eyebrow: '05 · ATLAS DE MÚSCULOS', title: 'Conheça o músculo antes de contar séries para ele.', body: 'Anatomia, função, arquitetura, participação estimada dos tipos de fibra e os melhores exercícios — em um só lugar.', specs: [{ k: 'MORFOLOGIA', v: 'massa, volume' }, { k: 'ARQUITETURA', v: 'penação, comprimento das fibras' }, { k: 'FIBRAS', v: 'participação estimada dos tipos I e II' }, { k: 'FCSA', v: 'unidade de força' }], note: 'FCSA não é contagem de fibras nem indicador de potencial hipertrófico. É uma área estimada de transmissão de força usada como denominador comum.', link: 'Ir do músculo aos exercícios',
    },
    features: {
      eyebrow: '06 · OUTROS RECURSOS', title: 'O restante do sistema, em resumo', technique: { title: 'Biblioteca de técnica', body: 'Posição, movimento, ROM, instruções, falha técnica, RIR e erros comuns.' }, io: { title: 'Importar / exportar plano', body: 'Baixe ou envie um plano facilmente como texto. Com a ajuda da IA, importar seus próprios planos fica simples.' }, mobile: { title: 'Treino no celular', body: 'Abra o aplicativo durante o treino e deixe que ele guie você pela sessão.' }, progress: { title: 'Acompanhamento de progresso', body: 'Histórico de execução, tendências de força e modelos automatizados de progressão — também no coaching.' }, knowledge: { title: 'Base de conhecimento', body: 'Uma base de conhecimento em formato de blog com fundamento científico. O Atlas também incluirá movimentos e articulações.' },
    },
    model: {
      eyebrow: '07 · POR DENTRO', title: 'Não medimos biologia pela tela. Construímos um modelo de decisão explícito.', body: 'O treino de força acontece sob incerteza. O Agonez organiza premissas, estima consequências do plano e mostra a origem do resultado. Quando não há medição, chamamos de modelo.', chain: ['exercício', 'músculos', 'estímulo mecânico', 'recuperação', 'semana do plano', 'progressão'], expandHint: 'EXPANDA PARA VER OS DETALHES',
      etu: { title: 'ETU', summary: 'Quanto do estímulo de tensão de uma repetição efetiva chega a cada músculo.', body: 'Um exercício não simplesmente “treina o peito”. Ele tem um perfil: parte da tensão vai para os músculos motores e parte para os estabilizadores. A ETU (Effective Tension Unit) estima essa distribuição para uma repetição efetiva, permitindo comparar numericamente duas variações do mesmo movimento.', caveat: 'Não é EMG, percentual de ativação nem medida de hipertrofia.' }, fcsa: { title: 'FCSA', summary: 'Um denominador comum para comparar músculos grandes e pequenos na mesma escala.', caveat: 'É demanda mecânica, não fadiga nem contagem de fibras.' }, recovery: { title: 'MRU · JRU', summary: 'Dívida muscular e articular modelada: sobe após a série e cai entre sessões.', body: 'Cada série adiciona dívida local aos músculos, e mais quanto mais perto chega da falha técnica. A dívida diminui com o tempo, então o intervalo entre estímulos do mesmo músculo faz parte do plano. A JRU faz o mesmo para as articulações.', caveat: 'Ferramenta comparativa, não relógio biológico nem avaliação de risco.' }, reference: { title: 'Atleta de referência', summary: 'As métricas do Atlas são calibradas em uma base descrita explicitamente.', caveat: 'Seu ponto de partida pode ser bem diferente, enquanto as relações relativas devem variar apenas de forma mínima.' }, limits: { title: 'Limites do modelo', summary: 'O que o modelo não enxerga — escrito claramente, não escondido.', note: 'versão do modelo, premissas e diagnósticos continuam visíveis no aplicativo' },
    },
    coaches: {
      eyebrow: '08 · PARA TREINADORES', title: 'Atenda mais atletas sem abrir mão da qualidade do acompanhamento.', body: 'Modelo de microciclo, substituições prontas e auditoria automática no lugar de refazer uma planilha para cada cliente. O tempo de copiar séries fica para o coaching.', reuse: { title: 'Um plano reutilizável', body: 'Um microciclo criado uma vez — com papéis, séries e RIR — vira o ponto de partida do próximo atleta.' }, swap: { title: 'Uma substituição em segundos', body: 'Máquina ocupada ou articulação dolorida não destrói o plano: o slot mantém sua intenção.' }, audit: { title: 'Auditoria em vez de contagem manual', body: 'Distribuição do estímulo, trabalho incidental, dívida modelada entre os dias e progressão de carga são calculados automaticamente; você julga o resultado.' }, argument: { title: 'Compartilhamento fácil', body: 'Envie um link ao atleta e ele terá um plano pronto para abrir no aplicativo.' }, adaptation: { title: 'Cada atleta é diferente', body: 'Percebe que um atleta não está se recuperando com o plano? Com o tempo, você o conhece melhor e pode ajustar os parâmetros do modelo especificamente para ele.' }, cta: 'Criar o primeiro modelo', note: 'Contas de atletas e histórico de execução estão planejados — hoje você trabalha nos seus próprios planos.',
    },
    roadmap: {
      eyebrow: '09 · PARA ONDE VAMOS', title: 'Hoje: criação e análise. Amanhã: execução e acompanhamento ao longo do tempo.', athlete: { title: 'Acompanhamento de atletas', body: 'A próxima etapa conectará o plano ao histórico de execução: cargas, repetições, RIR, trocas, deloads e tendências de e1RM.', flow: ['Plano', 'Prescrição', 'Execução', 'Histórico'] }, mobile: { title: 'Treino no celular', body: 'Durante a sessão, a próxima série é o que importa. O modo planejado mostrará o treino do dia e acesso rápido à técnica.', flow: ['Treino de hoje', 'Registrar execução', 'Técnica'] },
    },
    cta: { eyebrow: 'UM CONVITE ABERTO', title: 'Ajude a humanidade a alcançar a excelência no treinamento.', body: 'O Agonez está em uma fase inicial. Estamos construindo-o na interseção entre treinamento, ciência, engenharia e produto.', bodySecondary: 'Se você atua em uma dessas áreas e quer cocriar uma ferramenta baseada em problemas reais, conhecimento especializado e feedback crítico, estamos procurando você.', rolesLabel: 'Pessoas e perspectivas que queremos conhecer', roles: ['Personal trainers', 'Atletas', 'Biomecânicos', 'Ciência do esporte', 'Produto e engenharia', 'UX / pesquisa', 'Marketing', 'Primeiros parceiros e early adopters'], action: 'Vamos conversar', note: 'Abertos a conversas objetivas e colaborações com escopo claro. Abre seu aplicativo de e-mail.', emailSubject: 'Vamos construir o Agonez juntos', emailBody: 'Olá,\n\nquero conversar sobre como contribuir com o Agonez.\n\nMinha experiência ou ideia:\n' }, footer: { navigation: 'Navegação da página inicial', links: { exerciseAtlas: 'Atlas de exercícios', muscleAtlas: 'Atlas de músculos', planBuilder: 'Criador de planos', analysis: 'Análise', model: 'Modelo' }, disclaimer: 'Os valores do Agonez são estimativas modeladas baseadas em premissas explícitas. Não são medições do seu corpo nem aconselhamento médico.' }, badges: { comingSoon: 'EM BREVE', experimental: 'MODELO EXPERIMENTAL' },
  },
}
